CREATE TABLE [itis].[app_actual] (
    [id]                                          UNIQUEIDENTIFIER NULL,
    [type]                                        NVARCHAR (MAX)   NULL,
    [updated_at]                                  NVARCHAR (MAX)   NULL,
    [display]                                     NVARCHAR (MAX)   NULL,
    [annual_app_target_for_traffic_centre_id]     UNIQUEIDENTIFIER NULL,
    [annual_app_target_total_id]                  UNIQUEIDENTIFIER NULL,
    [app_target_id]                               UNIQUEIDENTIFIER NULL,
    [calendar_month_id]                           UNIQUEIDENTIFIER NULL,
    [calendar_quarter_id]                         UNIQUEIDENTIFIER NULL,
    [calendar_year_id]                            UNIQUEIDENTIFIER NULL,
    [quarterly_app_target_for_traffic_centre_id]  UNIQUEIDENTIFIER NULL,
    [quarterly_app_target_total_id]               UNIQUEIDENTIFIER NULL,
    [tc_who_submitted_id]                         UNIQUEIDENTIFIER NULL,
    [traffic_centre_id]                           UNIQUEIDENTIFIER NULL,
    [app_target_description]                      VARCHAR (MAX)    NULL,
    [calculated_preliminary_actual]               VARCHAR (MAX)    NULL,
    [corrective_action]                           VARCHAR (MAX)    NULL,
    [created_at]                                  VARCHAR (MAX)    NULL,
    [date_finalized_by_tc]                        VARCHAR (MAX)    NULL,
    [date_verified]                               VARCHAR (MAX)    NULL,
    [finalized_calculated_preliminary_actual]     VARCHAR (MAX)    NULL,
    [finalized_manually_added_preliminary_actual] VARCHAR (MAX)    NULL,
    [finalized_preliminary_actual_total]          VARCHAR (MAX)    NULL,
    [finalized_verified_actual]                   VARCHAR (MAX)    NULL,
    [has_been_verified_key]                       VARCHAR (MAX)    NULL,
    [has_been_verified_display]                   VARCHAR (MAX)    NULL,
    [last_date_calculated]                        VARCHAR (MAX)    NULL,
    [last_date_calculate_request_sent]            VARCHAR (MAX)    NULL,
    [manually_added_preliminary_actual]           VARCHAR (MAX)    NULL,
    [national_target]                             VARCHAR (MAX)    NULL,
    [percentage_achieved]                         VARCHAR (MAX)    NULL,
    [preliminary_actual_finalized_key]            VARCHAR (MAX)    NULL,
    [preliminary_actual_finalized_display]        VARCHAR (MAX)    NULL,
    [preliminary_actual_total]                    VARCHAR (MAX)    NULL,
    [regional_director_comment]                   VARCHAR (MAX)    NULL,
    [status_key]                                  VARCHAR (MAX)    NULL,
    [status_display]                              VARCHAR (MAX)    NULL,
    [submitted_by_rd_key]                         VARCHAR (MAX)    NULL,
    [submitted_by_rd_display]                     VARCHAR (MAX)    NULL,
    [target]                                      VARCHAR (MAX)    NULL,
    [tc_comment]                                  VARCHAR (MAX)    NULL,
    [verified_actual]                             VARCHAR (MAX)    NULL,
    [verifier_comment]                            VARCHAR (MAX)    NULL,
    [DeltaLogKey]                                 INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                                    INT              DEFAULT ((-1)) NOT NULL
);



