CREATE TABLE [itis].[event_WCG0104_New] (
    [id]                                            UNIQUEIDENTIFIER NULL,
    [type]                                          NVARCHAR (MAX)   NULL,
    [updated_at]                                    NVARCHAR (MAX)   NULL,
    [display]                                       NVARCHAR (MAX)   NULL,
    [control_room_user_id]                          UNIQUEIDENTIFIER NULL,
    [departure_point_id]                            UNIQUEIDENTIFIER NULL,
    [device_id]                                     UNIQUEIDENTIFIER NULL,
    [ems_user_id]                                   UNIQUEIDENTIFIER NULL,
    [first_break_location_id]                       UNIQUEIDENTIFIER NULL,
    [fme_destination_id]                            UNIQUEIDENTIFIER NULL,
    [land_transport_survey_user_id]                 UNIQUEIDENTIFIER NULL,
    [magistrates_court_id]                          UNIQUEIDENTIFIER NULL,
    [primary_driver_id]                             UNIQUEIDENTIFIER NULL,
    [primary_vehicle_id]                            UNIQUEIDENTIFIER NULL,
    [road_safety_user_id]                           UNIQUEIDENTIFIER NULL,
    [second_break_location_id]                      UNIQUEIDENTIFIER NULL,
    [shift_statistic_id]                            UNIQUEIDENTIFIER NULL,
    [site_id]                                       UNIQUEIDENTIFIER NULL,
    [third_break_location_id]                       UNIQUEIDENTIFIER NULL,
    [traffic_centre_id]                             UNIQUEIDENTIFIER NULL,
    [user_id]                                       UNIQUEIDENTIFIER NULL,
    [action_taken_key]                              VARCHAR (MAX)    NULL,
    [action_taken_display]                          VARCHAR (MAX)    NULL,
    [alcohol_and_drugs_key]                         VARCHAR (MAX)    NULL,
    [alcohol_and_drugs_display]                     VARCHAR (MAX)    NULL,
    [alcohol_level]                                 VARCHAR (MAX)    NULL,
    [alcohol_screening_key]                         VARCHAR (MAX)    NULL,
    [alcohol_screening_display]                     VARCHAR (MAX)    NULL,
    [alcohol_visual_screening_comment]              VARCHAR (MAX)    NULL,
    [amount_of_breaks_key]                          VARCHAR (MAX)    NULL,
    [amount_of_breaks_display]                      VARCHAR (MAX)    NULL,
    [arrival_time]                                  VARCHAR (MAX)    NULL,
    [blood_glucose_level]                           VARCHAR (MAX)    NULL,
    [blood_pressure_diastolic]                      VARCHAR (MAX)    NULL,
    [blood_pressure_systolic]                       VARCHAR (MAX)    NULL,
    [break_taken_key]                               VARCHAR (MAX)    NULL,
    [break_taken_display]                           VARCHAR (MAX)    NULL,
    [business_address_city]                         VARCHAR (MAX)    NULL,
    [business_address_code]                         VARCHAR (MAX)    NULL,
    [business_address_line1]                        VARCHAR (MAX)    NULL,
    [business_address_line2]                        VARCHAR (MAX)    NULL,
    [business_address_province_key]                 VARCHAR (MAX)    NULL,
    [business_address_province_display]             VARCHAR (MAX)    NULL,
    [business_telephone_number]                     VARCHAR (MAX)    NULL,
    [checked_brakes_steering_key]                   VARCHAR (MAX)    NULL,
    [checked_brakes_steering_display]               VARCHAR (MAX)    NULL,
    [checked_doors_windows_mirrors_key]             VARCHAR (MAX)    NULL,
    [checked_doors_windows_mirrors_display]         VARCHAR (MAX)    NULL,
    [checked_fuel_system_key]                       VARCHAR (MAX)    NULL,
    [checked_fuel_system_display]                   VARCHAR (MAX)    NULL,
    [checked_lights_key]                            VARCHAR (MAX)    NULL,
    [checked_lights_display]                        VARCHAR (MAX)    NULL,
    [checked_markings_signs_key]                    VARCHAR (MAX)    NULL,
    [checked_markings_signs_display]                VARCHAR (MAX)    NULL,
    [checked_numberplate_key]                       VARCHAR (MAX)    NULL,
    [checked_numberplate_display]                   VARCHAR (MAX)    NULL,
    [checked_passengers_key]                        VARCHAR (MAX)    NULL,
    [checked_passengers_display]                    VARCHAR (MAX)    NULL,
    [checked_seatbelts_key]                         VARCHAR (MAX)    NULL,
    [checked_seatbelts_display]                     VARCHAR (MAX)    NULL,
    [checked_tyres_key]                             VARCHAR (MAX)    NULL,
    [checked_tyres_display]                         VARCHAR (MAX)    NULL,
    [checked_windscreen_key]                        VARCHAR (MAX)    NULL,
    [checked_windscreen_display]                    VARCHAR (MAX)    NULL,
    [comments]                                      VARCHAR (MAX)    NULL,
    [completed_at]                                  VARCHAR (MAX)    NULL,
    [court_code]                                    VARCHAR (MAX)    NULL,
    [court_date]                                    VARCHAR (MAX)    NULL,
    [court_name]                                    VARCHAR (MAX)    NULL,
    [court_no]                                      VARCHAR (MAX)    NULL,
    [current_statutory_duties_sub_category_key]     VARCHAR (MAX)    NULL,
    [current_statutory_duties_sub_category_display] VARCHAR (MAX)    NULL,
    [custom_email_address]                          VARCHAR (MAX)    NULL,
    [date]                                          VARCHAR (MAX)    NULL,
    [datetime_impound_offence]                      VARCHAR (MAX)    NULL,
    [departure_time]                                VARCHAR (MAX)    NULL,
    [direction_key]                                 VARCHAR (MAX)    NULL,
    [direction_display]                             VARCHAR (MAX)    NULL,
    [disregard_instructions_key]                    VARCHAR (MAX)    NULL,
    [disregard_instructions_display]                VARCHAR (MAX)    NULL,
    [driver_identification_done_key]                VARCHAR (MAX)    NULL,
    [driver_identification_done_display]            VARCHAR (MAX)    NULL,
    [driver_signature]                              VARCHAR (MAX)    NULL,
    [driver_signature_for_survey]                   VARCHAR (MAX)    NULL,
    [driving_violations_key]                        VARCHAR (MAX)    NULL,
    [driving_violations_display]                    VARCHAR (MAX)    NULL,
    [elapsed_time_in_minutes]                       VARCHAR (MAX)    NULL,
    [ems_result_comments]                           VARCHAR (MAX)    NULL,
    [ems_testing_key]                               VARCHAR (MAX)    NULL,
    [ems_testing_display]                           VARCHAR (MAX)    NULL,
    [event_details_done_key]                        VARCHAR (MAX)    NULL,
    [event_details_done_display]                    VARCHAR (MAX)    NULL,
    [event_source_key]                              VARCHAR (MAX)    NULL,
    [event_source_display]                          VARCHAR (MAX)    NULL,
    [event_type_key]                                VARCHAR (MAX)    NULL,
    [event_type_display]                            VARCHAR (MAX)    NULL,
    [force_closed_type_key]                         VARCHAR (MAX)    NULL,
    [force_closed_type_display]                     VARCHAR (MAX)    NULL,
    [force_close_reason]                            VARCHAR (MAX)    NULL,
    [google_expected_duration_minutes]              VARCHAR (MAX)    NULL,
    [gps_location_latitude]                         VARCHAR (MAX)    NULL,
    [gps_location_longitude]                        VARCHAR (MAX)    NULL,
    [gps_location_altitude]                         VARCHAR (MAX)    NULL,
    [gps_location_horizontal_accuracy]              VARCHAR (MAX)    NULL,
    [gps_location_vertical_accuracy]                VARCHAR (MAX)    NULL,
    [gps_location_timestamp]                        VARCHAR (MAX)    NULL,
    [has_impound_violations_key]                    VARCHAR (MAX)    NULL,
    [has_impound_violations_display]                VARCHAR (MAX)    NULL,
    [has_moving_violation_key]                      VARCHAR (MAX)    NULL,
    [has_moving_violation_display]                  VARCHAR (MAX)    NULL,
    [has_no_ag_violations_key]                      VARCHAR (MAX)    NULL,
    [has_no_ag_violations_display]                  VARCHAR (MAX)    NULL,
    [has_violation_key]                             VARCHAR (MAX)    NULL,
    [has_violation_display]                         VARCHAR (MAX)    NULL,
    [heart_rate]                                    VARCHAR (MAX)    NULL,
    [is_archived_key]                               VARCHAR (MAX)    NULL,
    [is_archived_display]                           VARCHAR (MAX)    NULL,
    [is_draft_key]                                  VARCHAR (MAX)    NULL,
    [is_draft_display]                              VARCHAR (MAX)    NULL,
    [kilometer_distance]                            VARCHAR (MAX)    NULL,
    [location_description]                          VARCHAR (MAX)    NULL,
    [location_name]                                 VARCHAR (MAX)    NULL,
    [manual_sect_56]                                VARCHAR (MAX)    NULL,
    [manual_sect_56_2]                              VARCHAR (MAX)    NULL,
    [manual_sect_56_3]                              VARCHAR (MAX)    NULL,
    [manual_sect_56_4]                              VARCHAR (MAX)    NULL,
    [manual_sect_56_5]                              VARCHAR (MAX)    NULL,
    [manual_sect_56_6]                              VARCHAR (MAX)    NULL,
    [number_of_passengers]                          VARCHAR (MAX)    NULL,
    [number_of_people_wearing_seat_belts]           VARCHAR (MAX)    NULL,
    [officer_signature]                             VARCHAR (MAX)    NULL,
    [opened_at]                                     VARCHAR (MAX)    NULL,
    [operating_license_number]                      VARCHAR (MAX)    NULL,
    [operating_license_photo]                       VARCHAR (MAX)    NULL,
    [payment_date]                                  VARCHAR (MAX)    NULL,
    [place_brake_taken]                             VARCHAR (MAX)    NULL,
    [police_station]                                VARCHAR (MAX)    NULL,
    [public_transport_survey_completed_key]         VARCHAR (MAX)    NULL,
    [public_transport_survey_completed_display]     VARCHAR (MAX)    NULL,
    [regulatory_signs_key]                          VARCHAR (MAX)    NULL,
    [regulatory_signs_display]                      VARCHAR (MAX)    NULL,
    [residential_address_city]                      VARCHAR (MAX)    NULL,
    [residential_address_code]                      VARCHAR (MAX)    NULL,
    [residential_address_line1]                     VARCHAR (MAX)    NULL,
    [residential_address_line2]                     VARCHAR (MAX)    NULL,
    [residential_address_province_key]              VARCHAR (MAX)    NULL,
    [residential_address_province_display]          VARCHAR (MAX)    NULL,
    [residential_telephone_number]                  VARCHAR (MAX)    NULL,
    [reviewed_enatis_feedback_key]                  VARCHAR (MAX)    NULL,
    [reviewed_enatis_feedback_display]              VARCHAR (MAX)    NULL,
    [road_markings_key]                             VARCHAR (MAX)    NULL,
    [road_markings_display]                         VARCHAR (MAX)    NULL,
    [road_number]                                   VARCHAR (MAX)    NULL,
    [road_safety_comments]                          VARCHAR (MAX)    NULL,
    [road_safety_completed]                         VARCHAR (MAX)    NULL,
    [road_safety_topics_discussed_with]             VARCHAR (MAX)    NULL,
    [road_section]                                  VARCHAR (MAX)    NULL,
    [sect_56_at_near_by]                            VARCHAR (MAX)    NULL,
    [signed_at]                                     VARCHAR (MAX)    NULL,
    [speed_violations_key]                          VARCHAR (MAX)    NULL,
    [speed_violations_display]                      VARCHAR (MAX)    NULL,
    [status_key]                                    VARCHAR (MAX)    NULL,
    [status_display]                                VARCHAR (MAX)    NULL,
    [time_taken]                                    VARCHAR (MAX)    NULL,
    [total]                                         VARCHAR (MAX)    NULL,
    [transport_key]                                 VARCHAR (MAX)    NULL,
    [transport_display]                             VARCHAR (MAX)    NULL,
    [trip_type_key]                                 VARCHAR (MAX)    NULL,
    [trip_type_display]                             VARCHAR (MAX)    NULL,
    [vehicle_group_photo]                           VARCHAR (MAX)    NULL,
    [vehicle_identification_done_key]               VARCHAR (MAX)    NULL,
    [vehicle_identification_done_display]           VARCHAR (MAX)    NULL,
    [DeltaLogKey]                                   INT              NOT NULL,
    [AuditKey]                                      INT              NOT NULL
);

