CREATE TABLE [itis].[section56_form] (
    [id]                                   UNIQUEIDENTIFIER NULL,
    [type]                                 NVARCHAR (MAX)   NULL,
    [updated_at]                           NVARCHAR (MAX)   NULL,
    [display]                              NVARCHAR (MAX)   NULL,
    [driver_id]                            UNIQUEIDENTIFIER NULL,
    [event_id]                             UNIQUEIDENTIFIER NULL,
    [magistrates_court_id]                 UNIQUEIDENTIFIER NULL,
    [shift_statistic_id]                   UNIQUEIDENTIFIER NULL,
    [user_id]                              UNIQUEIDENTIFIER NULL,
    [vehicle_id]                           UNIQUEIDENTIFIER NULL,
    [age]                                  VARCHAR (MAX)    NULL,
    [business_address_city]                VARCHAR (MAX)    NULL,
    [business_address_code]                VARCHAR (MAX)    NULL,
    [business_address_line1]               VARCHAR (MAX)    NULL,
    [business_address_line2]               VARCHAR (MAX)    NULL,
    [business_address_province_key]        VARCHAR (MAX)    NULL,
    [business_address_province_display]    VARCHAR (MAX)    NULL,
    [business_telephone_number]            VARCHAR (MAX)    NULL,
    [cancelled_key]                        VARCHAR (MAX)    NULL,
    [cancelled_display]                    VARCHAR (MAX)    NULL,
    [cancelled_reason]                     VARCHAR (MAX)    NULL,
    [comment]                              VARCHAR (MAX)    NULL,
    [court_code]                           VARCHAR (MAX)    NULL,
    [court_date]                           VARCHAR (MAX)    NULL,
    [court_name]                           VARCHAR (MAX)    NULL,
    [court_no]                             VARCHAR (MAX)    NULL,
    [drivers_license_code]                 VARCHAR (MAX)    NULL,
    [driver_sex_key]                       VARCHAR (MAX)    NULL,
    [driver_sex_display]                   VARCHAR (MAX)    NULL,
    [email]                                VARCHAR (MAX)    NULL,
    [email_requested_key]                  VARCHAR (MAX)    NULL,
    [email_requested_display]              VARCHAR (MAX)    NULL,
    [id_number]                            VARCHAR (MAX)    NULL,
    [manual_entry_key]                     VARCHAR (MAX)    NULL,
    [manual_entry_display]                 VARCHAR (MAX)    NULL,
    [name]                                 VARCHAR (MAX)    NULL,
    [nationality_key]                      VARCHAR (MAX)    NULL,
    [nationality_display]                  VARCHAR (MAX)    NULL,
    [non_za_id_number]                     VARCHAR (MAX)    NULL,
    [number]                               VARCHAR (MAX)    NULL,
    [occupation]                           VARCHAR (MAX)    NULL,
    [payment_date]                         VARCHAR (MAX)    NULL,
    [residential_address_city]             VARCHAR (MAX)    NULL,
    [residential_address_code]             VARCHAR (MAX)    NULL,
    [residential_address_line1]            VARCHAR (MAX)    NULL,
    [residential_address_line2]            VARCHAR (MAX)    NULL,
    [residential_address_province_key]     VARCHAR (MAX)    NULL,
    [residential_address_province_display] VARCHAR (MAX)    NULL,
    [residential_telephone_number]         VARCHAR (MAX)    NULL,
    [surname]                              VARCHAR (MAX)    NULL,
    [system_populated_form_key]            VARCHAR (MAX)    NULL,
    [system_populated_form_display]        VARCHAR (MAX)    NULL,
    [time_generated]                       VARCHAR (MAX)    NULL,
    [vehicle_designation_key]              VARCHAR (MAX)    NULL,
    [vehicle_designation_display]          VARCHAR (MAX)    NULL,
    [violation_charges_arr]                VARCHAR (MAX)    NULL,
    [violation_charge_1]                   VARCHAR (MAX)    NULL,
    [violation_charge_2]                   VARCHAR (MAX)    NULL,
    [violation_charge_3]                   VARCHAR (MAX)    NULL,
    [violation_type_key]                   VARCHAR (MAX)    NULL,
    [violation_type_display]               VARCHAR (MAX)    NULL,
    [DeltaLogKey]                          INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                             INT              DEFAULT ((-1)) NOT NULL
);

