CREATE TABLE [itis].[task] (
    [id]                       UNIQUEIDENTIFIER NULL,
    [type]                     NVARCHAR (MAX)   NULL,
    [updated_at]               NVARCHAR (MAX)   NULL,
    [display]                  NVARCHAR (MAX)   NULL,
    [location_id]              UNIQUEIDENTIFIER NULL,
    [shift_id]                 UNIQUEIDENTIFIER NULL,
    [task_description_id]      UNIQUEIDENTIFIER NULL,
    [task_template_group_id]   UNIQUEIDENTIFIER NULL,
    [user_id]                  UNIQUEIDENTIFIER NULL,
    [adhoc_key]                VARCHAR (MAX)    NULL,
    [adhoc_display]            VARCHAR (MAX)    NULL,
    [archived_key]             VARCHAR (MAX)    NULL,
    [archived_display]         VARCHAR (MAX)    NULL,
    [date]                     VARCHAR (MAX)    NULL,
    [description]              VARCHAR (MAX)    NULL,
    [duration_key]             VARCHAR (MAX)    NULL,
    [duration_display]         VARCHAR (MAX)    NULL,
    [end_datetime]             VARCHAR (MAX)    NULL,
    [end_time]                 VARCHAR (MAX)    NULL,
    [other_location]           VARCHAR (MAX)    NULL,
    [sort]                     VARCHAR (MAX)    NULL,
    [start_datetime]           VARCHAR (MAX)    NULL,
    [start_time]               VARCHAR (MAX)    NULL,
    [task_template_group_name] VARCHAR (MAX)    NULL,
    [temp_template_store]      VARCHAR (MAX)    NULL,
    [temp_template_store_desc] VARCHAR (MAX)    NULL,
    [DeltaLogKey]              INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                 INT              DEFAULT ((-1)) NOT NULL
);

