CREATE TABLE [itis].[violation_charge] (
    [id]                          UNIQUEIDENTIFIER NULL,
    [type]                        NVARCHAR (MAX)   NULL,
    [updated_at]                  NVARCHAR (MAX)   NULL,
    [display]                     NVARCHAR (MAX)   NULL,
    [alert_id]                    UNIQUEIDENTIFIER NULL,
    [charge_code_id]              UNIQUEIDENTIFIER NULL,
    [event_id]                    UNIQUEIDENTIFIER NULL,
    [magistrates_court_id]        UNIQUEIDENTIFIER NULL,
    [section56_form_id]           UNIQUEIDENTIFIER NULL,
    [vehicle_id]                  UNIQUEIDENTIFIER NULL,
    [ag_key]                      VARCHAR (MAX)    NULL,
    [ag_display]                  VARCHAR (MAX)    NULL,
    [alternative_charge_code]     VARCHAR (MAX)    NULL,
    [amount]                      VARCHAR (MAX)    NULL,
    [average_kmh]                 VARCHAR (MAX)    NULL,
    [category]                    VARCHAR (MAX)    NULL,
    [charge_short_text]           VARCHAR (MAX)    NULL,
    [charge_text]                 VARCHAR (MAX)    NULL,
    [checkout_action_key]         VARCHAR (MAX)    NULL,
    [checkout_action_display]     VARCHAR (MAX)    NULL,
    [code]                        VARCHAR (MAX)    NULL,
    [comments]                    VARCHAR (MAX)    NULL,
    [court_code]                  VARCHAR (MAX)    NULL,
    [court_date]                  VARCHAR (MAX)    NULL,
    [court_name]                  VARCHAR (MAX)    NULL,
    [court_no]                    VARCHAR (MAX)    NULL,
    [is_asod_key]                 VARCHAR (MAX)    NULL,
    [is_asod_display]             VARCHAR (MAX)    NULL,
    [manual_sect56_number]        VARCHAR (MAX)    NULL,
    [payment_date]                VARCHAR (MAX)    NULL,
    [photo]                       VARCHAR (MAX)    NULL,
    [prdp_key]                    VARCHAR (MAX)    NULL,
    [prdp_display]                VARCHAR (MAX)    NULL,
    [regulation_number]           VARCHAR (MAX)    NULL,
    [removed_at_checkout_key]     VARCHAR (MAX)    NULL,
    [removed_at_checkout_display] VARCHAR (MAX)    NULL,
    [removed_at_checkout_reason]  VARCHAR (MAX)    NULL,
    [road_section]                VARCHAR (MAX)    NULL,
    [road_section_display_name]   VARCHAR (MAX)    NULL,
    [subcategory]                 VARCHAR (MAX)    NULL,
    [timestamp]                   VARCHAR (MAX)    NULL,
    [DeltaLogKey]                 INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                    INT              DEFAULT ((-1)) NOT NULL
);

