CREATE TABLE [sampleebat].[ebat_device] (
    [id]                                   UNIQUEIDENTIFIER NULL,
    [type]                                 NVARCHAR (MAX)   NULL,
    [updated_at]                           NVARCHAR (MAX)   NULL,
    [display]                              NVARCHAR (MAX)   NULL,
    [centre_id]                            UNIQUEIDENTIFIER NULL,
    [calibration_certificate]              VARCHAR (MAX)    NULL,
    [certificate_date_of_issue]            VARCHAR (MAX)    NULL,
    [certificate_number]                   VARCHAR (MAX)    NULL,
    [comments]                             VARCHAR (MAX)    NULL,
    [created_at]                           VARCHAR (MAX)    NULL,
    [created_by]                           VARCHAR (MAX)    NULL,
    [created_location_latitude]            VARCHAR (MAX)    NULL,
    [created_location_longitude]           VARCHAR (MAX)    NULL,
    [created_location_altitude]            VARCHAR (MAX)    NULL,
    [created_location_horizontal_accuracy] VARCHAR (MAX)    NULL,
    [created_location_vertical_accuracy]   VARCHAR (MAX)    NULL,
    [created_location_timestamp]           VARCHAR (MAX)    NULL,
    [created_signature]                    VARCHAR (MAX)    NULL,
    [date_of_next_calibration]             VARCHAR (MAX)    NULL,
    [make]                                 VARCHAR (MAX)    NULL,
    [manufacturer]                         VARCHAR (MAX)    NULL,
    [model]                                VARCHAR (MAX)    NULL,
    [serial]                               VARCHAR (MAX)    NULL,
    [status_key]                           VARCHAR (MAX)    NULL,
    [status_display]                       VARCHAR (MAX)    NULL,
    [DeltaLogKey]                          INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                             INT              DEFAULT ((-1)) NOT NULL
);

