CREATE TABLE [sampleebat].[vehicle] (
    [id]                                   UNIQUEIDENTIFIER NULL,
    [type]                                 NVARCHAR (MAX)   NULL,
    [updated_at]                           NVARCHAR (MAX)   NULL,
    [display]                              NVARCHAR (MAX)   NULL,
    [device_id]                            UNIQUEIDENTIFIER NULL,
    [ebat_report_id]                       UNIQUEIDENTIFIER NULL,
    [user_id]                              UNIQUEIDENTIFIER NULL,
    [address_street_1]                     VARCHAR (MAX)    NULL,
    [address_street_2]                     VARCHAR (MAX)    NULL,
    [address_street_3]                     VARCHAR (MAX)    NULL,
    [address_street_4]                     VARCHAR (MAX)    NULL,
    [address_street_5]                     VARCHAR (MAX)    NULL,
    [address_street_postal_code]           VARCHAR (MAX)    NULL,
    [economic_sector_description]          VARCHAR (MAX)    NULL,
    [enatis_lookup_type_key]               VARCHAR (MAX)    NULL,
    [enatis_lookup_type_display]           VARCHAR (MAX)    NULL,
    [enatis_summary]                       VARCHAR (MAX)    NULL,
    [enatis_time_updated]                  VARCHAR (MAX)    NULL,
    [engine_number]                        VARCHAR (MAX)    NULL,
    [engine_number_captured]               VARCHAR (MAX)    NULL,
    [have_checked_enatis_key]              VARCHAR (MAX)    NULL,
    [have_checked_enatis_display]          VARCHAR (MAX)    NULL,
    [initials]                             VARCHAR (MAX)    NULL,
    [license_certificate_number]           VARCHAR (MAX)    NULL,
    [license_certificate_number_captured]  VARCHAR (MAX)    NULL,
    [license_change_date]                  VARCHAR (MAX)    NULL,
    [license_expiry_date]                  VARCHAR (MAX)    NULL,
    [license_expiry_date_captured]         VARCHAR (MAX)    NULL,
    [license_number]                       VARCHAR (MAX)    NULL,
    [license_number_captured]              VARCHAR (MAX)    NULL,
    [nature_of_person_description]         VARCHAR (MAX)    NULL,
    [operating_license_number_captured]    VARCHAR (MAX)    NULL,
    [owner_id_document_number]             VARCHAR (MAX)    NULL,
    [owner_id_document_type]               VARCHAR (MAX)    NULL,
    [owner_id_document_type_code]          VARCHAR (MAX)    NULL,
    [previous_license_number]              VARCHAR (MAX)    NULL,
    [registration_description]             VARCHAR (MAX)    NULL,
    [roadworthy_status]                    VARCHAR (MAX)    NULL,
    [sap_clearance_status]                 VARCHAR (MAX)    NULL,
    [sap_mark_code]                        VARCHAR (MAX)    NULL,
    [sap_mark_description]                 VARCHAR (MAX)    NULL,
    [status_key]                           VARCHAR (MAX)    NULL,
    [status_display]                       VARCHAR (MAX)    NULL,
    [surname_business_name]                VARCHAR (MAX)    NULL,
    [timestamp_captured]                   VARCHAR (MAX)    NULL,
    [vehicle_colour]                       VARCHAR (MAX)    NULL,
    [vehicle_colour_captured]              VARCHAR (MAX)    NULL,
    [vehicle_description]                  VARCHAR (MAX)    NULL,
    [vehicle_description_captured]         VARCHAR (MAX)    NULL,
    [vehicle_gmv]                          VARCHAR (MAX)    NULL,
    [vehicle_make]                         VARCHAR (MAX)    NULL,
    [vehicle_make_captured]                VARCHAR (MAX)    NULL,
    [vehicle_model_description]            VARCHAR (MAX)    NULL,
    [vehicle_model_description_captured]   VARCHAR (MAX)    NULL,
    [vehicle_register_number]              VARCHAR (MAX)    NULL,
    [vehicle_register_number_captured]     VARCHAR (MAX)    NULL,
    [vehicle_registration_number]          VARCHAR (MAX)    NULL,
    [vehicle_registration_number_captured] VARCHAR (MAX)    NULL,
    [vehicle_state]                        VARCHAR (MAX)    NULL,
    [vehicle_usage_description]            VARCHAR (MAX)    NULL,
    [vin_chassis_number]                   VARCHAR (MAX)    NULL,
    [vin_chassis_number_captured]          VARCHAR (MAX)    NULL,
    [voluntary_lookup_key]                 VARCHAR (MAX)    NULL,
    [voluntary_lookup_display]             VARCHAR (MAX)    NULL,
    [DeltaLogKey]                          INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                             INT              DEFAULT ((-1)) NOT NULL
);

