CREATE TABLE [its].[day_statistic] (
    [id]                             UNIQUEIDENTIFIER NULL,
    [type]                           NVARCHAR (MAX)   NULL,
    [updated_at]                     NVARCHAR (MAX)   NULL,
    [display]                        NVARCHAR (MAX)   NULL,
    [admin_id]                       UNIQUEIDENTIFIER NULL,
    [inspector_id]                   UNIQUEIDENTIFIER NULL,
    [superior_id]                    UNIQUEIDENTIFIER NULL,
    [traffic_centre_id]              UNIQUEIDENTIFIER NULL,
    [alcohol_blitz]                  VARCHAR (MAX)    NULL,
    [alerts_comments]                VARCHAR (MAX)    NULL,
    [alerts_processed]               VARCHAR (MAX)    NULL,
    [asod_alerts_comments]           VARCHAR (MAX)    NULL,
    [asod_alerts_processed]          VARCHAR (MAX)    NULL,
    [asod_handheld_devices_deployed] VARCHAR (MAX)    NULL,
    [asod_hours_operated]            VARCHAR (MAX)    NULL,
    [asod_officers_deployed]         VARCHAR (MAX)    NULL,
    [asod_operating_comments]        VARCHAR (MAX)    NULL,
    [awareness_programs]             VARCHAR (MAX)    NULL,
    [completed_at]                   VARCHAR (MAX)    NULL,
    [date]                           VARCHAR (MAX)    NULL,
    [dog_unit]                       VARCHAR (MAX)    NULL,
    [general_tle]                    VARCHAR (MAX)    NULL,
    [home_affairs]                   VARCHAR (MAX)    NULL,
    [local_traffic]                  VARCHAR (MAX)    NULL,
    [metro_police]                   VARCHAR (MAX)    NULL,
    [opened_at]                      VARCHAR (MAX)    NULL,
    [overload_control]               VARCHAR (MAX)    NULL,
    [pedestrian_fatalities]          VARCHAR (MAX)    NULL,
    [prov_traffic]                   VARCHAR (MAX)    NULL,
    [public_transport_ops]           VARCHAR (MAX)    NULL,
    [report_type_key]                VARCHAR (MAX)    NULL,
    [report_type_display]            VARCHAR (MAX)    NULL,
    [road_fatalities]                VARCHAR (MAX)    NULL,
    [saps]                           VARCHAR (MAX)    NULL,
    [sars]                           VARCHAR (MAX)    NULL,
    [signature]                      VARCHAR (MAX)    NULL,
    [speed_ops]                      VARCHAR (MAX)    NULL,
    [status_key]                     VARCHAR (MAX)    NULL,
    [status_display]                 VARCHAR (MAX)    NULL,
    [stop_and_checks]                VARCHAR (MAX)    NULL,
    [supervisors_deployed]           VARCHAR (MAX)    NULL,
    [total_alerts]                   VARCHAR (MAX)    NULL,
    [total_asod_alerts]              VARCHAR (MAX)    NULL,
    [traffic_officer_deployed]       VARCHAR (MAX)    NULL,
    [vehicle_theft_unit]             VARCHAR (MAX)    NULL,
    [visible_policing]               VARCHAR (MAX)    NULL,
    [DeltaLogKey]                    INT              DEFAULT ((-1)) NOT NULL,
    [AuditLogKey]                    INT              DEFAULT ((-1)) NOT NULL
);

