CREATE TABLE [its].[operating_licence] (
    [id]                     UNIQUEIDENTIFIER NULL,
    [type]                   NVARCHAR (MAX)   NULL,
    [updated_at]             NVARCHAR (MAX)   NULL,
    [display]                NVARCHAR (MAX)   NULL,
    [public_vehicle_id]      UNIQUEIDENTIFIER NULL,
    [archived_key]           VARCHAR (MAX)    NULL,
    [archived_display]       VARCHAR (MAX)    NULL,
    [authority_text]         VARCHAR (MAX)    NULL,
    [authority_type]         VARCHAR (MAX)    NULL,
    [capacity]               VARCHAR (MAX)    NULL,
    [category]               VARCHAR (MAX)    NULL,
    [certificate_no]         VARCHAR (MAX)    NULL,
    [chassis_no]             VARCHAR (MAX)    NULL,
    [classification]         VARCHAR (MAX)    NULL,
    [conditions]             VARCHAR (MAX)    NULL,
    [created_at]             VARCHAR (MAX)    NULL,
    [destination]            VARCHAR (MAX)    NULL,
    [expiry_date]            VARCHAR (MAX)    NULL,
    [id_number]              VARCHAR (MAX)    NULL,
    [id_type]                VARCHAR (MAX)    NULL,
    [issue_date]             VARCHAR (MAX)    NULL,
    [issue_no]               VARCHAR (MAX)    NULL,
    [licence_no]             VARCHAR (MAX)    NULL,
    [make]                   VARCHAR (MAX)    NULL,
    [name]                   VARCHAR (MAX)    NULL,
    [operating_licence_type] VARCHAR (MAX)    NULL,
    [operator_no]            VARCHAR (MAX)    NULL,
    [origin]                 VARCHAR (MAX)    NULL,
    [registration_no]        VARCHAR (MAX)    NULL,
    [route_description]      VARCHAR (MAX)    NULL,
    [route_name]             VARCHAR (MAX)    NULL,
    [route_no]               VARCHAR (MAX)    NULL,
    [status]                 VARCHAR (MAX)    NULL,
    [trade_name]             VARCHAR (MAX)    NULL,
    [year]                   VARCHAR (MAX)    NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [AuditLogKey]            INT              DEFAULT ((-1)) NOT NULL
);

