CREATE TABLE [its].[shift] (
    [id]                   UNIQUEIDENTIFIER NULL,
    [type]                 NVARCHAR (MAX)   NULL,
    [updated_at]           NVARCHAR (MAX)   NULL,
    [display]              NVARCHAR (MAX)   NULL,
    [master_shift_id]      UNIQUEIDENTIFIER NULL,
    [roster_id]            UNIQUEIDENTIFIER NULL,
    [roster_assignment_id] UNIQUEIDENTIFIER NULL,
    [shift_time_id]        UNIQUEIDENTIFIER NULL,
    [shift_week_id]        UNIQUEIDENTIFIER NULL,
    [user_id]              UNIQUEIDENTIFIER NULL,
    [acknowledged_key]     VARCHAR (MAX)    NULL,
    [acknowledged_display] VARCHAR (MAX)    NULL,
    [archived_key]         VARCHAR (MAX)    NULL,
    [archived_display]     VARCHAR (MAX)    NULL,
    [date]                 VARCHAR (MAX)    NULL,
    [deleted_key]          VARCHAR (MAX)    NULL,
    [deleted_display]      VARCHAR (MAX)    NULL,
    [leave_key]            VARCHAR (MAX)    NULL,
    [leave_display]        VARCHAR (MAX)    NULL,
    [submission_datetime]  VARCHAR (MAX)    NULL,
    [submitted_key]        VARCHAR (MAX)    NULL,
    [submitted_display]    VARCHAR (MAX)    NULL,
    [user_shift_key]       VARCHAR (MAX)    NULL,
    [user_shift_display]   VARCHAR (MAX)    NULL,
    [week_day_key]         VARCHAR (MAX)    NULL,
    [week_day_display]     VARCHAR (MAX)    NULL,
    [DeltaLogKey]          INT              DEFAULT ((-1)) NOT NULL,
    [AuditLogKey]          INT              DEFAULT ((-1)) NOT NULL
);

