CREATE TABLE [its].[user] (
    [id]                           UNIQUEIDENTIFIER NULL,
    [type]                         NVARCHAR (MAX)   NULL,
    [updated_at]                   NVARCHAR (MAX)   NULL,
    [display]                      NVARCHAR (MAX)   NULL,
    [current_activity_id]          UNIQUEIDENTIFIER NULL,
    [current_alert_id]             UNIQUEIDENTIFIER NULL,
    [current_day_statistic_id]     UNIQUEIDENTIFIER NULL,
    [current_device_id]            UNIQUEIDENTIFIER NULL,
    [current_month_statistic_id]   UNIQUEIDENTIFIER NULL,
    [current_roster_assignment_id] UNIQUEIDENTIFIER NULL,
    [current_section56_numbers_id] UNIQUEIDENTIFIER NULL,
    [current_shift_statistic_id]   UNIQUEIDENTIFIER NULL,
    [last_potential_violation_id]  UNIQUEIDENTIFIER NULL,
    [operational_area_id]          UNIQUEIDENTIFIER NULL,
    [ppi_id]                       UNIQUEIDENTIFIER NULL,
    [roster_group_id]              UNIQUEIDENTIFIER NULL,
    [traffic_centre_id]            UNIQUEIDENTIFIER NULL,
    [designation]                  VARCHAR (MAX)    NULL,
    [duty_roster_admin_key]        VARCHAR (MAX)    NULL,
    [duty_roster_admin_display]    VARCHAR (MAX)    NULL,
    [email]                        VARCHAR (MAX)    NULL,
    [fingerprint]                  VARCHAR (MAX)    NULL,
    [id_number]                    VARCHAR (MAX)    NULL,
    [inactive_key]                 VARCHAR (MAX)    NULL,
    [inactive_display]             VARCHAR (MAX)    NULL,
    [infrastructure_number]        VARCHAR (MAX)    NULL,
    [is_control_room_key]          VARCHAR (MAX)    NULL,
    [is_control_room_display]      VARCHAR (MAX)    NULL,
    [is_verifier_key]              VARCHAR (MAX)    NULL,
    [is_verifier_display]          VARCHAR (MAX)    NULL,
    [kilometer_distance]           VARCHAR (MAX)    NULL,
    [mobile_number]                VARCHAR (MAX)    NULL,
    [name]                         VARCHAR (MAX)    NULL,
    [password]                     VARCHAR (MAX)    NULL,
    [persal_number]                VARCHAR (MAX)    NULL,
    [provincial_key]               VARCHAR (MAX)    NULL,
    [provincial_display]           VARCHAR (MAX)    NULL,
    [rank_key]                     VARCHAR (MAX)    NULL,
    [rank_display]                 VARCHAR (MAX)    NULL,
    [road_number]                  VARCHAR (MAX)    NULL,
    [road_section]                 VARCHAR (MAX)    NULL,
    [role_key]                     VARCHAR (MAX)    NULL,
    [role_display]                 VARCHAR (MAX)    NULL,
    [sect_56_begin]                VARCHAR (MAX)    NULL,
    [sect_56_end]                  VARCHAR (MAX)    NULL,
    [sect_56_last_used]            VARCHAR (MAX)    NULL,
    [sect_56_nn]                   VARCHAR (MAX)    NULL,
    [sect_56_nnn]                  VARCHAR (MAX)    NULL,
    [surname]                      VARCHAR (MAX)    NULL,
    [traffic_centre_string]        VARCHAR (MAX)    NULL,
    [vehicle_device_key]           VARCHAR (MAX)    NULL,
    [vehicle_device_display]       VARCHAR (MAX)    NULL,
    [work_number]                  VARCHAR (MAX)    NULL,
    [DeltaLogKey]                  INT              DEFAULT ((-1)) NOT NULL,
    [AuditLogKey]                  INT              DEFAULT ((-1)) NOT NULL
);

