CREATE TABLE [dbo].[DimDate] (
    [DateKey]                INT           NOT NULL,
    [CalendarMonth]          TINYINT       DEFAULT ((0)) NOT NULL,
    [CalendarQuarter]        TINYINT       DEFAULT ((0)) NOT NULL,
    [CalendarWeek]           TINYINT       DEFAULT ((0)) NOT NULL,
    [CalendarYear]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [CalendarYearMonthKey]   INT           DEFAULT ((0)) NOT NULL,
    [CalendarYearQuarterKey] INT           DEFAULT ((0)) NOT NULL,
    [CalendarYearWeekKey]    INT           DEFAULT ((0)) NOT NULL,
    [DayOfMonth]             TINYINT       DEFAULT ((0)) NOT NULL,
    [DayOfQuarter]           TINYINT       DEFAULT ((0)) NOT NULL,
    [DayOfWeekMonday]        TINYINT       DEFAULT ((0)) NOT NULL,
    [DayOfWeekName]          VARCHAR (10)  DEFAULT ('Unknown') NOT NULL,
    [DayOfWeekSaturday]      TINYINT       DEFAULT ((0)) NOT NULL,
    [DayOfWeekShortName]     VARCHAR (3)   DEFAULT ('UNK') NOT NULL,
    [DayOfWeekSunday]        TINYINT       DEFAULT ((0)) NOT NULL,
    [DayOfYear]              SMALLINT      DEFAULT ((0)) NOT NULL,
    [DaySuffix]              VARCHAR (5)   DEFAULT ('UNK') NOT NULL,
    [FullDate]               DATE          NULL,
    [IsFirstDayOfMonth]      VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsFirstDayOfQuarter]    VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsFirstDayOfYear]       VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsLastDayOfMonth]       VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsLastDayOfQuarter]     VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [ISLastDayOfYear]        VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsPublicHoliday]        VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsWeekend]              VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [IsWorkingDay]           VARCHAR (3)   DEFAULT ('No') NOT NULL,
    [MonthName]              VARCHAR (10)  DEFAULT ('Unknown') NOT NULL,
    [MonthOfQuarter]         TINYINT       DEFAULT ((0)) NOT NULL,
    [MonthShortName]         VARCHAR (3)   DEFAULT ('UNK') NOT NULL,
    [MonthYearName]          VARCHAR (15)  DEFAULT ('Unknown') NOT NULL,
    [PublicHolidayName]      VARCHAR (50)  DEFAULT ('Not Public Holiday') NOT NULL,
    [QuarterName]            VARCHAR (15)  DEFAULT ('Unknown') NOT NULL,
    [YearName]               VARCHAR (10)  DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]           CHAR (1)      DEFAULT ('Y') NOT NULL,
    [RowIsInferred]          CHAR (1)      DEFAULT ('N') NOT NULL,
    [RowStartDate]           DATETIME      DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]             DATETIME      DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]        VARCHAR (200) DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]         INT           DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT           DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT           DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT           DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimDate] PRIMARY KEY CLUSTERED ([DateKey] ASC),
    CONSTRAINT [FK_dbo_DimDate_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimDate_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

