CREATE TABLE [dbo].[DimEBATDevice] (
    [EBATDeviceKey]          INT              IDENTITY (1, 1) NOT NULL,
    [CalibrationCertificate] VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [CertificateDateOfIssue] DATE             NULL,
    [CertificateNumber]      VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [CreatedBy]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [CreatedDate]            DATE             NULL,
    [DateOfNextCalibration]  DATE             NULL,
    [DeviceMake]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [DeviceManufacturer]     VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [DeviceModel]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [DeviceStatus]           VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [EBATDevice]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [EBATDeviceID]           UNIQUEIDENTIFIER NULL,
    [SerialNumber]           VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]           CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]          CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]           DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]             DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]        VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimEBATDevice] PRIMARY KEY CLUSTERED ([EBATDeviceKey] ASC),
    CONSTRAINT [FK_dbo_DimEBATDevice_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimEBATDevice_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

