CREATE TABLE [dbo].[DimEBATRolePlayer] (
    [EBATRolePlayerKey]    INT              IDENTITY (1, 1) NOT NULL,
    [Authority]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [CentreOrStation]      VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [District]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [EBATRolePlayerID]     UNIQUEIDENTIFIER NULL,
    [FirstName]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [IDNumber]             VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [InfrastructureNumber] VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [IsOperator]           VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [MobileNumber]         VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [Municipality]         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Province]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RankOrRole]           VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Surname]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]         CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]        CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]         DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]           DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]      VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]          INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]      INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimEBATRolePlayer] PRIMARY KEY CLUSTERED ([EBATRolePlayerKey] ASC),
    CONSTRAINT [FK_dbo_DimEBATRolePlayer_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimEBATRolePlayer_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

