CREATE TABLE [dbo].[DimFlaggedVehicleTrip] (
    [FlaggedVehicleTripKey]             INT             IDENTITY (1, 1) NOT NULL,
    [AlertDeliveryDateTime]             DATETIME        NULL,
    [AverageSpeed]                      NUMERIC (11, 6) NULL,
    [EndTime]                           DATETIME        NULL,
    [FlagCloned]                        VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [FlagFatique]                       VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [FlagSpeeding]                      VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [FlagTurnaround]                    VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [FromToCamera]                      VARCHAR (100)   DEFAULT ('Unknown') NOT NULL,
    [IsAlertSent]                       VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [PreviousEndTime]                   DATETIME        NULL,
    [PreviousToCurrentActualDuration]   INT             NULL,
    [PreviousToCurrentCamera]           VARCHAR (100)   NULL,
    [PreviousToCurrentDistance]         INT             NULL,
    [PreviousToCurrentExpectedDuration] INT             NULL,
    [PreviousToCurrentImpliedSpeed]     NUMERIC (11, 6) NULL,
    [RegistrationNo]                    VARCHAR (20)    DEFAULT ('Unknown') NOT NULL,
    [Route]                             VARCHAR (30)    DEFAULT ('Unknown') NOT NULL,
    [StartTime]                         DATETIME        NULL,
    [TotalDistance]                     INT             NULL,
    [TripDuration]                      INT             NULL,
    [TurnaroundHours]                   INT             NULL,
    [RowIsCurrent]                      CHAR (1)        DEFAULT ('Y') NOT NULL,
    [RowIsInferred]                     CHAR (1)        DEFAULT ('N') NOT NULL,
    [RowStartDate]                      DATETIME        DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]                        DATETIME        DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]                   VARCHAR (200)   DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]                    INT             DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]                    INT             DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]                       INT             DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]                   INT             DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimFlaggedVehicleTrip] PRIMARY KEY CLUSTERED ([FlaggedVehicleTripKey] ASC),
    CONSTRAINT [FK_dbo_DimFlaggedVehicleTrip_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimFlaggedVehicleTrip_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

