CREATE TABLE [dbo].[DimOperator] (
    [OperatorKey]          INT              IDENTITY (1, 1) NOT NULL,
    [Authority]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Centre]               VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [District]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [FirstName]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [IDNumber]             VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [InfrastructureNumber] VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [IsOperator]           VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [Municipality]         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Operator]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [OperatorCertificate]  VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [OperatorID]           UNIQUEIDENTIFIER NULL,
    [Province]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RegionalArea]         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Role]                 VARCHAR (10)     DEFAULT ('Unknown') NOT NULL,
    [Surname]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]         CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]        CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]         DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]           DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]      VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]          INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]      INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimOperator] PRIMARY KEY CLUSTERED ([OperatorKey] ASC),
    CONSTRAINT [FK_dbo_DimOperator_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimOperator_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

