CREATE TABLE [dbo].[DimOfficer] (
    [OfficerKey]           INT              IDENTITY (1, 1) NOT NULL,
    [Authority]            VARCHAR (50)     DEFAULT ('UNknown') NOT NULL,
    [District]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [FirstNames]           VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [IdNumber]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [InfrastructureNumber] VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [Initials]             VARCHAR (10)     DEFAULT ('Unknown') NOT NULL,
    [MobileNumber]         VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [Municipality]         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Officer]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [OfficerId]            UNIQUEIDENTIFIER NULL,
    [OtherAuthority]       VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [OtherRank]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [OtherStation]         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Province]             VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Rank]                 VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Station]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Surname]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]         CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]        CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]         DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]           DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]      VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]          INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]      INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimOfficer] PRIMARY KEY CLUSTERED ([OfficerKey] ASC),
    CONSTRAINT [FK_dbo_DimOfficer_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimOfficer_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

