CREATE TABLE [dbo].[DimOperation_WCG0118] (
    [OperationKey]                  INT              IDENTITY (1, 1) NOT NULL,
    [ActualStartTime]               DATETIME         NULL,
    [ActualStopTime]                DATETIME         NULL,
    [ApprovalComment]               VARCHAR (1000)   NULL,
    [ApprovalDate]                  DATETIME         NULL,
    [ASODRoadSection]               VARCHAR (50)     NOT NULL,
    [AuthorisationDate]             DATETIME         NULL,
    [BriefingDoneBy]                VARCHAR (50)     NOT NULL,
    [CancellationReason]            VARCHAR (100)    NULL,
    [CompletionComment]             VARCHAR (1000)   NULL,
    [DebriefingDoneBy]              VARCHAR (50)     NOT NULL,
    [IsDistrictSafetyPlan]          VARCHAR (3)      NOT NULL,
    [IsRoadSafetyQualitySurvey]     VARCHAR (3)      NOT NULL,
    [Location]                      VARCHAR (100)    NOT NULL,
    [OperationalOfficer]            VARCHAR (100)    NOT NULL,
    [OperationDescription]          VARCHAR (100)    NOT NULL,
    [OperationID]                   UNIQUEIDENTIFIER NULL,
    [OperationStatus]               VARCHAR (30)     NOT NULL,
    [OperationSubType]              VARCHAR (200)    NOT NULL,
    [OperationType]                 VARCHAR (50)     NOT NULL,
    [PlannedStartTime]              DATETIME         NULL,
    [PlannedStopTime]               DATETIME         NULL,
    [Planner]                       VARCHAR (100)    NOT NULL,
    [SightingVehicleRegistrationNo] VARCHAR (20)     NOT NULL,
    [TrafficCentre]                 VARCHAR (50)     NOT NULL,
    [RowIsCurrent]                  CHAR (1)         NOT NULL,
    [RowIsInferred]                 CHAR (1)         NOT NULL,
    [RowStartDate]                  DATETIME         NOT NULL,
    [RowEndDate]                    DATETIME         NOT NULL,
    [RowChangeReason]               VARCHAR (200)    NOT NULL,
    [InsertAuditKey]                INT              NOT NULL,
    [UpdateAuditKey]                INT              NOT NULL,
    [DeltaLogKey]                   INT              NOT NULL,
    [ExceptionRowKey]               INT              NOT NULL
);

