CREATE TABLE [dbo].[DimOperation] (
    [OperationKey]                  INT              IDENTITY (1, 1) NOT NULL,
    [ActualStartTime]               DATETIME         NULL,
    [ActualStopTime]                DATETIME         NULL,
    [ApprovalComment]               VARCHAR (1000)   NULL,
    [ApprovalDate]                  DATETIME         NULL,
    [ASODRoadSection]               VARCHAR (50)     DEFAULT ('Not Applicable') NOT NULL,
    [AuthorisationDate]             DATETIME         NULL,
    [BriefingDoneBy]                VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [CancellationReason]            VARCHAR (100)    NULL,
    [CompletionComment]             VARCHAR (1000)   NULL,
    [DebriefingDoneBy]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [IsDistrictSafetyPlan]          VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [IsRoadSafetyQualitySurvey]     VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [Location]                      VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [OperationalOfficer]            VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [OperationDescription]          VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [OperationID]                   UNIQUEIDENTIFIER NULL,
    [OperationStatus]               VARCHAR (30)     DEFAULT ('Unknown') NOT NULL,
    [OperationSubType]              VARCHAR (200)    DEFAULT ('Unknown') NOT NULL,
    [OperationType]                 VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [PlannedStartTime]              DATETIME         NULL,
    [PlannedStopTime]               DATETIME         NULL,
    [Planner]                       VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [SightingVehicleRegistrationNo] VARCHAR (20)     DEFAULT ('Not Applicable') NOT NULL,
    [TrafficCentre]                 VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]                  CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]                 CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]                  DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]                    DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]               VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]                INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]                INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]                   INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]               INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimOperation] PRIMARY KEY CLUSTERED ([OperationKey] ASC),
    CONSTRAINT [FK_dbo_DimOperation_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimOperation_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

