CREATE TABLE [dbo].[DimRoster] (
    [RosterKey]              INT              IDENTITY (1, 1) NOT NULL,
    [IsArchived]             VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [IsDeleted]              VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [IsRevised]              VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [Roster]                 VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RosterGroup]            VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RosterGroupDescription] VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterGroupPPI]         VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterGroupReportsTo]   VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterGroupSPI]         VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterGUID]             UNIQUEIDENTIFIER NULL,
    [RosterStatus]           VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RowIsCurrent]           CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]          CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]           DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]             DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]        VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimRoster] PRIMARY KEY CLUSTERED ([RosterKey] ASC),
    CONSTRAINT [FK_dbo_DimRoster_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimRoster_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

