CREATE TABLE [dbo].[DimShift] (
    [ShiftKey]             INT              IDENTITY (1, 1) NOT NULL,
    [DurationHours]        NUMERIC (5, 2)   DEFAULT ((0)) NOT NULL,
    [EndTime]              TIME (7)         NULL,
    [IsOffDuty]            VARCHAR (3)      DEFAULT ('Yes') NOT NULL,
    [IsUserShift]          VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [Officer]              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RosterGroup]          VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RosterGroupPPI]       VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterGroupReportsTo] VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterGroupSPI]       VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [RosterStatus]         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RosterWeek]           VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Shift]                VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [ShiftDate]            DATE             NULL,
    [ShiftID]              UNIQUEIDENTIFIER NULL,
    [ShiftTime]            VARCHAR (30)     DEFAULT ('Unknown') NOT NULL,
    [ShiftTimeSort]        INT              DEFAULT ((0)) NOT NULL,
    [StartTime]            TIME (7)         NULL,
    [UserRole]             VARCHAR (30)     DEFAULT ('Unknown') NOT NULL,
    [WeekDay]              VARCHAR (10)     DEFAULT ('Unknown') NOT NULL,
    [WeekEndDate]          DATE             NULL,
    [WeekStartDate]        DATE             NULL,
    [RowIsCurrent]         CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]        CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]         DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]           DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]      VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]          INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]      INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimShift] PRIMARY KEY CLUSTERED ([ShiftKey] ASC),
    CONSTRAINT [FK_dbo_DimShift_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimShift_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

