CREATE TABLE [dbo].[DimTrip] (
    [TripKey]           INT             IDENTITY (1, 1) NOT NULL,
    [AverageSpeed]      NUMERIC (11, 6) NULL,
    [EndTime]           DATETIME        NULL,
    [FatiqueFlag]       VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [FromToCamera]      VARCHAR (100)   DEFAULT ('Unknown') NOT NULL,
    [PreviousEndTime]   DATETIME        NULL,
    [RegistrationNo]    VARCHAR (20)    DEFAULT ('Unknown') NOT NULL,
    [Route]             VARCHAR (15)    DEFAULT ('Unknown') NOT NULL,
    [SpeedingFlag]      VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [SpeedSectionCount] INT             NULL,
    [StartTime]         DATETIME        NULL,
    [TotalDistance]     NUMERIC (11, 3) NULL,
    [TripDuration]      NUMERIC (11, 3) NULL,
    [TurnaroundFlag]    VARCHAR (3)     DEFAULT ('No') NOT NULL,
    [TurnaroundHours]   INT             NULL,
    [RowIsCurrent]      CHAR (1)        DEFAULT ('Y') NOT NULL,
    [RowIsInferred]     CHAR (1)        DEFAULT ('N') NOT NULL,
    [RowStartDate]      DATETIME        DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]        DATETIME        DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]   VARCHAR (200)   DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]    INT             DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]    INT             DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]       INT             DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]   INT             DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimTrip] PRIMARY KEY CLUSTERED ([TripKey] ASC),
    CONSTRAINT [FK_dbo_DimTrip_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimTrip_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

