CREATE TABLE [dbo].[DimTrafficControlEvent] (
    [TrafficControlEventKey]            INT              IDENTITY (1, 1) NOT NULL,
    [ActionTaken]                       VARCHAR (50)     DEFAULT ('None') NOT NULL,
    [AlcoholLevel]                      VARCHAR (10)     DEFAULT ('N/A') NOT NULL,
    [AlcoholScreening]                  VARCHAR (30)     DEFAULT ('No Screening Performed') NOT NULL,
    [ArrivalTime]                       DATETIME         NULL,
    [BloodGlucoseLevel]                 NUMERIC (11, 2)  NULL,
    [BloodPressureDiastolic]            NUMERIC (11, 2)  NULL,
    [BloodPressureSystolic]             NUMERIC (11, 2)  NULL,
    [BrakeTakenLocation]                VARCHAR (50)     NULL,
    [DeparturePoint]                    VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [DepartureTime]                     DATETIME         NULL,
    [Destination]                       VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [EMSComments]                       VARCHAR (1000)   NULL,
    [EMSRepresentative]                 VARCHAR (50)     DEFAULT ('Not Applicable') NOT NULL,
    [EMSTestingStatus]                  VARCHAR (20)     DEFAULT ('Not Tested') NOT NULL,
    [EventCompletionDateTime]           DATETIME         NULL,
    [EventOpenDateTime]                 DATETIME         NULL,
    [EventSource]                       VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [ExpectedDurationMinutes]           NUMERIC (11, 2)  NULL,
    [ForcedCloseReason]                 VARCHAR (50)     DEFAULT ('Not Forced Closed') NOT NULL,
    [ForcedCloseType]                   VARCHAR (50)     DEFAULT ('Not Applicable') NOT NULL,
    [HasAlcoholAndDrugs]                VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasDisregardedInstructions]        VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasDrivingViolations]              VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasImpoundViolations]              VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasMovingViolations]               VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasNoAGViolations]                 VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasRegulatorySigns]                VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasRoadMarkings]                   VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasSpeedViolations]                VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HasViolation]                      VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [HeartRate]                         NUMERIC (11, 2)  NULL,
    [ImpoundOffenceDateTime]            DATETIME         NULL,
    [IsBrakeTaken]                      VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [IsEnatisFeedbackReviewed]          VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [IsPublicTransportSurveyCompleted]  VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [LandTransportSurveyRepresentative] VARCHAR (50)     DEFAULT ('Not Applicable') NOT NULL,
    [Latitude]                          NUMERIC (19, 5)  DEFAULT ((0)) NOT NULL,
    [Location]                          VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [Longitude]                         NUMERIC (19, 5)  DEFAULT ((0)) NOT NULL,
    [NumberOfPassengers]                INT              NULL,
    [NumberOfPeopleWearingSeatbelts]    INT              NULL,
    [PoliceStation]                     VARCHAR (50)     DEFAULT ('None') NOT NULL,
    [RoadSafetyComments]                VARCHAR (1000)   NULL,
    [RoadSafetyCompletedDateTime]       DATETIME         NULL,
    [RoadSafetyRepresentative]          VARCHAR (50)     DEFAULT ('Not Applicable') NOT NULL,
    [StatusCode]                        VARCHAR (30)     DEFAULT ('Unknown') NOT NULL,
    [TrafficControlEventGUID]           UNIQUEIDENTIFIER NULL,
    [TravelDirection]                   VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [TripType]                          VARCHAR (20)     DEFAULT ('Not Recorded') NOT NULL,
    [RowIsCurrent]                      CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]                     CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]                      DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]                        DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]                   VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]                    INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]                    INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]                       INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]                   INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimTrafficControlEvent] PRIMARY KEY CLUSTERED ([TrafficControlEventKey] ASC),
    CONSTRAINT [FK_dbo_DimTrafficControlEvent_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimTrafficControlEvent_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

