CREATE TABLE [dbo].[DimTrafficCentre] (
    [TrafficCentreKey]                 INT              IDENTITY (1, 1) NOT NULL,
    [Authority]                        VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [District]                         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [EmailAddress]                     VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [MagistratesCourt]                 VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [MagistratesCourtCode]             VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [MagistratesCourtNumber]           VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [Municipality]                     VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [MunicipalityHasElectronicPayment] VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [MunicipalityHasPostalPayment]     VARCHAR (3)      DEFAULT ('No') NOT NULL,
    [MunicipalityPlaceOfPayment]       VARCHAR (100)    DEFAULT ('Unknown') NOT NULL,
    [Province]                         VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RegionalArea]                     VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [RegionalDirector]                 VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [SecurityEmailList]                VARCHAR (1000)   NULL,
    [TCC]                              VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [TelephoneNo]                      VARCHAR (20)     DEFAULT ('Unknown') NOT NULL,
    [TrafficCentre]                    VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [TrafficCentreCode]                VARCHAR (50)     DEFAULT ('Unknown') NOT NULL,
    [TrafficCentreID]                  UNIQUEIDENTIFIER NULL,
    [RowIsCurrent]                     CHAR (1)         DEFAULT ('Y') NOT NULL,
    [RowIsInferred]                    CHAR (1)         DEFAULT ('N') NOT NULL,
    [RowStartDate]                     DATETIME         DEFAULT ('1 Jan 1900') NOT NULL,
    [RowEndDate]                       DATETIME         DEFAULT ('31 Dec 9999') NOT NULL,
    [RowChangeReason]                  VARCHAR (200)    DEFAULT ('New Row') NOT NULL,
    [InsertAuditKey]                   INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]                   INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]                      INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]                  INT              DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_dbo.DimTrafficCentre] PRIMARY KEY CLUSTERED ([TrafficCentreKey] ASC),
    CONSTRAINT [FK_dbo_DimTrafficCentre_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_DimTrafficCentre_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

