CREATE TABLE [dbo].[DimTrafficControlEvent_WCG0104] (
    [TrafficControlEventKey]            INT              IDENTITY (1, 1) NOT NULL,
    [ActionTaken]                       VARCHAR (50)     NOT NULL,
    [AlcoholLevel]                      VARCHAR (10)     NOT NULL,
    [AlcoholScreening]                  VARCHAR (30)     NOT NULL,
    [ArrivalTime]                       DATETIME         NULL,
    [BloodGlucoseLevel]                 NUMERIC (11, 2)  NULL,
    [BloodPressureDiastolic]            NUMERIC (11, 2)  NULL,
    [BloodPressureSystolic]             NUMERIC (11, 2)  NULL,
    [BrakeTakenLocation]                VARCHAR (50)     NULL,
    [DeparturePoint]                    VARCHAR (50)     NOT NULL,
    [DepartureTime]                     DATETIME         NULL,
    [Destination]                       VARCHAR (50)     NOT NULL,
    [EMSComments]                       VARCHAR (1000)   NULL,
    [EMSRepresentative]                 VARCHAR (50)     NOT NULL,
    [EMSTestingStatus]                  VARCHAR (20)     NOT NULL,
    [EventCompletionDateTime]           DATETIME         NULL,
    [EventOpenDateTime]                 DATETIME         NULL,
    [EventSource]                       VARCHAR (50)     NOT NULL,
    [ExpectedDurationMinutes]           NUMERIC (11, 2)  NULL,
    [ForcedCloseReason]                 VARCHAR (50)     NOT NULL,
    [ForcedCloseType]                   VARCHAR (50)     NOT NULL,
    [HasAlcoholAndDrugs]                VARCHAR (3)      NOT NULL,
    [HasDisregardedInstructions]        VARCHAR (3)      NOT NULL,
    [HasDrivingViolations]              VARCHAR (3)      NOT NULL,
    [HasImpoundViolations]              VARCHAR (3)      NOT NULL,
    [HasMovingViolations]               VARCHAR (3)      NOT NULL,
    [HasNoAGViolations]                 VARCHAR (3)      NOT NULL,
    [HasRegulatorySigns]                VARCHAR (3)      NOT NULL,
    [HasRoadMarkings]                   VARCHAR (3)      NOT NULL,
    [HasSpeedViolations]                VARCHAR (3)      NOT NULL,
    [HasViolation]                      VARCHAR (3)      NOT NULL,
    [HeartRate]                         NUMERIC (11, 2)  NULL,
    [ImpoundOffenceDateTime]            DATETIME         NULL,
    [IsBrakeTaken]                      VARCHAR (3)      NOT NULL,
    [IsEnatisFeedbackReviewed]          VARCHAR (3)      NOT NULL,
    [IsPublicTransportSurveyCompleted]  VARCHAR (3)      NOT NULL,
    [LandTransportSurveyRepresentitive] VARCHAR (50)     NOT NULL,
    [Latitude]                          NUMERIC (19, 5)  NOT NULL,
    [Location]                          VARCHAR (50)     NOT NULL,
    [Longitude]                         NUMERIC (19, 5)  NOT NULL,
    [NumberOfPassengers]                INT              NULL,
    [NumberOfPeopleWearingSeatbelts]    INT              NULL,
    [PoliceStation]                     VARCHAR (50)     NOT NULL,
    [RoadSafetyComments]                VARCHAR (1000)   NULL,
    [RoadSafetyCompletedDateTime]       DATETIME         NULL,
    [RoadSafetyRepresentative]          VARCHAR (50)     NOT NULL,
    [StatusCode]                        VARCHAR (30)     NOT NULL,
    [TrafficControlEventGUID]           UNIQUEIDENTIFIER NULL,
    [TravelDirection]                   VARCHAR (20)     NOT NULL,
    [TripType]                          VARCHAR (20)     NOT NULL,
    [RowIsCurrent]                      CHAR (1)         NOT NULL,
    [RowIsInferred]                     CHAR (1)         NOT NULL,
    [RowStartDate]                      DATETIME         NOT NULL,
    [RowEndDate]                        DATETIME         NOT NULL,
    [RowChangeReason]                   VARCHAR (200)    NOT NULL,
    [InsertAuditKey]                    INT              NOT NULL,
    [UpdateAuditKey]                    INT              NOT NULL,
    [DeltaLogKey]                       INT              NOT NULL,
    [ExceptionRowKey]                   INT              NOT NULL
);

