CREATE TABLE [dbo].[FactAlerts] (
    [AlertTypeKey]        INT          DEFAULT ((-1)) NOT NULL,
    [CameraKey]           INT          DEFAULT ((-1)) NOT NULL,
    [GeoLocationKey]      INT          DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]   INT          DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]    INT          DEFAULT ((-1)) NOT NULL,
    [UpdatedDateKey]      INT          DEFAULT ((-1)) NOT NULL,
    [UpdatedTimeKey]      INT          DEFAULT ((-1)) NOT NULL,
    [VehicleKey]          INT          DEFAULT ((-1)) NOT NULL,
    [AlertRecordID]       VARCHAR (15) NULL,
    [AlertStatus]         VARCHAR (50) NULL,
    [SourceAlertID]       VARCHAR (32) NULL,
    [SourceSystem]        VARCHAR (50) NULL,
    [SpeedClassCode]      VARCHAR (30) NULL,
    [VehicleCategory]     VARCHAR (50) NULL,
    [VehicleCategoryCode] VARCHAR (30) NULL,
    [VehicleUsage]        VARCHAR (50) NULL,
    [VehicleUsageCode]    VARCHAR (30) NULL,
    [AverageSpeed]        INT          DEFAULT ((0)) NOT NULL,
    [DurationAlert]       INT          NULL,
    [DurationPrimary]     INT          NULL,
    [SpeedLimit]          INT          NULL,
    [InsertAuditKey]      INT          DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]      INT          DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]         INT          DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]     INT          DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]         INT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactAlerts_AlertTypeKey] FOREIGN KEY ([AlertTypeKey]) REFERENCES [dbo].[DimAlertType] ([AlertTypeKey]),
    CONSTRAINT [FK_dbo_FactAlerts_CameraKey] FOREIGN KEY ([CameraKey]) REFERENCES [dbo].[DimCamera] ([CameraKey]),
    CONSTRAINT [FK_dbo_FactAlerts_GeoLocationKey] FOREIGN KEY ([GeoLocationKey]) REFERENCES [dbo].[DimGeoLocation] ([GeoLocationKey]),
    CONSTRAINT [FK_dbo_FactAlerts_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactAlerts_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactAlerts_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactAlerts_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactAlerts_UpdatedDateKey] FOREIGN KEY ([UpdatedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactAlerts_UpdatedTimeKey] FOREIGN KEY ([UpdatedTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactAlerts_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey])
);

