CREATE TABLE [dbo].[FactTrafficControlEventOutcomes] (
    [DeviceKey]              INT              DEFAULT ((-1)) NOT NULL,
    [DriverKey]              INT              DEFAULT ((-1)) NOT NULL,
    [MagistratesCourtKey]    INT              DEFAULT ((-1)) NOT NULL,
    [OpenDateKey]            INT              DEFAULT ((-1)) NOT NULL,
    [OpenTimeKey]            INT              DEFAULT ((-1)) NOT NULL,
    [OperationKey]           INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]      INT              DEFAULT ((-1)) NOT NULL,
    [Section56FormKey]       INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]       INT              DEFAULT ((-1)) NOT NULL,
    [TrafficControlEventKey] INT              DEFAULT ((-1)) NOT NULL,
    [UpdatedDateKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdatedTimeKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UserKey]                INT              DEFAULT ((-1)) NOT NULL,
    [VehicleKey]             INT              DEFAULT ((-1)) NOT NULL,
    [VehicleTypeKey]         INT              DEFAULT ((-1)) NOT NULL,
    [ViolationChargeKey]     INT              DEFAULT ((-1)) NOT NULL,
    [UniqueChargeID]         UNIQUEIDENTIFIER NULL,
    [UniqueSection56FormID]  UNIQUEIDENTIFIER NULL,
    [ChargeAmount]           NUMERIC (19, 2)  NULL,
    [InsertAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]            INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_DeviceKey] FOREIGN KEY ([DeviceKey]) REFERENCES [dbo].[DimDevice] ([DeviceKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_MagistratesCourtKey] FOREIGN KEY ([MagistratesCourtKey]) REFERENCES [dbo].[DimMagistratesCourt] ([MagistratesCourtKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_OpenDateKey] FOREIGN KEY ([OpenDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_OpenTimeKey] FOREIGN KEY ([OpenTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_OperationKey] FOREIGN KEY ([OperationKey]) REFERENCES [dbo].[DimOperation] ([OperationKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_Section56FormKey] FOREIGN KEY ([Section56FormKey]) REFERENCES [dbo].[DimSection56Form] ([Section56FormKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_TrafficControlEventKey] FOREIGN KEY ([TrafficControlEventKey]) REFERENCES [dbo].[DimTrafficControlEvent] ([TrafficControlEventKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_UpdatedDateKey] FOREIGN KEY ([UpdatedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_UpdatedTimeKey] FOREIGN KEY ([UpdatedTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_UserKey] FOREIGN KEY ([UserKey]) REFERENCES [dbo].[DimUser] ([UserKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_VehicleTypeKey] FOREIGN KEY ([VehicleTypeKey]) REFERENCES [dbo].[DimVehicleType] ([VehicleTypeKey]),
    CONSTRAINT [FK_dbo_FactTrafficControlEventOutcomes_ViolationChargeKey] FOREIGN KEY ([ViolationChargeKey]) REFERENCES [dbo].[DimViolationCharge] ([ViolationChargeKey])
);

