CREATE TABLE [dbo].[FactDeviceHistory] (
    [DeviceEventKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeviceKey]              INT              DEFAULT ((-1)) NOT NULL,
    [EventDateKey]           INT              DEFAULT ((-1)) NOT NULL,
    [EventTimeKey]           INT              DEFAULT ((-1)) NOT NULL,
    [GeoLocationKey]         INT              DEFAULT ((-1)) NOT NULL,
    [OperationKey]           INT              DEFAULT ((-1)) NOT NULL,
    [ShiftKey]               INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]       INT              DEFAULT ((-1)) NOT NULL,
    [TrafficControlEventKey] INT              DEFAULT ((-1)) NOT NULL,
    [UserKey]                INT              DEFAULT ((-1)) NOT NULL,
    [EventDateTime]          DATETIME         NULL,
    [EventStatus]            VARCHAR (10)     NULL,
    [EventValue]             VARCHAR (100)    NULL,
    [UniqueID]               UNIQUEIDENTIFIER NULL,
    [InsertAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]            INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactDeviceHistory_DeviceEventKey] FOREIGN KEY ([DeviceEventKey]) REFERENCES [dbo].[DimDeviceEvent] ([DeviceEventKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_DeviceKey] FOREIGN KEY ([DeviceKey]) REFERENCES [dbo].[DimDevice] ([DeviceKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_EventDateKey] FOREIGN KEY ([EventDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_EventTimeKey] FOREIGN KEY ([EventTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_GeoLocationKey] FOREIGN KEY ([GeoLocationKey]) REFERENCES [dbo].[DimGeoLocation] ([GeoLocationKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_OperationKey] FOREIGN KEY ([OperationKey]) REFERENCES [dbo].[DimOperation] ([OperationKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_ShiftKey] FOREIGN KEY ([ShiftKey]) REFERENCES [dbo].[DimShift] ([ShiftKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_TrafficControlEventKey] FOREIGN KEY ([TrafficControlEventKey]) REFERENCES [dbo].[DimTrafficControlEvent] ([TrafficControlEventKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactDeviceHistory_UserKey] FOREIGN KEY ([UserKey]) REFERENCES [dbo].[DimUser] ([UserKey])
);

