CREATE TABLE [dbo].[FactImpoundReleaseCosts] (
    [CreateDateKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DriverKey]             INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundInstructionKey] INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundJourneyUserKey] INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]     INT              DEFAULT ((-1)) NOT NULL,
    [PoundFacilityKey]      INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]      INT              DEFAULT ((-1)) NOT NULL,
    [VehicleKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ReleaseDescription]    VARCHAR (100)    NOT NULL,
    [ReleaseStatus]         VARCHAR (50)     NULL,
    [UniqueID]              UNIQUEIDENTIFIER NULL,
    [AmountPaid]            NUMERIC (19, 2)  NULL,
    [InsertAuditKey]        INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]           INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]           INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_CreateDateKey] FOREIGN KEY ([CreateDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_ImpoundInstructionKey] FOREIGN KEY ([ImpoundInstructionKey]) REFERENCES [dbo].[DimImpoundInstruction] ([ImpoundInstructionKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_ImpoundJourneyUserKey] FOREIGN KEY ([ImpoundJourneyUserKey]) REFERENCES [dbo].[DimJourneyUser] ([JourneyUserKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_PoundFacilityKey] FOREIGN KEY ([PoundFacilityKey]) REFERENCES [dbo].[DimPoundFacility] ([PoundFacilityKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundReleaseCosts_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey])
);

