CREATE TABLE [dbo].[FactShiftActivities] (
    [GeoLocationKey]       INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]    INT              DEFAULT ((-1)) NOT NULL,
    [ShiftActivityTypeKey] INT              DEFAULT ((-1)) NOT NULL,
    [ShiftDateKey]         INT              DEFAULT ((-1)) NOT NULL,
    [ShiftKey]             INT              DEFAULT ((-1)) NOT NULL,
    [ShiftLocationKey]     INT              DEFAULT ((-1)) NOT NULL,
    [ShiftTaskKey]         INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]     INT              DEFAULT ((-1)) NOT NULL,
    [UserKey]              INT              DEFAULT ((-1)) NOT NULL,
    [ActivityComment]      VARCHAR (100)    NULL,
    [ActivityEndTime]      TIME (7)         NULL,
    [ActivityStartTime]    TIME (7)         NULL,
    [IsAdhocActivity]      VARCHAR (3)      NULL,
    [OtherLocation]        VARCHAR (50)     NULL,
    [UniqueID]             UNIQUEIDENTIFIER NULL,
    [DurationHours]        NUMERIC (5, 2)   NULL,
    [InsertAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]          INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]      INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]          INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactShiftActivities_GeoLocationKey] FOREIGN KEY ([GeoLocationKey]) REFERENCES [dbo].[DimGeoLocation] ([GeoLocationKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_ShiftActivityTypeKey] FOREIGN KEY ([ShiftActivityTypeKey]) REFERENCES [dbo].[DimShiftActivityType] ([ShiftActivityTypeKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_ShiftDateKey] FOREIGN KEY ([ShiftDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_ShiftKey] FOREIGN KEY ([ShiftKey]) REFERENCES [dbo].[DimShift] ([ShiftKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_ShiftLocationKey] FOREIGN KEY ([ShiftLocationKey]) REFERENCES [dbo].[DimShiftLocation] ([ShiftLocationKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_ShiftTaskKey] FOREIGN KEY ([ShiftTaskKey]) REFERENCES [dbo].[DimShiftTask] ([ShiftTaskKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactShiftActivities_UserKey] FOREIGN KEY ([UserKey]) REFERENCES [dbo].[DimUser] ([UserKey])
);

