CREATE TABLE [dbo].[FactTrafficContraventions] (
    [DriverKey]           INT             DEFAULT ((-1)) NOT NULL,
    [MagistratesCourtKey] INT             DEFAULT ((-1)) NOT NULL,
    [OffenceDateKey]      INT             DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]    INT             DEFAULT ((-1)) NOT NULL,
    [VehicleKey]          INT             DEFAULT ((-1)) NOT NULL,
    [ViolationChargeKey]  INT             DEFAULT ((-1)) NOT NULL,
    [CaseResultDate]      DATE            NULL,
    [CourtDate]           DATE            NULL,
    [IssueDate]           DATE            NULL,
    [LastAction]          VARCHAR (50)    NULL,
    [LastActionDate]      DATE            NULL,
    [NoticeNumber]        VARCHAR (50)    NULL,
    [NoticeStage]         VARCHAR (30)    NULL,
    [NoticeStatus]        VARCHAR (30)    NULL,
    [NoticeType]          VARCHAR (30)    NULL,
    [PaymentDueDate]      DATE            NULL,
    [PaymentReceiptDate]  DATE            NULL,
    [ReceiptNumber]       VARCHAR (50)    NULL,
    [WarrantDate]         DATE            NULL,
    [CurrentAmount]       NUMERIC (11, 2) NULL,
    [OriginalAmount]      NUMERIC (11, 2) NULL,
    [PaidAmount]          NUMERIC (11, 2) NULL,
    [ReducedAmount]       NUMERIC (11, 2) NULL,
    [UnequalPaidAmount]   NUMERIC (11, 2) NULL,
    [WithdrawnAmount]     NUMERIC (11, 2) NULL,
    [InsertAuditKey]      INT             DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]      INT             DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]         INT             DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]     INT             DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]         INT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactTrafficContraventions_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_MagistratesCourtKey] FOREIGN KEY ([MagistratesCourtKey]) REFERENCES [dbo].[DimMagistratesCourt] ([MagistratesCourtKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_OffenceDateKey] FOREIGN KEY ([OffenceDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey]),
    CONSTRAINT [FK_dbo_FactTrafficContraventions_ViolationChargeKey] FOREIGN KEY ([ViolationChargeKey]) REFERENCES [dbo].[DimViolationCharge] ([ViolationChargeKey])
);

