CREATE TABLE [dbo].[FactImpoundViolationCharges] (
    [CreateDateKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DriverKey]             INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundInstructionKey] INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundJourneyUserKey] INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]     INT              DEFAULT ((-1)) NOT NULL,
    [PoundFacilityKey]      INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]      INT              DEFAULT ((-1)) NOT NULL,
    [VehicleKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ViolationChargeKey]    INT              DEFAULT ((-1)) NOT NULL,
    [UniqueID]              UNIQUEIDENTIFIER NULL,
    [InsertAuditKey]        INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]           INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]           INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_CreateDateKey] FOREIGN KEY ([CreateDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_ImpoundInstructionKey] FOREIGN KEY ([ImpoundInstructionKey]) REFERENCES [dbo].[DimImpoundInstruction] ([ImpoundInstructionKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_ImpoundJourneyUserKey] FOREIGN KEY ([ImpoundJourneyUserKey]) REFERENCES [dbo].[DimJourneyUser] ([JourneyUserKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_PoundFacilityKey] FOREIGN KEY ([PoundFacilityKey]) REFERENCES [dbo].[DimPoundFacility] ([PoundFacilityKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey]),
    CONSTRAINT [FK_dbo_FactImpoundViolationCharges_ViolationChargeKey] FOREIGN KEY ([ViolationChargeKey]) REFERENCES [dbo].[DimViolationCharge] ([ViolationChargeKey])
);

