CREATE TABLE [dbo].[FactShiftTasks] (
    [OperationsDateKey] INT              DEFAULT ((-1)) NOT NULL,
    [ShiftDateKey]      INT              DEFAULT ((-1)) NOT NULL,
    [ShiftKey]          INT              DEFAULT ((-1)) NOT NULL,
    [ShiftLocationKey]  INT              DEFAULT ((-1)) NOT NULL,
    [ShiftTaskKey]      INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]  INT              DEFAULT ((-1)) NOT NULL,
    [UserKey]           INT              DEFAULT ((-1)) NOT NULL,
    [IsAdhocTask]       VARCHAR (3)      NULL,
    [OtherLocation]     VARCHAR (50)     NULL,
    [TaskEndTime]       TIME (7)         NULL,
    [TaskStartTime]     TIME (7)         NULL,
    [UniqueID]          UNIQUEIDENTIFIER NULL,
    [DurationHours]     NUMERIC (5, 2)   NULL,
    [TaskTarget]        NUMERIC (11, 2)  NULL,
    [InsertAuditKey]    INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]    INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]       INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]   INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]       INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactShiftTasks_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_ShiftDateKey] FOREIGN KEY ([ShiftDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_ShiftKey] FOREIGN KEY ([ShiftKey]) REFERENCES [dbo].[DimShift] ([ShiftKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_ShiftLocationKey] FOREIGN KEY ([ShiftLocationKey]) REFERENCES [dbo].[DimShiftLocation] ([ShiftLocationKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_ShiftTaskKey] FOREIGN KEY ([ShiftTaskKey]) REFERENCES [dbo].[DimShiftTask] ([ShiftTaskKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactShiftTasks_UserKey] FOREIGN KEY ([UserKey]) REFERENCES [dbo].[DimUser] ([UserKey])
);

