CREATE TABLE [dbo].[FactRoadSafetyEducationEvents] (
    [CreateDateKey]          INT              DEFAULT ((-1)) NOT NULL,
    [CreateTimeKey]          INT              DEFAULT ((-1)) NOT NULL,
    [DriverKey]              INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]      INT              DEFAULT ((-1)) NOT NULL,
    [RoadSafetyTopicKey]     INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]       INT              DEFAULT ((-1)) NOT NULL,
    [TrafficControlEventKey] INT              DEFAULT ((-1)) NOT NULL,
    [UserKey]                INT              DEFAULT ((-1)) NOT NULL,
    [VehicleKey]             INT              DEFAULT ((-1)) NOT NULL,
    [UniqueID]               UNIQUEIDENTIFIER NULL,
    [InsertAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]            INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_CreateDateKey] FOREIGN KEY ([CreateDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_CreateTimeKey] FOREIGN KEY ([CreateTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_RoadSafetyTopicKey] FOREIGN KEY ([RoadSafetyTopicKey]) REFERENCES [dbo].[DimRoadSafetyTopic] ([RoadSafetyTopicKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_TrafficControlEventKey] FOREIGN KEY ([TrafficControlEventKey]) REFERENCES [dbo].[DimTrafficControlEvent] ([TrafficControlEventKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_UserKey] FOREIGN KEY ([UserKey]) REFERENCES [dbo].[DimUser] ([UserKey]),
    CONSTRAINT [FK_dbo_FactRoadSafetyEducationEvents_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey])
);

