CREATE TABLE [dbo].[FactAlerts_WCG0098] (
    [AlertTypeKey]        VARCHAR (50) NULL,
    [CameraKey]           VARCHAR (50) NULL,
    [GeoLocationKey]      VARCHAR (50) NULL,
    [OperationsDateKey]   VARCHAR (50) NULL,
    [TrafficCentreKey]    VARCHAR (50) NULL,
    [UpdatedDateKey]      VARCHAR (50) NULL,
    [UpdatedTimeKey]      INT          NULL,
    [VehicleKey]          INT          NOT NULL,
    [AlertRecordID]       INT          NULL,
    [AlertStatus]         INT          NULL,
    [SourceAlertID]       INT          NULL,
    [SourceSystem]        INT          NULL,
    [SpeedClassCode]      INT          NULL,
    [VehicleCategory]     INT          NULL,
    [VehicleCategoryCode] INT          NULL,
    [VehicleUsage]        INT          NULL,
    [VehicleUsageCode]    INT          NULL,
    [AverageSpeed]        INT          NULL,
    [DurationAlert]       INT          NULL,
    [DurationPrimary]     INT          NULL,
    [SpeedLimit]          INT          NULL,
    [InsertAuditKey]      INT          NULL,
    [UpdateAuditKey]      INT          NULL,
    [DeltaLogKey]         INT          NULL,
    [ExceptionRowKey]     INT          NULL,
    [DeletedFlag]         INT          NULL
);

