CREATE TABLE [dbo].[FactEBATEventDuration] (
    [EBATDeviceKey]       INT              DEFAULT ((-1)) NOT NULL,
    [EBATEventKey]        INT              DEFAULT ((-1)) NOT NULL,
    [EBATIncidentKey]     INT              DEFAULT ((-1)) NOT NULL,
    [EBATRoleKey]         INT              DEFAULT ((-1)) NOT NULL,
    [EBATRolePlayerKey]   INT              DEFAULT ((-1)) NOT NULL,
    [EventDateKey]        INT              DEFAULT ((-1)) NOT NULL,
    [EventTimeKey]        INT              DEFAULT ((-1)) NOT NULL,
    [MagistratesCourtKey] INT              DEFAULT ((-1)) NOT NULL,
    [OfficerKey]          INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]   INT              DEFAULT ((-1)) NOT NULL,
    [OperatorKey]         INT              DEFAULT ((-1)) NOT NULL,
    [EventId]             INT              NULL,
    [UniqueId]            UNIQUEIDENTIFIER NULL,
    [EventDuration]       INT              NULL,
    [InsertAuditKey]      INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]      INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]         INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]     INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]         INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EBATDeviceKey] FOREIGN KEY ([EBATDeviceKey]) REFERENCES [dbo].[DimEBATDevice] ([EBATDeviceKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EBATEventKey] FOREIGN KEY ([EBATEventKey]) REFERENCES [dbo].[DimEBATEvent] ([EBATEventKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EBATIncidentKey] FOREIGN KEY ([EBATIncidentKey]) REFERENCES [dbo].[DimEBATIncident] ([EBATIncidentKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EBATRoleKey] FOREIGN KEY ([EBATRoleKey]) REFERENCES [dbo].[DimEBATRole] ([EBATRoleKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EBATRolePlayerKey] FOREIGN KEY ([EBATRolePlayerKey]) REFERENCES [dbo].[DimEBATRolePlayer] ([EBATRolePlayerKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EventDateKey] FOREIGN KEY ([EventDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_EventTimeKey] FOREIGN KEY ([EventTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_MagistratesCourtKey] FOREIGN KEY ([MagistratesCourtKey]) REFERENCES [dbo].[DimMagistratesCourt] ([MagistratesCourtKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_OfficerKey] FOREIGN KEY ([OfficerKey]) REFERENCES [dbo].[DimOfficer] ([OfficerKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_OperatorKey] FOREIGN KEY ([OperatorKey]) REFERENCES [dbo].[DimOperator] ([OperatorKey]),
    CONSTRAINT [FK_dbo_FactEBATEventDuration_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey])
);

