CREATE TABLE [dbo].[FactImpoundRequests] (
    [DriverKey]              INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundInstructionKey]  INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]      INT              DEFAULT ((-1)) NOT NULL,
    [PoundFacilityKey]       INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]       INT              DEFAULT ((-1)) NOT NULL,
    [TrafficControlEventKey] INT              DEFAULT ((-1)) NOT NULL,
    [UpdateDateKey]          INT              DEFAULT ((-1)) NOT NULL,
    [UserKey]                INT              DEFAULT ((-1)) NOT NULL,
    [VehicleKey]             INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundOverrideReason]  VARCHAR (1000)   NULL,
    [ImpoundRequestStatus]   VARCHAR (10)     NULL,
    [IsImpoundOverridden]    VARCHAR (3)      NULL,
    [UniqueID]               UNIQUEIDENTIFIER NULL,
    [InsertAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]         INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]            INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactImpoundRequests_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_ImpoundInstructionKey] FOREIGN KEY ([ImpoundInstructionKey]) REFERENCES [dbo].[DimImpoundInstruction] ([ImpoundInstructionKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_PoundFacilityKey] FOREIGN KEY ([PoundFacilityKey]) REFERENCES [dbo].[DimPoundFacility] ([PoundFacilityKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_TrafficControlEventKey] FOREIGN KEY ([TrafficControlEventKey]) REFERENCES [dbo].[DimTrafficControlEvent] ([TrafficControlEventKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_UpdateDateKey] FOREIGN KEY ([UpdateDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_UserKey] FOREIGN KEY ([UserKey]) REFERENCES [dbo].[DimUser] ([UserKey]),
    CONSTRAINT [FK_dbo_FactImpoundRequests_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey])
);

