CREATE TABLE [dbo].[FactImpoundEvents] (
    [DriverKey]             INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundEventDateKey]   INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundEventTimeKey]   INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundInstructionKey] INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundJourneyUserKey] INT              DEFAULT ((-1)) NOT NULL,
    [OperationsDateKey]     INT              DEFAULT ((-1)) NOT NULL,
    [PoundFacilityKey]      INT              DEFAULT ((-1)) NOT NULL,
    [TrafficCentreKey]      INT              DEFAULT ((-1)) NOT NULL,
    [VehicleKey]            INT              DEFAULT ((-1)) NOT NULL,
    [ImpoundEvent]          VARCHAR (10)     NULL,
    [ImpoundEventDateTime]  DATETIME         NULL,
    [UniqueID]              UNIQUEIDENTIFIER NULL,
    [InsertAuditKey]        INT              DEFAULT ((-1)) NOT NULL,
    [UpdateAuditKey]        INT              DEFAULT ((-1)) NOT NULL,
    [DeltaLogKey]           INT              DEFAULT ((-1)) NOT NULL,
    [ExceptionRowKey]       INT              DEFAULT ((-1)) NOT NULL,
    [DeletedFlag]           INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_dbo_FactImpoundEvents_DriverKey] FOREIGN KEY ([DriverKey]) REFERENCES [dbo].[DimDriver] ([DriverKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_ImpoundEventDateKey] FOREIGN KEY ([ImpoundEventDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_ImpoundEventTimeKey] FOREIGN KEY ([ImpoundEventTimeKey]) REFERENCES [dbo].[DimTime] ([TimeKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_ImpoundInstructionKey] FOREIGN KEY ([ImpoundInstructionKey]) REFERENCES [dbo].[DimImpoundInstruction] ([ImpoundInstructionKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_ImpoundJourneyUserKey] FOREIGN KEY ([ImpoundJourneyUserKey]) REFERENCES [dbo].[DimJourneyUser] ([JourneyUserKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_InsertAuditKey] FOREIGN KEY ([InsertAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_OperationsDateKey] FOREIGN KEY ([OperationsDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_PoundFacilityKey] FOREIGN KEY ([PoundFacilityKey]) REFERENCES [dbo].[DimPoundFacility] ([PoundFacilityKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_TrafficCentreKey] FOREIGN KEY ([TrafficCentreKey]) REFERENCES [dbo].[DimTrafficCentre] ([TrafficCentreKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_UpdateAuditKey] FOREIGN KEY ([UpdateAuditKey]) REFERENCES [dbo].[DimAudit] ([AuditKey]),
    CONSTRAINT [FK_dbo_FactImpoundEvents_VehicleKey] FOREIGN KEY ([VehicleKey]) REFERENCES [dbo].[DimVehicle] ([VehicleKey])
);

