
CREATE PROCEDURE [itis].[prcExtractsection56_form]

--------------------------------------------------------------------------------------------------------------------------------------
-- Author				:	Generated from Model
-- Date Created			:	07-04-2018 01:33:31
-- Reason				:	Reads JSON file and inserts data into Stage table (section56_form)
--------------------------------------------------------------------------------------------------------------------------------------
-- Inputs				:	@FileName, @DeltaLogKey, @AuditKey
-- Ouputs				:	@RowCountStage
-- Test					:	exec itis.prcExtractsection56_form 'D:\PSA\TCE2\sample\section56_form.json'
--------------------------------------------------------------------------------------------------------------------------------------
-- Modified By	:
-- Modified On	:
-- Reason				:
--------------------------------------------------------------------------------------------------------------------------------------

@FileName NVARCHAR(MAX),
@DeltaLogKey INT = -1,
@AuditKey INT = -1,
@TruncateFlag INT = 1

AS

IF @TruncateFlag = 1 TRUNCATE TABLE [itis].[section56_form]

DECLARE @sql AS NVARCHAR(MAX)

SET @sql = 'DECLARE @json NVARCHAR(MAX) ' + CHAR(13)
SET @sql = @sql + 'SELECT @json = BulkColumn FROM OPENROWSET (BULK ''' + @FileName + ''', SINGLE_CLOB) as j' + CHAR(13)
SET @sql = @sql + 'INSERT INTO [itis].[section56_form] (' + CHAR(13)
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
--Insert Begin
SET @sql = @sql + '[driver_id], ' + CHAR(13)
SET @sql = @sql + '[event_id], ' + CHAR(13)
SET @sql = @sql + '[magistrates_court_id], ' + CHAR(13)
SET @sql = @sql + '[shift_statistic_id], ' + CHAR(13)
SET @sql = @sql + '[user_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_id], ' + CHAR(13)
SET @sql = @sql + '[age], ' + CHAR(13)
SET @sql = @sql + '[business_address_city], ' + CHAR(13)
SET @sql = @sql + '[business_address_code], ' + CHAR(13)
SET @sql = @sql + '[business_address_line1], ' + CHAR(13)
SET @sql = @sql + '[business_address_line2], ' + CHAR(13)
SET @sql = @sql + '[business_address_province_key], ' + CHAR(13)
SET @sql = @sql + '[business_address_province_display], ' + CHAR(13)
SET @sql = @sql + '[business_telephone_number], ' + CHAR(13)
SET @sql = @sql + '[cancelled_key], ' + CHAR(13)
SET @sql = @sql + '[cancelled_display], ' + CHAR(13)
SET @sql = @sql + '[cancelled_reason], ' + CHAR(13)
SET @sql = @sql + '[comment], ' + CHAR(13)
SET @sql = @sql + '[court_code], ' + CHAR(13)
SET @sql = @sql + '[court_date], ' + CHAR(13)
SET @sql = @sql + '[court_name], ' + CHAR(13)
SET @sql = @sql + '[court_no], ' + CHAR(13)
SET @sql = @sql + '[drivers_license_code], ' + CHAR(13)
SET @sql = @sql + '[driver_sex_key], ' + CHAR(13)
SET @sql = @sql + '[driver_sex_display], ' + CHAR(13)
SET @sql = @sql + '[email], ' + CHAR(13)
SET @sql = @sql + '[email_requested_key], ' + CHAR(13)
SET @sql = @sql + '[email_requested_display], ' + CHAR(13)
SET @sql = @sql + '[id_number], ' + CHAR(13)
SET @sql = @sql + '[manual_entry_key], ' + CHAR(13)
SET @sql = @sql + '[manual_entry_display], ' + CHAR(13)
SET @sql = @sql + '[name], ' + CHAR(13)
SET @sql = @sql + '[nationality_key], ' + CHAR(13)
SET @sql = @sql + '[nationality_display], ' + CHAR(13)
SET @sql = @sql + '[non_za_id_number], ' + CHAR(13)
SET @sql = @sql + '[number], ' + CHAR(13)
SET @sql = @sql + '[occupation], ' + CHAR(13)
SET @sql = @sql + '[payment_date], ' + CHAR(13)
SET @sql = @sql + '[residential_address_city], ' + CHAR(13)
SET @sql = @sql + '[residential_address_code], ' + CHAR(13)
SET @sql = @sql + '[residential_address_line1], ' + CHAR(13)
SET @sql = @sql + '[residential_address_line2], ' + CHAR(13)
SET @sql = @sql + '[residential_address_province_key], ' + CHAR(13)
SET @sql = @sql + '[residential_address_province_display], ' + CHAR(13)
SET @sql = @sql + '[residential_telephone_number], ' + CHAR(13)
SET @sql = @sql + '[surname], ' + CHAR(13)
SET @sql = @sql + '[system_populated_form_key], ' + CHAR(13)
SET @sql = @sql + '[system_populated_form_display], ' + CHAR(13)
SET @sql = @sql + '[time_generated], ' + CHAR(13)
SET @sql = @sql + '[vehicle_designation_key], ' + CHAR(13)
SET @sql = @sql + '[vehicle_designation_display], ' + CHAR(13)
SET @sql = @sql + '[violation_charges_arr], ' + CHAR(13)
SET @sql = @sql + '[violation_charge_1], ' + CHAR(13)
SET @sql = @sql + '[violation_charge_2], ' + CHAR(13)
SET @sql = @sql + '[violation_charge_3], ' + CHAR(13)
SET @sql = @sql + '[violation_type_key], ' + CHAR(13)
SET @sql = @sql + '[violation_type_display], ' + CHAR(13)
SET @sql = @sql + '[deltalogkey],' + CHAR(13)
SET @sql = @sql + '[AuditKey]' + CHAR(13)
--Insert End
SET @sql = @sql + ')' + CHAR(13)
SET @sql = @sql + 'SELECT ' 
--Select Begin
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
SET @sql = @sql + '[driver_id], ' + CHAR(13)
SET @sql = @sql + '[event_id], ' + CHAR(13)
SET @sql = @sql + '[magistrates_court_id], ' + CHAR(13)
SET @sql = @sql + '[shift_statistic_id], ' + CHAR(13)
SET @sql = @sql + '[user_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_id], ' + CHAR(13)
SET @sql = @sql + '[age], ' + CHAR(13)
SET @sql = @sql + '[business_address_city], ' + CHAR(13)
SET @sql = @sql + '[business_address_code], ' + CHAR(13)
SET @sql = @sql + '[business_address_line1], ' + CHAR(13)
SET @sql = @sql + '[business_address_line2], ' + CHAR(13)
SET @sql = @sql + '[business_address_province_key], ' + CHAR(13)
SET @sql = @sql + '[business_address_province_display], ' + CHAR(13)
SET @sql = @sql + '[business_telephone_number], ' + CHAR(13)
SET @sql = @sql + '[cancelled_key], ' + CHAR(13)
SET @sql = @sql + '[cancelled_display], ' + CHAR(13)
SET @sql = @sql + '[cancelled_reason], ' + CHAR(13)
SET @sql = @sql + '[comment], ' + CHAR(13)
SET @sql = @sql + '[court_code], ' + CHAR(13)
SET @sql = @sql + '[court_date], ' + CHAR(13)
SET @sql = @sql + '[court_name], ' + CHAR(13)
SET @sql = @sql + '[court_no], ' + CHAR(13)
SET @sql = @sql + '[drivers_license_code], ' + CHAR(13)
SET @sql = @sql + '[driver_sex_key], ' + CHAR(13)
SET @sql = @sql + '[driver_sex_display], ' + CHAR(13)
SET @sql = @sql + '[email], ' + CHAR(13)
SET @sql = @sql + '[email_requested_key], ' + CHAR(13)
SET @sql = @sql + '[email_requested_display], ' + CHAR(13)
SET @sql = @sql + '[id_number], ' + CHAR(13)
SET @sql = @sql + '[manual_entry_key], ' + CHAR(13)
SET @sql = @sql + '[manual_entry_display], ' + CHAR(13)
SET @sql = @sql + '[name], ' + CHAR(13)
SET @sql = @sql + '[nationality_key], ' + CHAR(13)
SET @sql = @sql + '[nationality_display], ' + CHAR(13)
SET @sql = @sql + '[non_za_id_number], ' + CHAR(13)
SET @sql = @sql + '[number], ' + CHAR(13)
SET @sql = @sql + '[occupation], ' + CHAR(13)
SET @sql = @sql + '[payment_date], ' + CHAR(13)
SET @sql = @sql + '[residential_address_city], ' + CHAR(13)
SET @sql = @sql + '[residential_address_code], ' + CHAR(13)
SET @sql = @sql + '[residential_address_line1], ' + CHAR(13)
SET @sql = @sql + '[residential_address_line2], ' + CHAR(13)
SET @sql = @sql + '[residential_address_province_key], ' + CHAR(13)
SET @sql = @sql + '[residential_address_province_display], ' + CHAR(13)
SET @sql = @sql + '[residential_telephone_number], ' + CHAR(13)
SET @sql = @sql + '[surname], ' + CHAR(13)
SET @sql = @sql + '[system_populated_form_key], ' + CHAR(13)
SET @sql = @sql + '[system_populated_form_display], ' + CHAR(13)
SET @sql = @sql + '[time_generated], ' + CHAR(13)
SET @sql = @sql + '[vehicle_designation_key], ' + CHAR(13)
SET @sql = @sql + '[vehicle_designation_display], ' + CHAR(13)
SET @sql = @sql + '[violation_charges_arr], ' + CHAR(13)
SET @sql = @sql + '[violation_charge_1], ' + CHAR(13)
SET @sql = @sql + '[violation_charge_2], ' + CHAR(13)
SET @sql = @sql + '[violation_charge_3], ' + CHAR(13)
SET @sql = @sql + '[violation_type_key], ' + CHAR(13)
SET @sql = @sql + '[violation_type_display], ' + CHAR(13)
--Select End
SET @sql = @sql + CAST(@DeltaLogKey AS VARCHAR(10)) + ',' + CAST(@AuditKey AS VARCHAR(10)) +  CHAR(13)
SET @sql = @sql + 'FROM OPENJSON(@json, ''$.objects'') '   + CHAR(13)
SET @sql = @sql + 'WITH ( ' + CHAR(13)
--WITH Begin
SET @sql = @sql + '[id] [uniqueidentifier] ''$.id'',' + CHAR(13)
SET @sql = @sql + '[type] [nvarchar](max) ''$.type'',' + CHAR(13)
SET @sql = @sql + '[updated_at] [nvarchar](max) ''$.updated_at'',' + CHAR(13)
SET @sql = @sql + '[display] [nvarchar](max) ''$.display'',' + CHAR(13)
SET @sql = @sql + '[driver_id] [varchar](max) ''$.driver_id'',' + CHAR(13)
SET @sql = @sql + '[event_id] [varchar](max) ''$.event_id'',' + CHAR(13)
SET @sql = @sql + '[magistrates_court_id] [varchar](max) ''$.magistrates_court_id'',' + CHAR(13)
SET @sql = @sql + '[shift_statistic_id] [varchar](max) ''$.shift_statistic_id'',' + CHAR(13)
SET @sql = @sql + '[user_id] [varchar](max) ''$.user_id'',' + CHAR(13)
SET @sql = @sql + '[vehicle_id] [varchar](max) ''$.vehicle_id'',' + CHAR(13)
SET @sql = @sql + '[age] [varchar](max) ''$.age'',' + CHAR(13)
SET @sql = @sql + '[business_address_city] [varchar](max) ''$.business_address_city'',' + CHAR(13)
SET @sql = @sql + '[business_address_code] [varchar](max) ''$.business_address_code'',' + CHAR(13)
SET @sql = @sql + '[business_address_line1] [varchar](max) ''$.business_address_line1'',' + CHAR(13)
SET @sql = @sql + '[business_address_line2] [varchar](max) ''$.business_address_line2'',' + CHAR(13)
SET @sql = @sql + '[business_address_province_key] [varchar](max) ''$.business_address_province.key'',' + CHAR(13)
SET @sql = @sql + '[business_address_province_display] [varchar](max) ''$.business_address_province.display'',' + CHAR(13)
SET @sql = @sql + '[business_telephone_number] [varchar](max) ''$.business_telephone_number'',' + CHAR(13)
SET @sql = @sql + '[cancelled_key] [varchar](max) ''$.cancelled.key'',' + CHAR(13)
SET @sql = @sql + '[cancelled_display] [varchar](max) ''$.cancelled.display'',' + CHAR(13)
SET @sql = @sql + '[cancelled_reason] [varchar](max) ''$.cancelled_reason'',' + CHAR(13)
SET @sql = @sql + '[comment] [varchar](max) ''$.comment'',' + CHAR(13)
SET @sql = @sql + '[court_code] [varchar](max) ''$.court_code'',' + CHAR(13)
SET @sql = @sql + '[court_date] [varchar](max) ''$.court_date'',' + CHAR(13)
SET @sql = @sql + '[court_name] [varchar](max) ''$.court_name'',' + CHAR(13)
SET @sql = @sql + '[court_no] [varchar](max) ''$.court_no'',' + CHAR(13)
SET @sql = @sql + '[drivers_license_code] [varchar](max) ''$.drivers_license_code'',' + CHAR(13)
SET @sql = @sql + '[driver_sex_key] [varchar](max) ''$.driver_sex.key'',' + CHAR(13)
SET @sql = @sql + '[driver_sex_display] [varchar](max) ''$.driver_sex.display'',' + CHAR(13)
SET @sql = @sql + '[email] [varchar](max) ''$.email'',' + CHAR(13)
SET @sql = @sql + '[email_requested_key] [varchar](max) ''$.email_requested.key'',' + CHAR(13)
SET @sql = @sql + '[email_requested_display] [varchar](max) ''$.email_requested.display'',' + CHAR(13)
SET @sql = @sql + '[id_number] [varchar](max) ''$.id_number'',' + CHAR(13)
SET @sql = @sql + '[manual_entry_key] [varchar](max) ''$.manual_entry.key'',' + CHAR(13)
SET @sql = @sql + '[manual_entry_display] [varchar](max) ''$.manual_entry.display'',' + CHAR(13)
SET @sql = @sql + '[name] [varchar](max) ''$.name'',' + CHAR(13)
SET @sql = @sql + '[nationality_key] [varchar](max) ''$.nationality.key'',' + CHAR(13)
SET @sql = @sql + '[nationality_display] [varchar](max) ''$.nationality.display'',' + CHAR(13)
SET @sql = @sql + '[non_za_id_number] [varchar](max) ''$.non_za_id_number'',' + CHAR(13)
SET @sql = @sql + '[number] [varchar](max) ''$.number'',' + CHAR(13)
SET @sql = @sql + '[occupation] [varchar](max) ''$.occupation'',' + CHAR(13)
SET @sql = @sql + '[payment_date] [varchar](max) ''$.payment_date'',' + CHAR(13)
SET @sql = @sql + '[residential_address_city] [varchar](max) ''$.residential_address_city'',' + CHAR(13)
SET @sql = @sql + '[residential_address_code] [varchar](max) ''$.residential_address_code'',' + CHAR(13)
SET @sql = @sql + '[residential_address_line1] [varchar](max) ''$.residential_address_line1'',' + CHAR(13)
SET @sql = @sql + '[residential_address_line2] [varchar](max) ''$.residential_address_line2'',' + CHAR(13)
SET @sql = @sql + '[residential_address_province_key] [varchar](max) ''$.residential_address_province.key'',' + CHAR(13)
SET @sql = @sql + '[residential_address_province_display] [varchar](max) ''$.residential_address_province.display'',' + CHAR(13)
SET @sql = @sql + '[residential_telephone_number] [varchar](max) ''$.residential_telephone_number'',' + CHAR(13)
SET @sql = @sql + '[surname] [varchar](max) ''$.surname'',' + CHAR(13)
SET @sql = @sql + '[system_populated_form_key] [varchar](max) ''$.system_populated_form.key'',' + CHAR(13)
SET @sql = @sql + '[system_populated_form_display] [varchar](max) ''$.system_populated_form.display'',' + CHAR(13)
SET @sql = @sql + '[time_generated] [varchar](max) ''$.time_generated'',' + CHAR(13)
SET @sql = @sql + '[vehicle_designation_key] [varchar](max) ''$.vehicle_designation.key'',' + CHAR(13)
SET @sql = @sql + '[vehicle_designation_display] [varchar](max) ''$.vehicle_designation.display'',' + CHAR(13)
SET @sql = @sql + '[violation_charges_arr] [varchar](max) ''$.violation_charges_arr'',' + CHAR(13)
SET @sql = @sql + '[violation_charge_1] [varchar](max) ''$.violation_charge_1'',' + CHAR(13)
SET @sql = @sql + '[violation_charge_2] [varchar](max) ''$.violation_charge_2'',' + CHAR(13)
SET @sql = @sql + '[violation_charge_3] [varchar](max) ''$.violation_charge_3'',' + CHAR(13)
SET @sql = @sql + '[violation_type_key] [varchar](max) ''$.violation_type.key'',' + CHAR(13)
SET @sql = @sql + '[violation_type_display] [varchar](max) ''$.violation_type.display''' + CHAR(13)
--WITH End
SET @sql = @sql + ')' + CHAR(13)

EXEC(@SQL)

