
CREATE PROCEDURE [itis].[prcExtractoperation]

--------------------------------------------------------------------------------------------------------------------------------------
-- Author				:	Generated from Model
-- Date Created			:	19-08-2019 07:13:46
-- Reason				:	Reads JSON file and inserts data into Stage table (operation)
--------------------------------------------------------------------------------------------------------------------------------------
-- Inputs				:	@FileName, @DeltaLogKey, @AuditKey
-- Ouputs				:	@RowCountStage
-- Test					:	exec itis.prcExtractoperation 'D:\PSA\WCG\changes\WCG-0099 - Replace Actuals\operation.json'
--------------------------------------------------------------------------------------------------------------------------------------
-- Modified By			:	Trevor Howe
-- Modified On			:	14-09-2019
-- Reason				:	Added new fields and changed logic for road_block fields to cater for multiple values instead of single values
--------------------------------------------------------------------------------------------------------------------------------------

@FileName NVARCHAR(MAX),
@DeltaLogKey INT = -1,
@AuditKey INT = -1,
@TruncateFlag INT = 1

AS

IF @TruncateFlag = 1 TRUNCATE TABLE [itis].[operation]

DECLARE @sql AS NVARCHAR(MAX)

SET @sql = 'DECLARE @json NVARCHAR(MAX) ' + CHAR(13)
SET @sql = @sql + 'SELECT @json = BulkColumn FROM OPENROWSET (BULK ''' + @FileName + ''', SINGLE_CLOB) as j' + CHAR(13)
SET @sql = @sql + 'INSERT INTO [itis].[operation] (' + CHAR(13)
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
--Insert Begin
SET @sql = @sql + '[asod_road_section_id], ' + CHAR(13)
SET @sql = @sql + '[briefing_done_by_id], ' + CHAR(13)
SET @sql = @sql + '[debriefing_done_by_id], ' + CHAR(13)
SET @sql = @sql + '[location_id], ' + CHAR(13)
SET @sql = @sql + '[operational_officer_id], ' + CHAR(13)
SET @sql = @sql + '[planner_id], ' + CHAR(13)
SET @sql = @sql + '[traffic_centre_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_used_id], ' + CHAR(13)
SET @sql = @sql + '[actual_operation_start_time], ' + CHAR(13)
SET @sql = @sql + '[actual_operation_stop_time], ' + CHAR(13)
SET @sql = @sql + '[approval_comment], ' + CHAR(13)
SET @sql = @sql + '[approval_date], ' + CHAR(13)
SET @sql = @sql + '[authorization_comment], ' + CHAR(13)
SET @sql = @sql + '[authorization_date], ' + CHAR(13)
SET @sql = @sql + '[close_local_ob_number], ' + CHAR(13)
SET @sql = @sql + '[compeltion_report], ' + CHAR(13)
SET @sql = @sql + '[compeltion_report_photo], ' + CHAR(13)
SET @sql = @sql + '[completion_comment], ' + CHAR(13)
SET @sql = @sql + '[date_created], ' + CHAR(13)
SET @sql = @sql + '[description], ' + CHAR(13)
SET @sql = @sql + '[dsp_operation_key], ' + CHAR(13)
SET @sql = @sql + '[dsp_operation_display], ' + CHAR(13)
SET @sql = @sql + '[equipment_serial_number], ' + CHAR(13)
SET @sql = @sql + '[general_type_key], ' + CHAR(13)
SET @sql = @sql + '[general_type_display], ' + CHAR(13)
SET @sql = @sql + '[has_non_object_location], ' + CHAR(13)
SET @sql = @sql + '[last_updated], ' + CHAR(13)
SET @sql = @sql + '[open_local_ob_number], ' + CHAR(13)
SET @sql = @sql + '[operation_document], ' + CHAR(13)
SET @sql = @sql + '[other_location], ' + CHAR(13)
SET @sql = @sql + '[reason_for_cancelation], ' + CHAR(13)
SET @sql = @sql + '[roadblock_type_key], ' + CHAR(13)
SET @sql = @sql + '[roadblock_type_display], ' + CHAR(13)
SET @sql = @sql + '[rtqs_key], ' + CHAR(13)
SET @sql = @sql + '[rtqs_display], ' + CHAR(13)
SET @sql = @sql + '[speed_operation_type_key], ' + CHAR(13)
SET @sql = @sql + '[speed_operation_type_display], ' + CHAR(13)
SET @sql = @sql + '[start_time], ' + CHAR(13)
SET @sql = @sql + '[status_key], ' + CHAR(13)
SET @sql = @sql + '[status_display], ' + CHAR(13)
SET @sql = @sql + '[stop_time], ' + CHAR(13)
SET @sql = @sql + '[weigh_operation_type_key], ' + CHAR(13)
SET @sql = @sql + '[weigh_operation_type_display], ' + CHAR(13)
SET @sql = @sql + '[deltalogkey],' + CHAR(13)
SET @sql = @sql + '[auditkey]' + CHAR(13)
--Insert End
SET @sql = @sql + ')' + CHAR(13)
SET @sql = @sql + 'SELECT ' 
--Select Begin
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
SET @sql = @sql + '[asod_road_section_id], ' + CHAR(13)
SET @sql = @sql + '[briefing_done_by_id], ' + CHAR(13)
SET @sql = @sql + '[debriefing_done_by_id], ' + CHAR(13)
SET @sql = @sql + '[location_id], ' + CHAR(13)
SET @sql = @sql + '[operational_officer_id], ' + CHAR(13)
SET @sql = @sql + '[planner_id], ' + CHAR(13)
SET @sql = @sql + '[traffic_centre_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_used_id], ' + CHAR(13)
SET @sql = @sql + '[actual_operation_start_time], ' + CHAR(13)
SET @sql = @sql + '[actual_operation_stop_time], ' + CHAR(13)
SET @sql = @sql + '[approval_comment], ' + CHAR(13)
SET @sql = @sql + '[approval_date], ' + CHAR(13)
SET @sql = @sql + '[authorization_comment], ' + CHAR(13)
SET @sql = @sql + '[authorization_date], ' + CHAR(13)
SET @sql = @sql + '[close_local_ob_number], ' + CHAR(13)
SET @sql = @sql + '[compeltion_report], ' + CHAR(13)
SET @sql = @sql + '[compeltion_report_photo], ' + CHAR(13)
SET @sql = @sql + '[completion_comment], ' + CHAR(13)
SET @sql = @sql + '[date_created], ' + CHAR(13)
SET @sql = @sql + '[description], ' + CHAR(13)
SET @sql = @sql + '[dsp_operation_key], ' + CHAR(13)
SET @sql = @sql + '[dsp_operation_display], ' + CHAR(13)
SET @sql = @sql + '[equipment_serial_number], ' + CHAR(13)
SET @sql = @sql + '[general_type_key], ' + CHAR(13)
SET @sql = @sql + '[general_type_display], ' + CHAR(13)
SET @sql = @sql + '[has_non_object_location], ' + CHAR(13)
SET @sql = @sql + '[last_updated], ' + CHAR(13)
SET @sql = @sql + '[open_local_ob_number], ' + CHAR(13)
SET @sql = @sql + '[operation_document], ' + CHAR(13)
SET @sql = @sql + '[other_location], ' + CHAR(13)
SET @sql = @sql + '[reason_for_cancelation], ' + CHAR(13)
SET @sql = @sql + 'NULLIF(CONCAT( ' + CHAR(13)SET @sql = @sql + '	+ [roadblock_type_key0], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key1], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key2], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key3], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key4], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key5], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key6], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key7], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key8], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_key9] ' + CHAR(13)SET @sql = @sql + '),'''') as roadblock_type_key, ' + CHAR(13)SET @sql = @sql + 'NULLIF(CONCAT( ' + CHAR(13)SET @sql = @sql + '	+ [roadblock_type_display0], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display1], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display2], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display3], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display4], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display5], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display6], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display7], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display8], ' + CHAR(13)SET @sql = @sql + '	'','' + [roadblock_type_display9]	 ' + CHAR(13)SET @sql = @sql + '),'''') as roadblock_type_display, ' + CHAR(13)
SET @sql = @sql + '[rtqs_key], ' + CHAR(13)
SET @sql = @sql + '[rtqs_display], ' + CHAR(13)
SET @sql = @sql + '[speed_operation_type_key], ' + CHAR(13)
SET @sql = @sql + '[speed_operation_type_display], ' + CHAR(13)
SET @sql = @sql + '[start_time], ' + CHAR(13)
SET @sql = @sql + '[status_key], ' + CHAR(13)
SET @sql = @sql + '[status_display], ' + CHAR(13)
SET @sql = @sql + '[stop_time], ' + CHAR(13)
SET @sql = @sql + '[weigh_operation_type_key], ' + CHAR(13)
SET @sql = @sql + '[weigh_operation_type_display], ' + CHAR(13)
--Select End
SET @sql = @sql + CAST(@DeltaLogKey AS VARCHAR(10)) + ',' + CAST(@AuditKey AS VARCHAR(10)) +  CHAR(13)
SET @sql = @sql + 'FROM OPENJSON(@json, ''$.objects'') '   + CHAR(13)
SET @sql = @sql + 'WITH ( ' + CHAR(13)
--WITH Begin
SET @sql = @sql + '[id] [uniqueidentifier] ''$.id'',' + CHAR(13)
SET @sql = @sql + '[type] [nvarchar](max) ''$.type'',' + CHAR(13)
SET @sql = @sql + '[updated_at] [nvarchar](max) ''$.updated_at'',' + CHAR(13)
SET @sql = @sql + '[display] [nvarchar](max) ''$.display'',' + CHAR(13)
SET @sql = @sql + '[asod_road_section_id] [varchar](max) ''$.asod_road_section_id'',' + CHAR(13)
SET @sql = @sql + '[briefing_done_by_id] [varchar](max) ''$.briefing_done_by_id'',' + CHAR(13)
SET @sql = @sql + '[debriefing_done_by_id] [varchar](max) ''$.debriefing_done_by_id'',' + CHAR(13)
SET @sql = @sql + '[location_id] [varchar](max) ''$.location_id'',' + CHAR(13)
SET @sql = @sql + '[operational_officer_id] [varchar](max) ''$.operational_officer_id'',' + CHAR(13)
SET @sql = @sql + '[planner_id] [varchar](max) ''$.planner_id'',' + CHAR(13)
SET @sql = @sql + '[traffic_centre_id] [varchar](max) ''$.traffic_centre_id'',' + CHAR(13)
SET @sql = @sql + '[vehicle_used_id] [varchar](max) ''$.vehicle_used_id'',' + CHAR(13)
SET @sql = @sql + '[actual_operation_start_time] [varchar](max) ''$.actual_operation_start_time'',' + CHAR(13)
SET @sql = @sql + '[actual_operation_stop_time] [varchar](max) ''$.actual_operation_stop_time'',' + CHAR(13)
SET @sql = @sql + '[approval_comment] [varchar](max) ''$.approval_comment'',' + CHAR(13)
SET @sql = @sql + '[approval_date] [varchar](max) ''$.approval_date'',' + CHAR(13)
SET @sql = @sql + '[authorization_comment] [varchar](max) ''$.authorization_comment'',' + CHAR(13)
SET @sql = @sql + '[authorization_date] [varchar](max) ''$.authorization_date'',' + CHAR(13)
SET @sql = @sql + '[close_local_ob_number] [varchar](max) ''$.close_local_ob_number'',' + CHAR(13)
SET @sql = @sql + '[compeltion_report] [varchar](max) ''$.compeltion_report'',' + CHAR(13)
SET @sql = @sql + '[compeltion_report_photo] [varchar](max) ''$.compeltion_report_photo'',' + CHAR(13)
SET @sql = @sql + '[completion_comment] [varchar](max) ''$.completion_comment'',' + CHAR(13)
SET @sql = @sql + '[date_created] [varchar](max) ''$.date_created'',' + CHAR(13)
SET @sql = @sql + '[description] [varchar](max) ''$.description'',' + CHAR(13)
SET @sql = @sql + '[dsp_operation_key] [varchar](max) ''$.dsp_operation.key'',' + CHAR(13)
SET @sql = @sql + '[dsp_operation_display] [varchar](max) ''$.dsp_operation.display'',' + CHAR(13)
SET @sql = @sql + '[equipment_serial_number] [varchar](max) ''$.equipment_serial_number'',' + CHAR(13)
SET @sql = @sql + '[general_type_key] [varchar](max) ''$.general_type.key'',' + CHAR(13)
SET @sql = @sql + '[general_type_display] [varchar](max) ''$.general_type.display'',' + CHAR(13)
SET @sql = @sql + '[has_non_object_location] [varchar](max) ''$.has_non_object_location'',' + CHAR(13)
SET @sql = @sql + '[last_updated] [varchar](max) ''$.last_updated'',' + CHAR(13)
SET @sql = @sql + '[open_local_ob_number] [varchar](max) ''$.open_local_ob_number'',' + CHAR(13)
SET @sql = @sql + '[operation_document] [varchar](max) ''$.operation_document'',' + CHAR(13)
SET @sql = @sql + '[other_location] [varchar](max) ''$.other_location'',' + CHAR(13)
SET @sql = @sql + '[reason_for_cancelation] [varchar](max) ''$.reason_for_cancelation'',' + CHAR(13)
SET @sql = @sql + '[roadblock_type_key0] [nvarchar](max) ''$.roadblock_type[0].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key1] [nvarchar](max) ''$.roadblock_type[1].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key2] [nvarchar](max) ''$.roadblock_type[2].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key3] [nvarchar](max) ''$.roadblock_type[3].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key4] [nvarchar](max) ''$.roadblock_type[4].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key5] [nvarchar](max) ''$.roadblock_type[5].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key6] [nvarchar](max) ''$.roadblock_type[6].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key7] [nvarchar](max) ''$.roadblock_type[7].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key8] [nvarchar](max) ''$.roadblock_type[8].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_key9] [nvarchar](max) ''$.roadblock_type[9].key'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display0] [nvarchar](max) ''$.roadblock_type[0].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display1] [nvarchar](max) ''$.roadblock_type[1].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display2] [nvarchar](max) ''$.roadblock_type[2].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display3] [nvarchar](max) ''$.roadblock_type[3].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display4] [nvarchar](max) ''$.roadblock_type[4].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display5] [nvarchar](max) ''$.roadblock_type[5].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display6] [nvarchar](max) ''$.roadblock_type[6].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display7] [nvarchar](max) ''$.roadblock_type[7].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display8] [nvarchar](max) ''$.roadblock_type[8].display'',' + CHAR(13)SET @sql = @sql + '[roadblock_type_display9] [nvarchar](max) ''$.roadblock_type[9].display'',' + CHAR(13)
SET @sql = @sql + '[rtqs_key] [varchar](max) ''$.rtqs.key'',' + CHAR(13)
SET @sql = @sql + '[rtqs_display] [varchar](max) ''$.rtqs.display'',' + CHAR(13)
SET @sql = @sql + '[speed_operation_type_key] [varchar](max) ''$.speed_operation_type.key'',' + CHAR(13)
SET @sql = @sql + '[speed_operation_type_display] [varchar](max) ''$.speed_operation_type.display'',' + CHAR(13)
SET @sql = @sql + '[start_time] [varchar](max) ''$.start_time'',' + CHAR(13)
SET @sql = @sql + '[status_key] [varchar](max) ''$.status.key'',' + CHAR(13)
SET @sql = @sql + '[status_display] [varchar](max) ''$.status.display'',' + CHAR(13)
SET @sql = @sql + '[stop_time] [varchar](max) ''$.stop_time'',' + CHAR(13)
SET @sql = @sql + '[weigh_operation_type_key] [varchar](max) ''$.weigh_operation_type.key'',' + CHAR(13)
SET @sql = @sql + '[weigh_operation_type_display] [varchar](max) ''$.weigh_operation_type.display''' + CHAR(13)
--WITH End
SET @sql = @sql + ')' + CHAR(13)

EXEC(@SQL)

