
CREATE PROCEDURE [itis].[prcExtractalert]

--------------------------------------------------------------------------------------------------------------------------------------
-- Author				:	Generated from Model
-- Date Created			:	07-04-2018 01:33:30
-- Reason				:	Reads JSON file and inserts data into Stage table (alert)
--------------------------------------------------------------------------------------------------------------------------------------
-- Inputs				:	@FileName, @DeltaLogKey, @AuditKey
-- Ouputs				:	@RowCountStage
-- Test					:	exec itis.prcExtractalert 'D:\PSA\TCE2\sample\alert.json'
--------------------------------------------------------------------------------------------------------------------------------------
-- Modified By	:
-- Modified On	:
-- Reason				:
--------------------------------------------------------------------------------------------------------------------------------------

@FileName NVARCHAR(MAX),
@DeltaLogKey INT = -1,
@AuditKey INT = -1,
@TruncateFlag INT = 1

AS

IF @TruncateFlag = 1 TRUNCATE TABLE [itis].[alert]

DECLARE @sql AS NVARCHAR(MAX)

SET @sql = 'DECLARE @json NVARCHAR(MAX) ' + CHAR(13)
SET @sql = @sql + 'SELECT @json = BulkColumn FROM OPENROWSET (BULK ''' + @FileName + ''', SINGLE_CLOB) as j' + CHAR(13)
SET @sql = @sql + 'INSERT INTO [itis].[alert] (' + CHAR(13)
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
--Insert Begin
SET @sql = @sql + '[asod_road_section_id], ' + CHAR(13)
SET @sql = @sql + '[assigned_user_id], ' + CHAR(13)
SET @sql = @sql + '[camera_site_id], ' + CHAR(13)
SET @sql = @sql + '[control_room_selector_id], ' + CHAR(13)
SET @sql = @sql + '[control_room_user_id], ' + CHAR(13)
SET @sql = @sql + '[event_id], ' + CHAR(13)
SET @sql = @sql + '[operational_area_id], ' + CHAR(13)
SET @sql = @sql + '[traffic_centre_id], ' + CHAR(13)
SET @sql = @sql + '[alert_id], ' + CHAR(13)
SET @sql = @sql + '[alert_status], ' + CHAR(13)
SET @sql = @sql + '[alert_status_description], ' + CHAR(13)
SET @sql = @sql + '[alert_sub_type], ' + CHAR(13)
SET @sql = @sql + '[alert_sub_type_code], ' + CHAR(13)
SET @sql = @sql + '[alert_type], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_key], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_display], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_short_key], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_short_display], ' + CHAR(13)
SET @sql = @sql + '[average_kmh], ' + CHAR(13)
SET @sql = @sql + '[control_room_assigned_key], ' + CHAR(13)
SET @sql = @sql + '[control_room_assigned_display], ' + CHAR(13)
SET @sql = @sql + '[corrected_vrm], ' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_key], ' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_display], ' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_other], ' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_key], ' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_display], ' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_other], ' + CHAR(13)
SET @sql = @sql + '[device_id], ' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_key], ' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_display], ' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_other], ' + CHAR(13)
SET @sql = @sql + '[images_cleared_key], ' + CHAR(13)
SET @sql = @sql + '[images_cleared_display], ' + CHAR(13)
SET @sql = @sql + '[journey_status_key], ' + CHAR(13)
SET @sql = @sql + '[journey_status_display], ' + CHAR(13)
SET @sql = @sql + '[lane], ' + CHAR(13)
SET @sql = @sql + '[lane_direction], ' + CHAR(13)
SET @sql = @sql + '[latittude], ' + CHAR(13)
SET @sql = @sql + '[license_number], ' + CHAR(13)
SET @sql = @sql + '[location_name], ' + CHAR(13)
SET @sql = @sql + '[location_name_short], ' + CHAR(13)
SET @sql = @sql + '[longitude], ' + CHAR(13)
SET @sql = @sql + '[previous_license_number], ' + CHAR(13)
SET @sql = @sql + '[primary_ir_image], ' + CHAR(13)
SET @sql = @sql + '[primary_overview_image], ' + CHAR(13)
SET @sql = @sql + '[primary_sighting_id], ' + CHAR(13)
SET @sql = @sql + '[primary_sighting_site_name], ' + CHAR(13)
SET @sql = @sql + '[primary_timestamp], ' + CHAR(13)
SET @sql = @sql + '[primary_vrm], ' + CHAR(13)
SET @sql = @sql + '[processed_and_routed_key], ' + CHAR(13)
SET @sql = @sql + '[processed_and_routed_display], ' + CHAR(13)
SET @sql = @sql + '[reject_reason_key], ' + CHAR(13)
SET @sql = @sql + '[reject_reason_display], ' + CHAR(13)
SET @sql = @sql + '[reject_reason_other], ' + CHAR(13)
SET @sql = @sql + '[road_section], ' + CHAR(13)
SET @sql = @sql + '[secondary_ir_image], ' + CHAR(13)
SET @sql = @sql + '[secondary_overview_image], ' + CHAR(13)
SET @sql = @sql + '[secondary_sighting_id], ' + CHAR(13)
SET @sql = @sql + '[secondary_sighting_site_name], ' + CHAR(13)
SET @sql = @sql + '[secondary_timestamp], ' + CHAR(13)
SET @sql = @sql + '[secondary_vrm], ' + CHAR(13)
SET @sql = @sql + '[sighting_id], ' + CHAR(13)
SET @sql = @sql + '[source_system_id], ' + CHAR(13)
SET @sql = @sql + '[speed_class], ' + CHAR(13)
SET @sql = @sql + '[speed_class_code], ' + CHAR(13)
SET @sql = @sql + '[speed_limit], ' + CHAR(13)
SET @sql = @sql + '[timestamp], ' + CHAR(13)
SET @sql = @sql + '[time_string], ' + CHAR(13)
SET @sql = @sql + '[traffic_centre_name], ' + CHAR(13)
SET @sql = @sql + '[user_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_category], ' + CHAR(13)
SET @sql = @sql + '[vehicle_category_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_direction], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_model], ' + CHAR(13)
SET @sql = @sql + '[vehicle_model_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_usage], ' + CHAR(13)
SET @sql = @sql + '[vehicle_usage_code], ' + CHAR(13)
SET @sql = @sql + '[vrm], ' + CHAR(13)
SET @sql = @sql + '[deltalogkey],' + CHAR(13)
SET @sql = @sql + '[AuditKey]' + CHAR(13)
--Insert End
SET @sql = @sql + ')' + CHAR(13)
SET @sql = @sql + 'SELECT ' 
--Select Begin
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
SET @sql = @sql + '[asod_road_section_id], ' + CHAR(13)
SET @sql = @sql + '[assigned_user_id], ' + CHAR(13)
SET @sql = @sql + '[camera_site_id], ' + CHAR(13)
SET @sql = @sql + '[control_room_selector_id], ' + CHAR(13)
SET @sql = @sql + '[control_room_user_id], ' + CHAR(13)
SET @sql = @sql + '[event_id], ' + CHAR(13)
SET @sql = @sql + '[operational_area_id], ' + CHAR(13)
SET @sql = @sql + '[traffic_centre_id], ' + CHAR(13)
SET @sql = @sql + '[alert_id], ' + CHAR(13)
SET @sql = @sql + '[alert_status], ' + CHAR(13)
SET @sql = @sql + '[alert_status_description], ' + CHAR(13)
SET @sql = @sql + '[alert_sub_type], ' + CHAR(13)
SET @sql = @sql + '[alert_sub_type_code], ' + CHAR(13)
SET @sql = @sql + '[alert_type], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_key], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_display], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_short_key], ' + CHAR(13)
SET @sql = @sql + '[alert_type_id_short_display], ' + CHAR(13)
SET @sql = @sql + '[average_kmh], ' + CHAR(13)
SET @sql = @sql + '[control_room_assigned_key], ' + CHAR(13)
SET @sql = @sql + '[control_room_assigned_display], ' + CHAR(13)
SET @sql = @sql + '[corrected_vrm], ' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_key], ' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_display], ' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_other], ' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_key], ' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_display], ' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_other], ' + CHAR(13)
SET @sql = @sql + '[device_id], ' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_key], ' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_display], ' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_other], ' + CHAR(13)
SET @sql = @sql + '[images_cleared_key], ' + CHAR(13)
SET @sql = @sql + '[images_cleared_display], ' + CHAR(13)
SET @sql = @sql + '[journey_status_key], ' + CHAR(13)
SET @sql = @sql + '[journey_status_display], ' + CHAR(13)
SET @sql = @sql + '[lane], ' + CHAR(13)
SET @sql = @sql + '[lane_direction], ' + CHAR(13)
SET @sql = @sql + '[latittude], ' + CHAR(13)
SET @sql = @sql + '[license_number], ' + CHAR(13)
SET @sql = @sql + '[location_name], ' + CHAR(13)
SET @sql = @sql + '[location_name_short], ' + CHAR(13)
SET @sql = @sql + '[longitude], ' + CHAR(13)
SET @sql = @sql + '[previous_license_number], ' + CHAR(13)
SET @sql = @sql + '[primary_ir_image], ' + CHAR(13)
SET @sql = @sql + '[primary_overview_image], ' + CHAR(13)
SET @sql = @sql + '[primary_sighting_id], ' + CHAR(13)
SET @sql = @sql + '[primary_sighting_site_name], ' + CHAR(13)
SET @sql = @sql + '[primary_timestamp], ' + CHAR(13)
SET @sql = @sql + '[primary_vrm], ' + CHAR(13)
SET @sql = @sql + '[processed_and_routed_key], ' + CHAR(13)
SET @sql = @sql + '[processed_and_routed_display], ' + CHAR(13)
SET @sql = @sql + '[reject_reason_key], ' + CHAR(13)
SET @sql = @sql + '[reject_reason_display], ' + CHAR(13)
SET @sql = @sql + '[reject_reason_other], ' + CHAR(13)
SET @sql = @sql + '[road_section], ' + CHAR(13)
SET @sql = @sql + '[secondary_ir_image], ' + CHAR(13)
SET @sql = @sql + '[secondary_overview_image], ' + CHAR(13)
SET @sql = @sql + '[secondary_sighting_id], ' + CHAR(13)
SET @sql = @sql + '[secondary_sighting_site_name], ' + CHAR(13)
SET @sql = @sql + '[secondary_timestamp], ' + CHAR(13)
SET @sql = @sql + '[secondary_vrm], ' + CHAR(13)
SET @sql = @sql + '[sighting_id], ' + CHAR(13)
SET @sql = @sql + '[source_system_id], ' + CHAR(13)
SET @sql = @sql + '[speed_class], ' + CHAR(13)
SET @sql = @sql + '[speed_class_code], ' + CHAR(13)
SET @sql = @sql + '[speed_limit], ' + CHAR(13)
SET @sql = @sql + '[timestamp], ' + CHAR(13)
SET @sql = @sql + '[time_string], ' + CHAR(13)
SET @sql = @sql + '[traffic_centre_name], ' + CHAR(13)
SET @sql = @sql + '[user_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_category], ' + CHAR(13)
SET @sql = @sql + '[vehicle_category_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_direction], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_model], ' + CHAR(13)
SET @sql = @sql + '[vehicle_model_code], ' + CHAR(13)
SET @sql = @sql + '[vehicle_usage], ' + CHAR(13)
SET @sql = @sql + '[vehicle_usage_code], ' + CHAR(13)
SET @sql = @sql + '[vrm], ' + CHAR(13)
--Select End
SET @sql = @sql + CAST(@DeltaLogKey AS VARCHAR(10)) + ',' + CAST(@AuditKey AS VARCHAR(10)) +  CHAR(13)
SET @sql = @sql + 'FROM OPENJSON(@json, ''$.objects'') '   + CHAR(13)
SET @sql = @sql + 'WITH ( ' + CHAR(13)
--WITH Begin
SET @sql = @sql + '[id] [uniqueidentifier] ''$.id'',' + CHAR(13)
SET @sql = @sql + '[type] [nvarchar](max) ''$.type'',' + CHAR(13)
SET @sql = @sql + '[updated_at] [nvarchar](max) ''$.updated_at'',' + CHAR(13)
SET @sql = @sql + '[display] [nvarchar](max) ''$.display'',' + CHAR(13)
SET @sql = @sql + '[asod_road_section_id] [varchar](max) ''$.asod_road_section_id'',' + CHAR(13)
SET @sql = @sql + '[assigned_user_id] [varchar](max) ''$.assigned_user_id'',' + CHAR(13)
SET @sql = @sql + '[camera_site_id] [varchar](max) ''$.camera_site_id'',' + CHAR(13)
SET @sql = @sql + '[control_room_selector_id] [varchar](max) ''$.control_room_selector_id'',' + CHAR(13)
SET @sql = @sql + '[control_room_user_id] [varchar](max) ''$.control_room_user_id'',' + CHAR(13)
SET @sql = @sql + '[event_id] [varchar](max) ''$.event_id'',' + CHAR(13)
SET @sql = @sql + '[operational_area_id] [varchar](max) ''$.operational_area_id'',' + CHAR(13)
SET @sql = @sql + '[traffic_centre_id] [varchar](max) ''$.traffic_centre_id'',' + CHAR(13)
SET @sql = @sql + '[alert_id] [varchar](max) ''$.alert_id'',' + CHAR(13)
SET @sql = @sql + '[alert_status] [varchar](max) ''$.alert_status'',' + CHAR(13)
SET @sql = @sql + '[alert_status_description] [varchar](max) ''$.alert_status_description'',' + CHAR(13)
SET @sql = @sql + '[alert_sub_type] [varchar](max) ''$.alert_sub_type'',' + CHAR(13)
SET @sql = @sql + '[alert_sub_type_code] [varchar](max) ''$.alert_sub_type_code'',' + CHAR(13)
SET @sql = @sql + '[alert_type] [varchar](max) ''$.alert_type'',' + CHAR(13)
SET @sql = @sql + '[alert_type_id_key] [varchar](max) ''$.alert_type_id.key'',' + CHAR(13)
SET @sql = @sql + '[alert_type_id_display] [varchar](max) ''$.alert_type_id.display'',' + CHAR(13)
SET @sql = @sql + '[alert_type_id_short_key] [varchar](max) ''$.alert_type_id_short.key'',' + CHAR(13)
SET @sql = @sql + '[alert_type_id_short_display] [varchar](max) ''$.alert_type_id_short.display'',' + CHAR(13)
SET @sql = @sql + '[average_kmh] [varchar](max) ''$.average_kmh'',' + CHAR(13)
SET @sql = @sql + '[control_room_assigned_key] [varchar](max) ''$.control_room_assigned.key'',' + CHAR(13)
SET @sql = @sql + '[control_room_assigned_display] [varchar](max) ''$.control_room_assigned.display'',' + CHAR(13)
SET @sql = @sql + '[corrected_vrm] [varchar](max) ''$.corrected_vrm'',' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_key] [varchar](max) ''$.correction_primary_reason.key'',' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_display] [varchar](max) ''$.correction_primary_reason.display'',' + CHAR(13)
SET @sql = @sql + '[correction_primary_reason_other] [varchar](max) ''$.correction_primary_reason_other'',' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_key] [varchar](max) ''$.correction_secondary_reason.key'',' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_display] [varchar](max) ''$.correction_secondary_reason.display'',' + CHAR(13)
SET @sql = @sql + '[correction_secondary_reason_other] [varchar](max) ''$.correction_secondary_reason_other'',' + CHAR(13)
SET @sql = @sql + '[device_id] [varchar](max) ''$.device_id'',' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_key] [varchar](max) ''$.dismiss_reason.key'',' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_display] [varchar](max) ''$.dismiss_reason.display'',' + CHAR(13)
SET @sql = @sql + '[dismiss_reason_other] [varchar](max) ''$.dismiss_reason_other'',' + CHAR(13)
SET @sql = @sql + '[images_cleared_key] [varchar](max) ''$.images_cleared.key'',' + CHAR(13)
SET @sql = @sql + '[images_cleared_display] [varchar](max) ''$.images_cleared.display'',' + CHAR(13)
SET @sql = @sql + '[journey_status_key] [varchar](max) ''$.journey_status.key'',' + CHAR(13)
SET @sql = @sql + '[journey_status_display] [varchar](max) ''$.journey_status.display'',' + CHAR(13)
SET @sql = @sql + '[lane] [varchar](max) ''$.lane'',' + CHAR(13)
SET @sql = @sql + '[lane_direction] [varchar](max) ''$.lane_direction'',' + CHAR(13)
SET @sql = @sql + '[latittude] [varchar](max) ''$.latittude'',' + CHAR(13)
SET @sql = @sql + '[license_number] [varchar](max) ''$.license_number'',' + CHAR(13)
SET @sql = @sql + '[location_name] [varchar](max) ''$.location_name'',' + CHAR(13)
SET @sql = @sql + '[location_name_short] [varchar](max) ''$.location_name_short'',' + CHAR(13)
SET @sql = @sql + '[longitude] [varchar](max) ''$.longitude'',' + CHAR(13)
SET @sql = @sql + '[previous_license_number] [varchar](max) ''$.previous_license_number'',' + CHAR(13)
SET @sql = @sql + '[primary_ir_image] [varchar](max) ''$.primary_ir_image'',' + CHAR(13)
SET @sql = @sql + '[primary_overview_image] [varchar](max) ''$.primary_overview_image'',' + CHAR(13)
SET @sql = @sql + '[primary_sighting_id] [varchar](max) ''$.primary_sighting_id'',' + CHAR(13)
SET @sql = @sql + '[primary_sighting_site_name] [varchar](max) ''$.primary_sighting_site_name'',' + CHAR(13)
SET @sql = @sql + '[primary_timestamp] [varchar](max) ''$.primary_timestamp'',' + CHAR(13)
SET @sql = @sql + '[primary_vrm] [varchar](max) ''$.primary_vrm'',' + CHAR(13)
SET @sql = @sql + '[processed_and_routed_key] [varchar](max) ''$.processed_and_routed.key'',' + CHAR(13)
SET @sql = @sql + '[processed_and_routed_display] [varchar](max) ''$.processed_and_routed.display'',' + CHAR(13)
SET @sql = @sql + '[reject_reason_key] [varchar](max) ''$.reject_reason.key'',' + CHAR(13)
SET @sql = @sql + '[reject_reason_display] [varchar](max) ''$.reject_reason.display'',' + CHAR(13)
SET @sql = @sql + '[reject_reason_other] [varchar](max) ''$.reject_reason_other'',' + CHAR(13)
SET @sql = @sql + '[road_section] [varchar](max) ''$.road_section'',' + CHAR(13)
SET @sql = @sql + '[secondary_ir_image] [varchar](max) ''$.secondary_ir_image'',' + CHAR(13)
SET @sql = @sql + '[secondary_overview_image] [varchar](max) ''$.secondary_overview_image'',' + CHAR(13)
SET @sql = @sql + '[secondary_sighting_id] [varchar](max) ''$.secondary_sighting_id'',' + CHAR(13)
SET @sql = @sql + '[secondary_sighting_site_name] [varchar](max) ''$.secondary_sighting_site_name'',' + CHAR(13)
SET @sql = @sql + '[secondary_timestamp] [varchar](max) ''$.secondary_timestamp'',' + CHAR(13)
SET @sql = @sql + '[secondary_vrm] [varchar](max) ''$.secondary_vrm'',' + CHAR(13)
SET @sql = @sql + '[sighting_id] [varchar](max) ''$.sighting_id'',' + CHAR(13)
SET @sql = @sql + '[source_system_id] [varchar](max) ''$.source_system_id'',' + CHAR(13)
SET @sql = @sql + '[speed_class] [varchar](max) ''$.speed_class'',' + CHAR(13)
SET @sql = @sql + '[speed_class_code] [varchar](max) ''$.speed_class_code'',' + CHAR(13)
SET @sql = @sql + '[speed_limit] [varchar](max) ''$.speed_limit'',' + CHAR(13)
SET @sql = @sql + '[timestamp] [varchar](max) ''$.timestamp'',' + CHAR(13)
SET @sql = @sql + '[time_string] [varchar](max) ''$.time_string'',' + CHAR(13)
SET @sql = @sql + '[traffic_centre_name] [varchar](max) ''$.traffic_centre_name'',' + CHAR(13)
SET @sql = @sql + '[user_id] [varchar](max) ''$.user_id'',' + CHAR(13)
SET @sql = @sql + '[vehicle_category] [varchar](max) ''$.vehicle_category'',' + CHAR(13)
SET @sql = @sql + '[vehicle_category_code] [varchar](max) ''$.vehicle_category_code'',' + CHAR(13)
SET @sql = @sql + '[vehicle_colour] [varchar](max) ''$.vehicle_colour'',' + CHAR(13)
SET @sql = @sql + '[vehicle_colour_code] [varchar](max) ''$.vehicle_colour_code'',' + CHAR(13)
SET @sql = @sql + '[vehicle_direction] [varchar](max) ''$.vehicle_direction'',' + CHAR(13)
SET @sql = @sql + '[vehicle_make] [varchar](max) ''$.vehicle_make'',' + CHAR(13)
SET @sql = @sql + '[vehicle_make_code] [varchar](max) ''$.vehicle_make_code'',' + CHAR(13)
SET @sql = @sql + '[vehicle_model] [varchar](max) ''$.vehicle_model'',' + CHAR(13)
SET @sql = @sql + '[vehicle_model_code] [varchar](max) ''$.vehicle_model_code'',' + CHAR(13)
SET @sql = @sql + '[vehicle_usage] [varchar](max) ''$.vehicle_usage'',' + CHAR(13)
SET @sql = @sql + '[vehicle_usage_code] [varchar](max) ''$.vehicle_usage_code'',' + CHAR(13)
SET @sql = @sql + '[vrm] [varchar](max) ''$.vrm''' + CHAR(13)
--WITH End
SET @sql = @sql + ')' + CHAR(13)

EXEC(@SQL)

