
CREATE PROCEDURE [pnd].[prcExtractimpound_instruction]

--------------------------------------------------------------------------------------------------------------------------------------
-- Author				:	Generated from Model
-- Date Created			:	03-02-2019 11:53:08
-- Reason				:	Reads JSON file and inserts data into Stage table (impound_instruction)
--------------------------------------------------------------------------------------------------------------------------------------
-- Inputs				:	@FileName, @DeltaLogKey, @AuditKey
-- Ouputs				:	@RowCountStage
-- Test					:	exec pnd.prcExtractimpound_instruction 'D:\PSA\WCG\changes\WCG-0067 - Impound\impound\impound_instruction.json'
--------------------------------------------------------------------------------------------------------------------------------------
-- Modified By	:
-- Modified On	:
-- Reason				:
--------------------------------------------------------------------------------------------------------------------------------------

@FileName NVARCHAR(MAX),
@DeltaLogKey INT = -1,
@AuditKey INT = -1,
@TruncateFlag INT = 1

AS

IF @TruncateFlag = 1 TRUNCATE TABLE [pnd].[impound_instruction]

DECLARE @sql AS NVARCHAR(MAX)

SET @sql = 'DECLARE @json NVARCHAR(MAX) ' + CHAR(13)
SET @sql = @sql + 'SELECT @json = BulkColumn FROM OPENROWSET (BULK ''' + @FileName + ''', SINGLE_CLOB) as j' + CHAR(13)
SET @sql = @sql + 'INSERT INTO [pnd].[impound_instruction] (' + CHAR(13)
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
--Insert Begin
SET @sql = @sql + '[impound_id], ' + CHAR(13)
SET @sql = @sql + '[impound_officer_id], ' + CHAR(13)
SET @sql = @sql + '[archived_key], ' + CHAR(13)
SET @sql = @sql + '[archived_display], ' + CHAR(13)
SET @sql = @sql + '[created_at], ' + CHAR(13)
SET @sql = @sql + '[date_impounded], ' + CHAR(13)
SET @sql = @sql + '[date_of_offence], ' + CHAR(13)
SET @sql = @sql + '[date_released], ' + CHAR(13)
SET @sql = @sql + '[driver_age], ' + CHAR(13)
SET @sql = @sql + '[driver_city], ' + CHAR(13)
SET @sql = @sql + '[driver_gender], ' + CHAR(13)
SET @sql = @sql + '[driver_id_number], ' + CHAR(13)
SET @sql = @sql + '[driver_id_type], ' + CHAR(13)
SET @sql = @sql + '[driver_licence_code], ' + CHAR(13)
SET @sql = @sql + '[driver_licence_expiry], ' + CHAR(13)
SET @sql = @sql + '[driver_licence_number], ' + CHAR(13)
SET @sql = @sql + '[driver_name], ' + CHAR(13)
SET @sql = @sql + '[driver_phone_number], ' + CHAR(13)
SET @sql = @sql + '[driver_postal_code], ' + CHAR(13)
SET @sql = @sql + '[driver_prdp_code], ' + CHAR(13)
SET @sql = @sql + '[driver_street_address_1], ' + CHAR(13)
SET @sql = @sql + '[driver_street_address_2], ' + CHAR(13)
SET @sql = @sql + '[driver_surname], ' + CHAR(13)
SET @sql = @sql + '[incoming_impound_officer_signature], ' + CHAR(13)
SET @sql = @sql + '[incoming_impound_officer_signed_at], ' + CHAR(13)
SET @sql = @sql + '[incoming_inspection_pdf], ' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_generated_at], ' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_status_key], ' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_status_display], ' + CHAR(13)
SET @sql = @sql + '[incoming_report_client_receival_key], ' + CHAR(13)
SET @sql = @sql + '[incoming_report_client_receival_display], ' + CHAR(13)
SET @sql = @sql + '[incoming_vehicle_owner_signature], ' + CHAR(13)
SET @sql = @sql + '[incoming_vehicle_owner_signed_at], ' + CHAR(13)
SET @sql = @sql + '[jack_key], ' + CHAR(13)
SET @sql = @sql + '[jack_display], ' + CHAR(13)
SET @sql = @sql + '[location], ' + CHAR(13)
SET @sql = @sql + '[offence_count_key], ' + CHAR(13)
SET @sql = @sql + '[offence_count_display], ' + CHAR(13)
SET @sql = @sql + '[offence_fine], ' + CHAR(13)
SET @sql = @sql + '[officer_comments], ' + CHAR(13)
SET @sql = @sql + '[outgoing_impound_officer_signature], ' + CHAR(13)
SET @sql = @sql + '[outgoing_impound_officer_signed_at], ' + CHAR(13)
SET @sql = @sql + '[outgoing_inspection_pdf], ' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_generated_at], ' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_status_key], ' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_status_display], ' + CHAR(13)
SET @sql = @sql + '[outgoing_report_client_receival_key], ' + CHAR(13)
SET @sql = @sql + '[outgoing_report_client_receival_display], ' + CHAR(13)
SET @sql = @sql + '[outgoing_vehicle_owner_signature], ' + CHAR(13)
SET @sql = @sql + '[outgoing_vehicle_owner_signed_at], ' + CHAR(13)
SET @sql = @sql + '[override_reason], ' + CHAR(13)
SET @sql = @sql + '[owner_age], ' + CHAR(13)
SET @sql = @sql + '[owner_city], ' + CHAR(13)
SET @sql = @sql + '[owner_gender], ' + CHAR(13)
SET @sql = @sql + '[owner_id_number], ' + CHAR(13)
SET @sql = @sql + '[owner_id_type], ' + CHAR(13)
SET @sql = @sql + '[owner_licence_code], ' + CHAR(13)
SET @sql = @sql + '[owner_licence_expiry], ' + CHAR(13)
SET @sql = @sql + '[owner_licence_number], ' + CHAR(13)
SET @sql = @sql + '[owner_name], ' + CHAR(13)
SET @sql = @sql + '[owner_phone_number], ' + CHAR(13)
SET @sql = @sql + '[owner_postal_code], ' + CHAR(13)
SET @sql = @sql + '[owner_prdp_code], ' + CHAR(13)
SET @sql = @sql + '[owner_street_address_1], ' + CHAR(13)
SET @sql = @sql + '[owner_street_address_2], ' + CHAR(13)
SET @sql = @sql + '[owner_surname], ' + CHAR(13)
SET @sql = @sql + '[payload], ' + CHAR(13)
SET @sql = @sql + '[release_as_scrap_key], ' + CHAR(13)
SET @sql = @sql + '[release_as_scrap_display], ' + CHAR(13)
SET @sql = @sql + '[scrap_document_photo], ' + CHAR(13)
SET @sql = @sql + '[scrap_reason], ' + CHAR(13)
SET @sql = @sql + '[spanners_key], ' + CHAR(13)
SET @sql = @sql + '[spanners_display], ' + CHAR(13)
SET @sql = @sql + '[status_key], ' + CHAR(13)
SET @sql = @sql + '[status_display], ' + CHAR(13)
SET @sql = @sql + '[total_broken_incoming], ' + CHAR(13)
SET @sql = @sql + '[total_broken_outgoing], ' + CHAR(13)
SET @sql = @sql + '[total_missing_incoming], ' + CHAR(13)
SET @sql = @sql + '[total_missing_outgoing], ' + CHAR(13)
SET @sql = @sql + '[total_ok_incoming], ' + CHAR(13)
SET @sql = @sql + '[total_ok_outgoing], ' + CHAR(13)
SET @sql = @sql + '[vehicle_class], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour], ' + CHAR(13)
SET @sql = @sql + '[vehicle_engine_number], ' + CHAR(13)
SET @sql = @sql + '[vehicle_licence_expiry_date], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make], ' + CHAR(13)
SET @sql = @sql + '[vehicle_model], ' + CHAR(13)
SET @sql = @sql + '[vehicle_no_passengers], ' + CHAR(13)
SET @sql = @sql + '[vehicle_register_number], ' + CHAR(13)
SET @sql = @sql + '[vehicle_registration], ' + CHAR(13)
SET @sql = @sql + '[vehicle_vin_number], ' + CHAR(13)
SET @sql = @sql + '[violation_type_key], ' + CHAR(13)
SET @sql = @sql + '[violation_type_display], ' + CHAR(13)
SET @sql = @sql + '[wheel_brace_key], ' + CHAR(13)
SET @sql = @sql + '[wheel_brace_display], ' + CHAR(13)
SET @sql = @sql + '[written_notice_number], ' + CHAR(13)
SET @sql = @sql + '[deltalogkey],' + CHAR(13)
SET @sql = @sql + '[auditkey]' + CHAR(13)
--Insert End
SET @sql = @sql + ')' + CHAR(13)
SET @sql = @sql + 'SELECT ' 
--Select Begin
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
SET @sql = @sql + '[impound_id], ' + CHAR(13)
SET @sql = @sql + '[impound_officer_id], ' + CHAR(13)
SET @sql = @sql + '[archived_key], ' + CHAR(13)
SET @sql = @sql + '[archived_display], ' + CHAR(13)
SET @sql = @sql + '[created_at], ' + CHAR(13)
SET @sql = @sql + '[date_impounded], ' + CHAR(13)
SET @sql = @sql + '[date_of_offence], ' + CHAR(13)
SET @sql = @sql + '[date_released], ' + CHAR(13)
SET @sql = @sql + '[driver_age], ' + CHAR(13)
SET @sql = @sql + '[driver_city], ' + CHAR(13)
SET @sql = @sql + '[driver_gender], ' + CHAR(13)
SET @sql = @sql + '[driver_id_number], ' + CHAR(13)
SET @sql = @sql + '[driver_id_type], ' + CHAR(13)
SET @sql = @sql + '[driver_licence_code], ' + CHAR(13)
SET @sql = @sql + '[driver_licence_expiry], ' + CHAR(13)
SET @sql = @sql + '[driver_licence_number], ' + CHAR(13)
SET @sql = @sql + '[driver_name], ' + CHAR(13)
SET @sql = @sql + '[driver_phone_number], ' + CHAR(13)
SET @sql = @sql + '[driver_postal_code], ' + CHAR(13)
SET @sql = @sql + '[driver_prdp_code], ' + CHAR(13)
SET @sql = @sql + '[driver_street_address_1], ' + CHAR(13)
SET @sql = @sql + '[driver_street_address_2], ' + CHAR(13)
SET @sql = @sql + '[driver_surname], ' + CHAR(13)
SET @sql = @sql + '[incoming_impound_officer_signature], ' + CHAR(13)
SET @sql = @sql + '[incoming_impound_officer_signed_at], ' + CHAR(13)
SET @sql = @sql + '[incoming_inspection_pdf], ' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_generated_at], ' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_status_key], ' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_status_display], ' + CHAR(13)
SET @sql = @sql + '[incoming_report_client_receival_key], ' + CHAR(13)
SET @sql = @sql + '[incoming_report_client_receival_display], ' + CHAR(13)
SET @sql = @sql + '[incoming_vehicle_owner_signature], ' + CHAR(13)
SET @sql = @sql + '[incoming_vehicle_owner_signed_at], ' + CHAR(13)
SET @sql = @sql + '[jack_key], ' + CHAR(13)
SET @sql = @sql + '[jack_display], ' + CHAR(13)
SET @sql = @sql + '[location], ' + CHAR(13)
SET @sql = @sql + '[offence_count_key], ' + CHAR(13)
SET @sql = @sql + '[offence_count_display], ' + CHAR(13)
SET @sql = @sql + '[offence_fine], ' + CHAR(13)
SET @sql = @sql + '[officer_comments], ' + CHAR(13)
SET @sql = @sql + '[outgoing_impound_officer_signature], ' + CHAR(13)
SET @sql = @sql + '[outgoing_impound_officer_signed_at], ' + CHAR(13)
SET @sql = @sql + '[outgoing_inspection_pdf], ' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_generated_at], ' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_status_key], ' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_status_display], ' + CHAR(13)
SET @sql = @sql + '[outgoing_report_client_receival_key], ' + CHAR(13)
SET @sql = @sql + '[outgoing_report_client_receival_display], ' + CHAR(13)
SET @sql = @sql + '[outgoing_vehicle_owner_signature], ' + CHAR(13)
SET @sql = @sql + '[outgoing_vehicle_owner_signed_at], ' + CHAR(13)
SET @sql = @sql + '[override_reason], ' + CHAR(13)
SET @sql = @sql + '[owner_age], ' + CHAR(13)
SET @sql = @sql + '[owner_city], ' + CHAR(13)
SET @sql = @sql + '[owner_gender], ' + CHAR(13)
SET @sql = @sql + '[owner_id_number], ' + CHAR(13)
SET @sql = @sql + '[owner_id_type], ' + CHAR(13)
SET @sql = @sql + '[owner_licence_code], ' + CHAR(13)
SET @sql = @sql + '[owner_licence_expiry], ' + CHAR(13)
SET @sql = @sql + '[owner_licence_number], ' + CHAR(13)
SET @sql = @sql + '[owner_name], ' + CHAR(13)
SET @sql = @sql + '[owner_phone_number], ' + CHAR(13)
SET @sql = @sql + '[owner_postal_code], ' + CHAR(13)
SET @sql = @sql + '[owner_prdp_code], ' + CHAR(13)
SET @sql = @sql + '[owner_street_address_1], ' + CHAR(13)
SET @sql = @sql + '[owner_street_address_2], ' + CHAR(13)
SET @sql = @sql + '[owner_surname], ' + CHAR(13)
SET @sql = @sql + '[payload], ' + CHAR(13)
SET @sql = @sql + '[release_as_scrap_key], ' + CHAR(13)
SET @sql = @sql + '[release_as_scrap_display], ' + CHAR(13)
SET @sql = @sql + '[scrap_document_photo], ' + CHAR(13)
SET @sql = @sql + '[scrap_reason], ' + CHAR(13)
SET @sql = @sql + '[spanners_key], ' + CHAR(13)
SET @sql = @sql + '[spanners_display], ' + CHAR(13)
SET @sql = @sql + '[status_key], ' + CHAR(13)
SET @sql = @sql + '[status_display], ' + CHAR(13)
SET @sql = @sql + '[total_broken_incoming], ' + CHAR(13)
SET @sql = @sql + '[total_broken_outgoing], ' + CHAR(13)
SET @sql = @sql + '[total_missing_incoming], ' + CHAR(13)
SET @sql = @sql + '[total_missing_outgoing], ' + CHAR(13)
SET @sql = @sql + '[total_ok_incoming], ' + CHAR(13)
SET @sql = @sql + '[total_ok_outgoing], ' + CHAR(13)
SET @sql = @sql + '[vehicle_class], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour], ' + CHAR(13)
SET @sql = @sql + '[vehicle_engine_number], ' + CHAR(13)
SET @sql = @sql + '[vehicle_licence_expiry_date], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make], ' + CHAR(13)
SET @sql = @sql + '[vehicle_model], ' + CHAR(13)
SET @sql = @sql + '[vehicle_no_passengers], ' + CHAR(13)
SET @sql = @sql + '[vehicle_register_number], ' + CHAR(13)
SET @sql = @sql + '[vehicle_registration], ' + CHAR(13)
SET @sql = @sql + '[vehicle_vin_number], ' + CHAR(13)
SET @sql = @sql + '[violation_type_key], ' + CHAR(13)
SET @sql = @sql + '[violation_type_display], ' + CHAR(13)
SET @sql = @sql + '[wheel_brace_key], ' + CHAR(13)
SET @sql = @sql + '[wheel_brace_display], ' + CHAR(13)
SET @sql = @sql + '[written_notice_number], ' + CHAR(13)
--Select End
SET @sql = @sql + CAST(@DeltaLogKey AS VARCHAR(10)) + ',' + CAST(@AuditKey AS VARCHAR(10)) +  CHAR(13)
SET @sql = @sql + 'FROM OPENJSON(@json, ''$.objects'') '   + CHAR(13)
SET @sql = @sql + 'WITH ( ' + CHAR(13)
--WITH Begin
SET @sql = @sql + '[id] [uniqueidentifier] ''$.id'',' + CHAR(13)
SET @sql = @sql + '[type] [nvarchar](max) ''$.type'',' + CHAR(13)
SET @sql = @sql + '[updated_at] [nvarchar](max) ''$.updated_at'',' + CHAR(13)
SET @sql = @sql + '[display] [nvarchar](max) ''$.display'',' + CHAR(13)
SET @sql = @sql + '[impound_id] [varchar](max) ''$.impound_id'',' + CHAR(13)
SET @sql = @sql + '[impound_officer_id] [varchar](max) ''$.impound_officer_id'',' + CHAR(13)
SET @sql = @sql + '[archived_key] [varchar](max) ''$.archived.key'',' + CHAR(13)
SET @sql = @sql + '[archived_display] [varchar](max) ''$.archived.display'',' + CHAR(13)
SET @sql = @sql + '[created_at] [varchar](max) ''$.created_at'',' + CHAR(13)
SET @sql = @sql + '[date_impounded] [varchar](max) ''$.date_impounded'',' + CHAR(13)
SET @sql = @sql + '[date_of_offence] [varchar](max) ''$.date_of_offence'',' + CHAR(13)
SET @sql = @sql + '[date_released] [varchar](max) ''$.date_released'',' + CHAR(13)
SET @sql = @sql + '[driver_age] [varchar](max) ''$.driver_age'',' + CHAR(13)
SET @sql = @sql + '[driver_city] [varchar](max) ''$.driver_city'',' + CHAR(13)
SET @sql = @sql + '[driver_gender] [varchar](max) ''$.driver_gender'',' + CHAR(13)
SET @sql = @sql + '[driver_id_number] [varchar](max) ''$.driver_id_number'',' + CHAR(13)
SET @sql = @sql + '[driver_id_type] [varchar](max) ''$.driver_id_type'',' + CHAR(13)
SET @sql = @sql + '[driver_licence_code] [varchar](max) ''$.driver_licence_code'',' + CHAR(13)
SET @sql = @sql + '[driver_licence_expiry] [varchar](max) ''$.driver_licence_expiry'',' + CHAR(13)
SET @sql = @sql + '[driver_licence_number] [varchar](max) ''$.driver_licence_number'',' + CHAR(13)
SET @sql = @sql + '[driver_name] [varchar](max) ''$.driver_name'',' + CHAR(13)
SET @sql = @sql + '[driver_phone_number] [varchar](max) ''$.driver_phone_number'',' + CHAR(13)
SET @sql = @sql + '[driver_postal_code] [varchar](max) ''$.driver_postal_code'',' + CHAR(13)
SET @sql = @sql + '[driver_prdp_code] [varchar](max) ''$.driver_prdp_code'',' + CHAR(13)
SET @sql = @sql + '[driver_street_address_1] [varchar](max) ''$.driver_street_address_1'',' + CHAR(13)
SET @sql = @sql + '[driver_street_address_2] [varchar](max) ''$.driver_street_address_2'',' + CHAR(13)
SET @sql = @sql + '[driver_surname] [varchar](max) ''$.driver_surname'',' + CHAR(13)
SET @sql = @sql + '[incoming_impound_officer_signature] [varchar](max) ''$.incoming_impound_officer_signature'',' + CHAR(13)
SET @sql = @sql + '[incoming_impound_officer_signed_at] [varchar](max) ''$.incoming_impound_officer_signed_at'',' + CHAR(13)
SET @sql = @sql + '[incoming_inspection_pdf] [varchar](max) ''$.incoming_inspection_pdf'',' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_generated_at] [varchar](max) ''$.incoming_pdf_generated_at'',' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_status_key] [varchar](max) ''$.incoming_pdf_status.key'',' + CHAR(13)
SET @sql = @sql + '[incoming_pdf_status_display] [varchar](max) ''$.incoming_pdf_status.display'',' + CHAR(13)
SET @sql = @sql + '[incoming_report_client_receival_key] [varchar](max) ''$.incoming_report_client_receival.key'',' + CHAR(13)
SET @sql = @sql + '[incoming_report_client_receival_display] [varchar](max) ''$.incoming_report_client_receival.display'',' + CHAR(13)
SET @sql = @sql + '[incoming_vehicle_owner_signature] [varchar](max) ''$.incoming_vehicle_owner_signature'',' + CHAR(13)
SET @sql = @sql + '[incoming_vehicle_owner_signed_at] [varchar](max) ''$.incoming_vehicle_owner_signed_at'',' + CHAR(13)
SET @sql = @sql + '[jack_key] [varchar](max) ''$.jack.key'',' + CHAR(13)
SET @sql = @sql + '[jack_display] [varchar](max) ''$.jack.display'',' + CHAR(13)
SET @sql = @sql + '[location] [varchar](max) ''$.location'',' + CHAR(13)
SET @sql = @sql + '[offence_count_key] [varchar](max) ''$.offence_count.key'',' + CHAR(13)
SET @sql = @sql + '[offence_count_display] [varchar](max) ''$.offence_count.display'',' + CHAR(13)
SET @sql = @sql + '[offence_fine] [varchar](max) ''$.offence_fine'',' + CHAR(13)
SET @sql = @sql + '[officer_comments] [varchar](max) ''$.officer_comments'',' + CHAR(13)
SET @sql = @sql + '[outgoing_impound_officer_signature] [varchar](max) ''$.outgoing_impound_officer_signature'',' + CHAR(13)
SET @sql = @sql + '[outgoing_impound_officer_signed_at] [varchar](max) ''$.outgoing_impound_officer_signed_at'',' + CHAR(13)
SET @sql = @sql + '[outgoing_inspection_pdf] [varchar](max) ''$.outgoing_inspection_pdf'',' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_generated_at] [varchar](max) ''$.outgoing_pdf_generated_at'',' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_status_key] [varchar](max) ''$.outgoing_pdf_status.key'',' + CHAR(13)
SET @sql = @sql + '[outgoing_pdf_status_display] [varchar](max) ''$.outgoing_pdf_status.display'',' + CHAR(13)
SET @sql = @sql + '[outgoing_report_client_receival_key] [varchar](max) ''$.outgoing_report_client_receival.key'',' + CHAR(13)
SET @sql = @sql + '[outgoing_report_client_receival_display] [varchar](max) ''$.outgoing_report_client_receival.display'',' + CHAR(13)
SET @sql = @sql + '[outgoing_vehicle_owner_signature] [varchar](max) ''$.outgoing_vehicle_owner_signature'',' + CHAR(13)
SET @sql = @sql + '[outgoing_vehicle_owner_signed_at] [varchar](max) ''$.outgoing_vehicle_owner_signed_at'',' + CHAR(13)
SET @sql = @sql + '[override_reason] [varchar](max) ''$.override_reason'',' + CHAR(13)
SET @sql = @sql + '[owner_age] [varchar](max) ''$.owner_age'',' + CHAR(13)
SET @sql = @sql + '[owner_city] [varchar](max) ''$.owner_city'',' + CHAR(13)
SET @sql = @sql + '[owner_gender] [varchar](max) ''$.owner_gender'',' + CHAR(13)
SET @sql = @sql + '[owner_id_number] [varchar](max) ''$.owner_id_number'',' + CHAR(13)
SET @sql = @sql + '[owner_id_type] [varchar](max) ''$.owner_id_type'',' + CHAR(13)
SET @sql = @sql + '[owner_licence_code] [varchar](max) ''$.owner_licence_code'',' + CHAR(13)
SET @sql = @sql + '[owner_licence_expiry] [varchar](max) ''$.owner_licence_expiry'',' + CHAR(13)
SET @sql = @sql + '[owner_licence_number] [varchar](max) ''$.owner_licence_number'',' + CHAR(13)
SET @sql = @sql + '[owner_name] [varchar](max) ''$.owner_name'',' + CHAR(13)
SET @sql = @sql + '[owner_phone_number] [varchar](max) ''$.owner_phone_number'',' + CHAR(13)
SET @sql = @sql + '[owner_postal_code] [varchar](max) ''$.owner_postal_code'',' + CHAR(13)
SET @sql = @sql + '[owner_prdp_code] [varchar](max) ''$.owner_prdp_code'',' + CHAR(13)
SET @sql = @sql + '[owner_street_address_1] [varchar](max) ''$.owner_street_address_1'',' + CHAR(13)
SET @sql = @sql + '[owner_street_address_2] [varchar](max) ''$.owner_street_address_2'',' + CHAR(13)
SET @sql = @sql + '[owner_surname] [varchar](max) ''$.owner_surname'',' + CHAR(13)
SET @sql = @sql + '[payload] [varchar](max) ''$.payload'',' + CHAR(13)
SET @sql = @sql + '[release_as_scrap_key] [varchar](max) ''$.release_as_scrap.key'',' + CHAR(13)
SET @sql = @sql + '[release_as_scrap_display] [varchar](max) ''$.release_as_scrap.display'',' + CHAR(13)
SET @sql = @sql + '[scrap_document_photo] [varchar](max) ''$.scrap_document_photo'',' + CHAR(13)
SET @sql = @sql + '[scrap_reason] [varchar](max) ''$.scrap_reason'',' + CHAR(13)
SET @sql = @sql + '[spanners_key] [varchar](max) ''$.spanners.key'',' + CHAR(13)
SET @sql = @sql + '[spanners_display] [varchar](max) ''$.spanners.display'',' + CHAR(13)
SET @sql = @sql + '[status_key] [varchar](max) ''$.status.key'',' + CHAR(13)
SET @sql = @sql + '[status_display] [varchar](max) ''$.status.display'',' + CHAR(13)
SET @sql = @sql + '[total_broken_incoming] [varchar](max) ''$.total_broken_incoming'',' + CHAR(13)
SET @sql = @sql + '[total_broken_outgoing] [varchar](max) ''$.total_broken_outgoing'',' + CHAR(13)
SET @sql = @sql + '[total_missing_incoming] [varchar](max) ''$.total_missing_incoming'',' + CHAR(13)
SET @sql = @sql + '[total_missing_outgoing] [varchar](max) ''$.total_missing_outgoing'',' + CHAR(13)
SET @sql = @sql + '[total_ok_incoming] [varchar](max) ''$.total_ok_incoming'',' + CHAR(13)
SET @sql = @sql + '[total_ok_outgoing] [varchar](max) ''$.total_ok_outgoing'',' + CHAR(13)
SET @sql = @sql + '[vehicle_class] [varchar](max) ''$.vehicle_class'',' + CHAR(13)
SET @sql = @sql + '[vehicle_colour] [varchar](max) ''$.vehicle_colour'',' + CHAR(13)
SET @sql = @sql + '[vehicle_engine_number] [varchar](max) ''$.vehicle_engine_number'',' + CHAR(13)
SET @sql = @sql + '[vehicle_licence_expiry_date] [varchar](max) ''$.vehicle_licence_expiry_date'',' + CHAR(13)
SET @sql = @sql + '[vehicle_make] [varchar](max) ''$.vehicle_make'',' + CHAR(13)
SET @sql = @sql + '[vehicle_model] [varchar](max) ''$.vehicle_model'',' + CHAR(13)
SET @sql = @sql + '[vehicle_no_passengers] [varchar](max) ''$.vehicle_no_passengers'',' + CHAR(13)
SET @sql = @sql + '[vehicle_register_number] [varchar](max) ''$.vehicle_register_number'',' + CHAR(13)
SET @sql = @sql + '[vehicle_registration] [varchar](max) ''$.vehicle_registration'',' + CHAR(13)
SET @sql = @sql + '[vehicle_vin_number] [varchar](max) ''$.vehicle_vin_number'',' + CHAR(13)
SET @sql = @sql + '[violation_type_key] [varchar](max) ''$.violation_type.key'',' + CHAR(13)
SET @sql = @sql + '[violation_type_display] [varchar](max) ''$.violation_type.display'',' + CHAR(13)
SET @sql = @sql + '[wheel_brace_key] [varchar](max) ''$.wheel_brace.key'',' + CHAR(13)
SET @sql = @sql + '[wheel_brace_display] [varchar](max) ''$.wheel_brace.display'',' + CHAR(13)
SET @sql = @sql + '[written_notice_number] [varchar](max) ''$.written_notice_number''' + CHAR(13)
--WITH End
SET @sql = @sql + ')' + CHAR(13)

EXEC(@SQL)

