

CREATE PROCEDURE [ebat].[prcExtractebat_report]

--------------------------------------------------------------------------------------------------------------------------------------
-- Author				:	Generated from Model
-- Date Created			:	18-10-2017 05:01:55
-- Reason				:	Reads JSON file and inserts data into Stage table (ebat_report)
--------------------------------------------------------------------------------------------------------------------------------------
-- Inputs				:	@FileName, @DeltaLogKey, @AuditKey
-- Ouputs				:	@RowCountStage
-- Test					:	exec ebat.prcExtractebat_report 'D:\PSA\WCG\sql\ebat_report.json'
--------------------------------------------------------------------------------------------------------------------------------------
-- Modified By	:
-- Modified On	:
-- Reason				:
--------------------------------------------------------------------------------------------------------------------------------------

@FileName NVARCHAR(MAX),
@DeltaLogKey INT = -1,
@AuditKey INT = -1,
@TruncateFlag INT = 0

AS

IF @TruncateFlag = 1 TRUNCATE TABLE [ebat].[ebat_report]

DECLARE @sql AS NVARCHAR(MAX)

SET @sql = 'DECLARE @json NVARCHAR(MAX) ' + CHAR(13)
SET @sql = @sql + 'SELECT @json = BulkColumn FROM OPENROWSET (BULK ''' + @FileName + ''', SINGLE_CLOB) as j' + CHAR(13)
SET @sql = @sql + 'INSERT INTO [ebat].[ebat_report] (' + CHAR(13)
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
--Insert Begin
SET @sql = @sql + '[centre_id], ' + CHAR(13)
SET @sql = @sql + '[completed_by_id], ' + CHAR(13)
SET @sql = @sql + '[driver_id], ' + CHAR(13)
SET @sql = @sql + '[ebat_device_id], ' + CHAR(13)
SET @sql = @sql + '[magistrates_court_id], ' + CHAR(13)
SET @sql = @sql + '[officer_id], ' + CHAR(13)
SET @sql = @sql + '[operator_id], ' + CHAR(13)
SET @sql = @sql + '[reading_by_id], ' + CHAR(13)
SET @sql = @sql + '[registered_by_id], ' + CHAR(13)
SET @sql = @sql + '[station_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_id], ' + CHAR(13)
SET @sql = @sql + '[verified_by_id], ' + CHAR(13)
SET @sql = @sql + '[abort_comment], ' + CHAR(13)
SET @sql = @sql + '[abort_ob_number], ' + CHAR(13)
SET @sql = @sql + '[abort_reason], ' + CHAR(13)
SET @sql = @sql + '[accident_key], ' + CHAR(13)
SET @sql = @sql + '[accident_display], ' + CHAR(13)
SET @sql = @sql + '[accident_location], ' + CHAR(13)
SET @sql = @sql + '[address_line_1], ' + CHAR(13)
SET @sql = @sql + '[address_line_2], ' + CHAR(13)
SET @sql = @sql + '[address_line_3], ' + CHAR(13)
SET @sql = @sql + '[admin_timestamp], ' + CHAR(13)
SET @sql = @sql + '[archived_key], ' + CHAR(13)
SET @sql = @sql + '[archived_display], ' + CHAR(13)
SET @sql = @sql + '[cas_number], ' + CHAR(13)
SET @sql = @sql + '[cas_or_ob_key], ' + CHAR(13)
SET @sql = @sql + '[cas_or_ob_display], ' + CHAR(13)
SET @sql = @sql + '[created_at], ' + CHAR(13)
SET @sql = @sql + '[measurement1_try1], ' + CHAR(13)
SET @sql = @sql + '[measurement1_try2], ' + CHAR(13)
SET @sql = @sql + '[measurement1_try3], ' + CHAR(13)
SET @sql = @sql + '[measurement2_try1], ' + CHAR(13)
SET @sql = @sql + '[measurement2_try2], ' + CHAR(13)
SET @sql = @sql + '[measurement2_try3], ' + CHAR(13)
SET @sql = @sql + '[nature_of_injuries_key], ' + CHAR(13)
SET @sql = @sql + '[nature_of_injuries_display], ' + CHAR(13)
SET @sql = @sql + '[not_successful_reason], ' + CHAR(13)
SET @sql = @sql + '[number_of_vehicles], ' + CHAR(13)
SET @sql = @sql + '[ob_number], ' + CHAR(13)
SET @sql = @sql + '[protocol_number], ' + CHAR(13)
SET @sql = @sql + '[reading], ' + CHAR(13)
SET @sql = @sql + '[reading_timestamp], ' + CHAR(13)
SET @sql = @sql + '[record_number], ' + CHAR(13)
SET @sql = @sql + '[referred_key], ' + CHAR(13)
SET @sql = @sql + '[referred_display], ' + CHAR(13)
SET @sql = @sql + '[referred_location], ' + CHAR(13)
SET @sql = @sql + '[referred_type_key], ' + CHAR(13)
SET @sql = @sql + '[referred_type_display], ' + CHAR(13)
SET @sql = @sql + '[referred_type_other], ' + CHAR(13)
SET @sql = @sql + '[result_key], ' + CHAR(13)
SET @sql = @sql + '[result_display], ' + CHAR(13)
SET @sql = @sql + '[roadside_activity_key], ' + CHAR(13)
SET @sql = @sql + '[roadside_activity_display], ' + CHAR(13)
SET @sql = @sql + '[status_key], ' + CHAR(13)
SET @sql = @sql + '[status_display], ' + CHAR(13)
SET @sql = @sql + '[subject_age], ' + CHAR(13)
SET @sql = @sql + '[subject_date_of_birth], ' + CHAR(13)
SET @sql = @sql + '[subject_full_name], ' + CHAR(13)
SET @sql = @sql + '[subject_gender_key], ' + CHAR(13)
SET @sql = @sql + '[subject_gender_display], ' + CHAR(13)
SET @sql = @sql + '[subject_identification], ' + CHAR(13)
SET @sql = @sql + '[subject_identification_type_key], ' + CHAR(13)
SET @sql = @sql + '[subject_identification_type_display], ' + CHAR(13)
SET @sql = @sql + '[subject_id_number], ' + CHAR(13)
SET @sql = @sql + '[subject_initials], ' + CHAR(13)
SET @sql = @sql + '[subject_occupation_sector_key], ' + CHAR(13)
SET @sql = @sql + '[subject_occupation_sector_display], ' + CHAR(13)
SET @sql = @sql + '[subject_photo], ' + CHAR(13)
SET @sql = @sql + '[subject_photo_at_reading], ' + CHAR(13)
SET @sql = @sql + '[subject_surname], ' + CHAR(13)
SET @sql = @sql + '[subject_tel_no], ' + CHAR(13)
SET @sql = @sql + '[supporting_documents], ' + CHAR(13)
SET @sql = @sql + '[time_of_arrest], ' + CHAR(13)
SET @sql = @sql + '[time_of_arrival], ' + CHAR(13)
SET @sql = @sql + '[time_of_departure], ' + CHAR(13)
SET @sql = @sql + '[time_of_reading_start], ' + CHAR(13)
SET @sql = @sql + '[time_of_reading_stop], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make], ' + CHAR(13)
SET @sql = @sql + '[vehicle_registration_number], ' + CHAR(13)
SET @sql = @sql + '[vehicle_type_key], ' + CHAR(13)
SET @sql = @sql + '[vehicle_type_display], ' + CHAR(13)
SET @sql = @sql + '[verified_at], ' + CHAR(13)
SET @sql = @sql + '[deltalogkey],' + CHAR(13)
SET @sql = @sql + '[AuditKey]' + CHAR(13)
--Insert End
SET @sql = @sql + ')' + CHAR(13)
SET @sql = @sql + 'SELECT ' 
--Select Begin
SET @sql = @sql + '[id], ' + CHAR(13)
SET @sql = @sql + '[type], ' + CHAR(13)
SET @sql = @sql + '[updated_at], ' + CHAR(13)
SET @sql = @sql + '[display], ' + CHAR(13)
SET @sql = @sql + '[centre_id], ' + CHAR(13)
SET @sql = @sql + '[completed_by_id], ' + CHAR(13)
SET @sql = @sql + '[driver_id], ' + CHAR(13)
SET @sql = @sql + '[ebat_device_id], ' + CHAR(13)
SET @sql = @sql + '[magistrates_court_id], ' + CHAR(13)
SET @sql = @sql + '[officer_id], ' + CHAR(13)
SET @sql = @sql + '[operator_id], ' + CHAR(13)
SET @sql = @sql + '[reading_by_id], ' + CHAR(13)
SET @sql = @sql + '[registered_by_id], ' + CHAR(13)
SET @sql = @sql + '[station_id], ' + CHAR(13)
SET @sql = @sql + '[vehicle_id], ' + CHAR(13)
SET @sql = @sql + '[verified_by_id], ' + CHAR(13)
SET @sql = @sql + '[abort_comment], ' + CHAR(13)
SET @sql = @sql + '[abort_ob_number], ' + CHAR(13)
SET @sql = @sql + '[abort_reason], ' + CHAR(13)
SET @sql = @sql + '[accident_key], ' + CHAR(13)
SET @sql = @sql + '[accident_display], ' + CHAR(13)
SET @sql = @sql + '[accident_location], ' + CHAR(13)
SET @sql = @sql + '[address_line_1], ' + CHAR(13)
SET @sql = @sql + '[address_line_2], ' + CHAR(13)
SET @sql = @sql + '[address_line_3], ' + CHAR(13)
SET @sql = @sql + '[admin_timestamp], ' + CHAR(13)
SET @sql = @sql + '[archived_key], ' + CHAR(13)
SET @sql = @sql + '[archived_display], ' + CHAR(13)
SET @sql = @sql + '[cas_number], ' + CHAR(13)
SET @sql = @sql + '[cas_or_ob_key], ' + CHAR(13)
SET @sql = @sql + '[cas_or_ob_display], ' + CHAR(13)
SET @sql = @sql + '[created_at], ' + CHAR(13)
SET @sql = @sql + '[measurement1_try1], ' + CHAR(13)
SET @sql = @sql + '[measurement1_try2], ' + CHAR(13)
SET @sql = @sql + '[measurement1_try3], ' + CHAR(13)
SET @sql = @sql + '[measurement2_try1], ' + CHAR(13)
SET @sql = @sql + '[measurement2_try2], ' + CHAR(13)
SET @sql = @sql + '[measurement2_try3], ' + CHAR(13)
SET @sql = @sql + '[nature_of_injuries_key], ' + CHAR(13)
SET @sql = @sql + '[nature_of_injuries_display], ' + CHAR(13)
SET @sql = @sql + '[not_successful_reason], ' + CHAR(13)
SET @sql = @sql + '[number_of_vehicles], ' + CHAR(13)
SET @sql = @sql + '[ob_number], ' + CHAR(13)
SET @sql = @sql + '[protocol_number], ' + CHAR(13)
SET @sql = @sql + '[reading], ' + CHAR(13)
SET @sql = @sql + '[reading_timestamp], ' + CHAR(13)
SET @sql = @sql + '[record_number], ' + CHAR(13)
SET @sql = @sql + '[referred_key], ' + CHAR(13)
SET @sql = @sql + '[referred_display], ' + CHAR(13)
SET @sql = @sql + '[referred_location], ' + CHAR(13)
SET @sql = @sql + '[referred_type_key], ' + CHAR(13)
SET @sql = @sql + '[referred_type_display], ' + CHAR(13)
SET @sql = @sql + '[referred_type_other], ' + CHAR(13)
SET @sql = @sql + '[result_key], ' + CHAR(13)
SET @sql = @sql + '[result_display], ' + CHAR(13)
SET @sql = @sql + '[roadside_activity_key], ' + CHAR(13)
SET @sql = @sql + '[roadside_activity_display], ' + CHAR(13)
SET @sql = @sql + '[status_key], ' + CHAR(13)
SET @sql = @sql + '[status_display], ' + CHAR(13)
SET @sql = @sql + '[subject_age], ' + CHAR(13)
SET @sql = @sql + '[subject_date_of_birth], ' + CHAR(13)
SET @sql = @sql + '[subject_full_name], ' + CHAR(13)
SET @sql = @sql + '[subject_gender_key], ' + CHAR(13)
SET @sql = @sql + '[subject_gender_display], ' + CHAR(13)
SET @sql = @sql + '[subject_identification], ' + CHAR(13)
SET @sql = @sql + '[subject_identification_type_key], ' + CHAR(13)
SET @sql = @sql + '[subject_identification_type_display], ' + CHAR(13)
SET @sql = @sql + '[subject_id_number], ' + CHAR(13)
SET @sql = @sql + '[subject_initials], ' + CHAR(13)
SET @sql = @sql + '[subject_occupation_sector_key], ' + CHAR(13)
SET @sql = @sql + '[subject_occupation_sector_display], ' + CHAR(13)
SET @sql = @sql + '[subject_photo], ' + CHAR(13)
SET @sql = @sql + '[subject_photo_at_reading], ' + CHAR(13)
SET @sql = @sql + '[subject_surname], ' + CHAR(13)
SET @sql = @sql + '[subject_tel_no], ' + CHAR(13)
SET @sql = @sql + '[supporting_documents], ' + CHAR(13)
SET @sql = @sql + '[time_of_arrest], ' + CHAR(13)
SET @sql = @sql + '[time_of_arrival], ' + CHAR(13)
SET @sql = @sql + '[time_of_departure], ' + CHAR(13)
SET @sql = @sql + '[time_of_reading_start], ' + CHAR(13)
SET @sql = @sql + '[time_of_reading_stop], ' + CHAR(13)
SET @sql = @sql + '[vehicle_colour], ' + CHAR(13)
SET @sql = @sql + '[vehicle_make], ' + CHAR(13)
SET @sql = @sql + '[vehicle_registration_number], ' + CHAR(13)
SET @sql = @sql + '[vehicle_type_key], ' + CHAR(13)
SET @sql = @sql + '[vehicle_type_display], ' + CHAR(13)
SET @sql = @sql + '[verified_at], ' + CHAR(13)
--Select End
SET @sql = @sql + CAST(@DeltaLogKey AS VARCHAR(10)) + ',' + CAST(@AuditKey AS VARCHAR(10)) +  CHAR(13)
SET @sql = @sql + 'FROM OPENJSON(@json, ''$.objects'') '   + CHAR(13)
SET @sql = @sql + 'WITH ( ' + CHAR(13)
--WITH Begin
SET @sql = @sql + '[id] [uniqueidentifier] ''$.id'',' + CHAR(13)
SET @sql = @sql + '[type] [nvarchar](max) ''$.type'',' + CHAR(13)
SET @sql = @sql + '[updated_at] [nvarchar](max) ''$.updated_at'',' + CHAR(13)
SET @sql = @sql + '[display] [nvarchar](max) ''$.display'',' + CHAR(13)
SET @sql = @sql + '[centre_id] [varchar](max) ''$.centre_id'',' + CHAR(13)
SET @sql = @sql + '[completed_by_id] [varchar](max) ''$.completed_by_id'',' + CHAR(13)
SET @sql = @sql + '[driver_id] [varchar](max) ''$.driver_id'',' + CHAR(13)
SET @sql = @sql + '[ebat_device_id] [varchar](max) ''$.ebat_device_id'',' + CHAR(13)
SET @sql = @sql + '[magistrates_court_id] [varchar](max) ''$.magistrates_court_id'',' + CHAR(13)
SET @sql = @sql + '[officer_id] [varchar](max) ''$.officer_id'',' + CHAR(13)
SET @sql = @sql + '[operator_id] [varchar](max) ''$.operator_id'',' + CHAR(13)
SET @sql = @sql + '[reading_by_id] [varchar](max) ''$.reading_by_id'',' + CHAR(13)
SET @sql = @sql + '[registered_by_id] [varchar](max) ''$.registered_by_id'',' + CHAR(13)
SET @sql = @sql + '[station_id] [varchar](max) ''$.station_id'',' + CHAR(13)
SET @sql = @sql + '[vehicle_id] [varchar](max) ''$.vehicle_id'',' + CHAR(13)
SET @sql = @sql + '[verified_by_id] [varchar](max) ''$.verified_by_id'',' + CHAR(13)
SET @sql = @sql + '[abort_comment] [varchar](max) ''$.abort_comment'',' + CHAR(13)
SET @sql = @sql + '[abort_ob_number] [varchar](max) ''$.abort_ob_number'',' + CHAR(13)
SET @sql = @sql + '[abort_reason] [varchar](max) ''$.abort_reason'',' + CHAR(13)
SET @sql = @sql + '[accident_key] [varchar](max) ''$.accident.key'',' + CHAR(13)
SET @sql = @sql + '[accident_display] [varchar](max) ''$.accident.display'',' + CHAR(13)
SET @sql = @sql + '[accident_location] [varchar](max) ''$.accident_location'',' + CHAR(13)
SET @sql = @sql + '[address_line_1] [varchar](max) ''$.address_line_1'',' + CHAR(13)
SET @sql = @sql + '[address_line_2] [varchar](max) ''$.address_line_2'',' + CHAR(13)
SET @sql = @sql + '[address_line_3] [varchar](max) ''$.address_line_3'',' + CHAR(13)
SET @sql = @sql + '[admin_timestamp] [varchar](max) ''$.admin_timestamp'',' + CHAR(13)
SET @sql = @sql + '[archived_key] [varchar](max) ''$.archived.key'',' + CHAR(13)
SET @sql = @sql + '[archived_display] [varchar](max) ''$.archived.display'',' + CHAR(13)
SET @sql = @sql + '[cas_number] [varchar](max) ''$.cas_number'',' + CHAR(13)
SET @sql = @sql + '[cas_or_ob_key] [varchar](max) ''$.cas_or_ob.key'',' + CHAR(13)
SET @sql = @sql + '[cas_or_ob_display] [varchar](max) ''$.cas_or_ob.display'',' + CHAR(13)
SET @sql = @sql + '[created_at] [varchar](max) ''$.created_at'',' + CHAR(13)
SET @sql = @sql + '[measurement1_try1] [varchar](max) ''$.measurement1_try1'',' + CHAR(13)
SET @sql = @sql + '[measurement1_try2] [varchar](max) ''$.measurement1_try2'',' + CHAR(13)
SET @sql = @sql + '[measurement1_try3] [varchar](max) ''$.measurement1_try3'',' + CHAR(13)
SET @sql = @sql + '[measurement2_try1] [varchar](max) ''$.measurement2_try1'',' + CHAR(13)
SET @sql = @sql + '[measurement2_try2] [varchar](max) ''$.measurement2_try2'',' + CHAR(13)
SET @sql = @sql + '[measurement2_try3] [varchar](max) ''$.measurement2_try3'',' + CHAR(13)
SET @sql = @sql + '[nature_of_injuries_key] [varchar](max) ''$.nature_of_injuries.key'',' + CHAR(13)
SET @sql = @sql + '[nature_of_injuries_display] [varchar](max) ''$.nature_of_injuries.display'',' + CHAR(13)
SET @sql = @sql + '[not_successful_reason] [varchar](max) ''$.not_successful_reason'',' + CHAR(13)
SET @sql = @sql + '[number_of_vehicles] [varchar](max) ''$.number_of_vehicles'',' + CHAR(13)
SET @sql = @sql + '[ob_number] [varchar](max) ''$.ob_number'',' + CHAR(13)
SET @sql = @sql + '[protocol_number] [varchar](max) ''$.protocol_number'',' + CHAR(13)
SET @sql = @sql + '[reading] [varchar](max) ''$.reading'',' + CHAR(13)
SET @sql = @sql + '[reading_timestamp] [varchar](max) ''$.reading_timestamp'',' + CHAR(13)
SET @sql = @sql + '[record_number] [varchar](max) ''$.record_number'',' + CHAR(13)
SET @sql = @sql + '[referred_key] [varchar](max) ''$.referred.key'',' + CHAR(13)
SET @sql = @sql + '[referred_display] [varchar](max) ''$.referred.display'',' + CHAR(13)
SET @sql = @sql + '[referred_location] [varchar](max) ''$.referred_location'',' + CHAR(13)
SET @sql = @sql + '[referred_type_key] [varchar](max) ''$.referred_type.key'',' + CHAR(13)
SET @sql = @sql + '[referred_type_display] [varchar](max) ''$.referred_type.display'',' + CHAR(13)
SET @sql = @sql + '[referred_type_other] [varchar](max) ''$.referred_type_other'',' + CHAR(13)
SET @sql = @sql + '[result_key] [varchar](max) ''$.result.key'',' + CHAR(13)
SET @sql = @sql + '[result_display] [varchar](max) ''$.result.display'',' + CHAR(13)
SET @sql = @sql + '[roadside_activity_key] [varchar](max) ''$.roadside_activity.key'',' + CHAR(13)
SET @sql = @sql + '[roadside_activity_display] [varchar](max) ''$.roadside_activity.display'',' + CHAR(13)
SET @sql = @sql + '[status_key] [varchar](max) ''$.status.key'',' + CHAR(13)
SET @sql = @sql + '[status_display] [varchar](max) ''$.status.display'',' + CHAR(13)
SET @sql = @sql + '[subject_age] [varchar](max) ''$.subject_age'',' + CHAR(13)
SET @sql = @sql + '[subject_date_of_birth] [varchar](max) ''$.subject_date_of_birth'',' + CHAR(13)
SET @sql = @sql + '[subject_full_name] [varchar](max) ''$.subject_full_name'',' + CHAR(13)
SET @sql = @sql + '[subject_gender_key] [varchar](max) ''$.subject_gender.key'',' + CHAR(13)
SET @sql = @sql + '[subject_gender_display] [varchar](max) ''$.subject_gender.display'',' + CHAR(13)
SET @sql = @sql + '[subject_identification] [varchar](max) ''$.subject_identification'',' + CHAR(13)
SET @sql = @sql + '[subject_identification_type_key] [varchar](max) ''$.subject_identification_type.key'',' + CHAR(13)
SET @sql = @sql + '[subject_identification_type_display] [varchar](max) ''$.subject_identification_type.display'',' + CHAR(13)
SET @sql = @sql + '[subject_id_number] [varchar](max) ''$.subject_id_number'',' + CHAR(13)
SET @sql = @sql + '[subject_initials] [varchar](max) ''$.subject_initials'',' + CHAR(13)
SET @sql = @sql + '[subject_occupation_sector_key] [varchar](max) ''$.subject_occupation_sector.key'',' + CHAR(13)
SET @sql = @sql + '[subject_occupation_sector_display] [varchar](max) ''$.subject_occupation_sector.display'',' + CHAR(13)
SET @sql = @sql + '[subject_photo] [varchar](max) ''$.subject_photo'',' + CHAR(13)
SET @sql = @sql + '[subject_photo_at_reading] [varchar](max) ''$.subject_photo_at_reading'',' + CHAR(13)
SET @sql = @sql + '[subject_surname] [varchar](max) ''$.subject_surname'',' + CHAR(13)
SET @sql = @sql + '[subject_tel_no] [varchar](max) ''$.subject_tel_no'',' + CHAR(13)
SET @sql = @sql + '[supporting_documents] [varchar](max) ''$.supporting_documents'',' + CHAR(13)
SET @sql = @sql + '[time_of_arrest] [varchar](max) ''$.time_of_arrest'',' + CHAR(13)
SET @sql = @sql + '[time_of_arrival] [varchar](max) ''$.time_of_arrival'',' + CHAR(13)
SET @sql = @sql + '[time_of_departure] [varchar](max) ''$.time_of_departure'',' + CHAR(13)
SET @sql = @sql + '[time_of_reading_start] [varchar](max) ''$.time_of_reading_start'',' + CHAR(13)
SET @sql = @sql + '[time_of_reading_stop] [varchar](max) ''$.time_of_reading_stop'',' + CHAR(13)
SET @sql = @sql + '[vehicle_colour] [varchar](max) ''$.vehicle_colour'',' + CHAR(13)
SET @sql = @sql + '[vehicle_make] [varchar](max) ''$.vehicle_make'',' + CHAR(13)
SET @sql = @sql + '[vehicle_registration_number] [varchar](max) ''$.vehicle_registration_number'',' + CHAR(13)
SET @sql = @sql + '[vehicle_type_key] [varchar](max) ''$.vehicle_type.key'',' + CHAR(13)
SET @sql = @sql + '[vehicle_type_display] [varchar](max) ''$.vehicle_type.display'',' + CHAR(13)
SET @sql = @sql + '[verified_at] [varchar](max) ''$.verified_at''' + CHAR(13)
--WITH End
SET @sql = @sql + ')' + CHAR(13)

EXEC(@SQL)


