CREATE TABLE [ebat].[ebat_report] (
    [id]                                  UNIQUEIDENTIFIER NULL,
    [type]                                VARCHAR (MAX)    NULL,
    [updated_at]                          VARCHAR (MAX)    NULL,
    [display]                             VARCHAR (MAX)    NULL,
    [centre_id]                           UNIQUEIDENTIFIER NULL,
    [completed_by_id]                     UNIQUEIDENTIFIER NULL,
    [driver_id]                           UNIQUEIDENTIFIER NULL,
    [ebat_device_id]                      UNIQUEIDENTIFIER NULL,
    [magistrates_court_id]                UNIQUEIDENTIFIER NULL,
    [officer_id]                          UNIQUEIDENTIFIER NULL,
    [operator_id]                         UNIQUEIDENTIFIER NULL,
    [reading_by_id]                       UNIQUEIDENTIFIER NULL,
    [registered_by_id]                    UNIQUEIDENTIFIER NULL,
    [station_id]                          UNIQUEIDENTIFIER NULL,
    [vehicle_id]                          UNIQUEIDENTIFIER NULL,
    [verified_by_id]                      UNIQUEIDENTIFIER NULL,
    [abort_comment]                       VARCHAR (MAX)    NULL,
    [abort_ob_number]                     VARCHAR (MAX)    NULL,
    [abort_reason]                        VARCHAR (MAX)    NULL,
    [accident_key]                        VARCHAR (MAX)    NULL,
    [accident_display]                    VARCHAR (MAX)    NULL,
    [accident_location]                   VARCHAR (MAX)    NULL,
    [address_line_1]                      VARCHAR (MAX)    NULL,
    [address_line_2]                      VARCHAR (MAX)    NULL,
    [address_line_3]                      VARCHAR (MAX)    NULL,
    [admin_timestamp]                     VARCHAR (MAX)    NULL,
    [archived_key]                        VARCHAR (MAX)    NULL,
    [archived_display]                    VARCHAR (MAX)    NULL,
    [cas_number]                          VARCHAR (MAX)    NULL,
    [cas_or_ob_key]                       VARCHAR (MAX)    NULL,
    [cas_or_ob_display]                   VARCHAR (MAX)    NULL,
    [created_at]                          VARCHAR (MAX)    NULL,
    [measurement1_try1]                   VARCHAR (MAX)    NULL,
    [measurement1_try2]                   VARCHAR (MAX)    NULL,
    [measurement1_try3]                   VARCHAR (MAX)    NULL,
    [measurement2_try1]                   VARCHAR (MAX)    NULL,
    [measurement2_try2]                   VARCHAR (MAX)    NULL,
    [measurement2_try3]                   VARCHAR (MAX)    NULL,
    [nature_of_injuries_key]              VARCHAR (MAX)    NULL,
    [nature_of_injuries_display]          VARCHAR (MAX)    NULL,
    [not_successful_reason]               VARCHAR (MAX)    NULL,
    [number_of_vehicles]                  VARCHAR (MAX)    NULL,
    [ob_number]                           VARCHAR (MAX)    NULL,
    [protocol_number]                     VARCHAR (MAX)    NULL,
    [reading]                             VARCHAR (MAX)    NULL,
    [reading_timestamp]                   VARCHAR (MAX)    NULL,
    [record_number]                       VARCHAR (MAX)    NULL,
    [referred_key]                        VARCHAR (MAX)    NULL,
    [referred_display]                    VARCHAR (MAX)    NULL,
    [referred_location]                   VARCHAR (MAX)    NULL,
    [referred_type_key]                   VARCHAR (MAX)    NULL,
    [referred_type_display]               VARCHAR (MAX)    NULL,
    [referred_type_other]                 VARCHAR (MAX)    NULL,
    [result_key]                          VARCHAR (MAX)    NULL,
    [result_display]                      VARCHAR (MAX)    NULL,
    [roadside_activity_key]               VARCHAR (MAX)    NULL,
    [roadside_activity_display]           VARCHAR (MAX)    NULL,
    [status_key]                          VARCHAR (MAX)    NULL,
    [status_display]                      VARCHAR (MAX)    NULL,
    [subject_age]                         VARCHAR (MAX)    NULL,
    [subject_date_of_birth]               VARCHAR (MAX)    NULL,
    [subject_full_name]                   VARCHAR (MAX)    NULL,
    [subject_gender_key]                  VARCHAR (MAX)    NULL,
    [subject_gender_display]              VARCHAR (MAX)    NULL,
    [subject_identification]              VARCHAR (MAX)    NULL,
    [subject_identification_type_key]     VARCHAR (MAX)    NULL,
    [subject_identification_type_display] VARCHAR (MAX)    NULL,
    [subject_id_number]                   VARCHAR (MAX)    NULL,
    [subject_initials]                    VARCHAR (MAX)    NULL,
    [subject_occupation_sector_key]       VARCHAR (MAX)    NULL,
    [subject_occupation_sector_display]   VARCHAR (MAX)    NULL,
    [subject_photo]                       VARCHAR (MAX)    NULL,
    [subject_photo_at_reading]            VARCHAR (MAX)    NULL,
    [subject_surname]                     VARCHAR (MAX)    NULL,
    [subject_tel_no]                      VARCHAR (MAX)    NULL,
    [supporting_documents]                VARCHAR (MAX)    NULL,
    [time_of_arrest]                      VARCHAR (MAX)    NULL,
    [time_of_arrival]                     VARCHAR (MAX)    NULL,
    [time_of_departure]                   VARCHAR (MAX)    NULL,
    [time_of_reading_start]               VARCHAR (MAX)    NULL,
    [time_of_reading_stop]                VARCHAR (MAX)    NULL,
    [vehicle_colour]                      VARCHAR (MAX)    NULL,
    [vehicle_make]                        VARCHAR (MAX)    NULL,
    [vehicle_registration_number]         VARCHAR (MAX)    NULL,
    [vehicle_type_key]                    VARCHAR (MAX)    NULL,
    [vehicle_type_display]                VARCHAR (MAX)    NULL,
    [verified_at]                         VARCHAR (MAX)    NULL,
    [DeltaLogKey]                         INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                            INT              DEFAULT ((-1)) NOT NULL
);

