CREATE TABLE [man].[FIOCNOTICES] (
    [NoticeType]             VARCHAR (5000) NULL,
    [NoticeNumber]           VARCHAR (5000) NULL,
    [Stage]                  VARCHAR (5000) NULL,
    [Status]                 VARCHAR (5000) NULL,
    [FNL]                    VARCHAR (5000) NULL,
    [OrigFine]               VARCHAR (5000) NULL,
    [CurrFine]               VARCHAR (5000) NULL,
    [WDAmt]                  VARCHAR (5000) NULL,
    [redcAmt]                VARCHAR (5000) NULL,
    [PaidFine]               VARCHAR (5000) NULL,
    [UneqPaid]               VARCHAR (5000) NULL,
    [ReceiptNumber]          VARCHAR (5000) NULL,
    [Payment Rec_Date]       VARCHAR (5000) NULL,
    [OffenceDate]            VARCHAR (5000) NULL,
    [IssueDate]              VARCHAR (5000) NULL,
    [RepDate]                VARCHAR (5000) NULL,
    [RepResultDate]          VARCHAR (5000) NULL,
    [NBSDate]                VARCHAR (5000) NULL,
    [SummonsGenerateDate]    VARCHAR (5000) NULL,
    [CourtDate]              VARCHAR (5000) NULL,
    [PaymentDueDate]         VARCHAR (5000) NULL,
    [CaseResultDate]         VARCHAR (5000) NULL,
    [WarrantDate]            VARCHAR (5000) NULL,
    [Cont empt]              VARCHAR (5000) NULL,
    [Method or Tender]       VARCHAR (5000) NULL,
    [Source or Origin]       VARCHAR (5000) NULL,
    [Contractor]             VARCHAR (5000) NULL,
    [PaymentCaptureDate]     VARCHAR (5000) NULL,
    [CourtCode]              VARCHAR (5000) NULL,
    [CourtName]              VARCHAR (5000) NULL,
    [Magistrates Court GUID] VARCHAR (5000) NULL,
    [Traffic Centre GUID]    VARCHAR (5000) NULL,
    [ID_NO]                  VARCHAR (5000) NULL,
    [Surname]                VARCHAR (5000) NULL,
    [Name]                   VARCHAR (5000) NULL,
    [Address1]               VARCHAR (5000) NULL,
    [Address2]               VARCHAR (5000) NULL,
    [Address3]               VARCHAR (5000) NULL,
    [Address4]               VARCHAR (5000) NULL,
    [Address5]               VARCHAR (5000) NULL,
    [PostCode]               VARCHAR (5000) NULL,
    [Regno]                  VARCHAR (5000) NULL,
    [Charge1]                VARCHAR (5000) NULL,
    [Charge2]                VARCHAR (5000) NULL,
    [Charge3]                VARCHAR (5000) NULL,
    [LastAction]             VARCHAR (5000) NULL,
    [LastActionDate]         VARCHAR (5000) NULL
);

