CREATE TABLE [man].[WesternCape_all_years_SUMMARY] (
    [md_or]                   NVARCHAR (MAX) NULL,
    [md_des]                  NVARCHAR (MAX) NULL,
    [waste_org]               NVARCHAR (MAX) NULL,
    [waste_via]               NVARCHAR (MAX) NULL,
    [waste_dest]              NVARCHAR (MAX) NULL,
    [National road allocated] NVARCHAR (MAX) NULL,
    [COMMODITY_NAME]          NVARCHAR (MAX) NULL,
    [PACKAGING_TYPE]          NVARCHAR (MAX) NULL,
    [SECTOR]                  NVARCHAR (MAX) NULL,
    [CARGO_TYPE]              NVARCHAR (MAX) NULL,
    [INDUSTRY_GROUP]          NVARCHAR (MAX) NULL,
    [DISTANCE]                FLOAT (53)     NULL,
    [ORIGINNEWG]              NVARCHAR (MAX) NULL,
    [DESTINATIO]              NVARCHAR (MAX) NULL,
    [Rail_Frien]              NVARCHAR (MAX) NULL,
    [Distance_C]              NVARCHAR (MAX) NULL,
    [GFB]                     NVARCHAR (MAX) NULL,
    [OProvince]               NVARCHAR (MAX) NULL,
    [DProvince]               NVARCHAR (MAX) NULL,
    [2017_Road_tons]          FLOAT (53)     NULL,
    [2017_Road_tonkms]        FLOAT (53)     NULL,
    [2017_Rail_tons]          FLOAT (53)     NULL,
    [2017_Rail_tonkms]        BIGINT         NULL,
    [2017_Rail_cost]          FLOAT (53)     NULL,
    [2017_Pipe_tons]          BIGINT         NULL,
    [2017_Pipe_tonkms]        BIGINT         NULL,
    [2017_Pipe_cost]          BIGINT         NULL,
    [2017_Total_tons]         FLOAT (53)     NULL,
    [2017_Total_tonkms]       FLOAT (53)     NULL,
    [2018_Total_tons]         FLOAT (53)     NULL,
    [2018_Total_tonkms]       FLOAT (53)     NULL,
    [2023_Total_tons]         FLOAT (53)     NULL,
    [2023_Total_tonkms]       FLOAT (53)     NULL,
    [2048_Total_tons]         FLOAT (53)     NULL,
    [2048_Total_tonkms]       FLOAT (53)     NULL,
    [Modal shift - Tonnes]    FLOAT (53)     NULL,
    [Modal shift - Tonnekms]  FLOAT (53)     NULL,
    [Depreciation]            FLOAT (53)     NULL,
    [Cost of Cap]             FLOAT (53)     NULL,
    [Licence]                 FLOAT (53)     NULL,
    [Toll Fees]               FLOAT (53)     NULL,
    [Insurance]               FLOAT (53)     NULL,
    [Driver]                  FLOAT (53)     NULL,
    [Fuel]                    FLOAT (53)     NULL,
    [Maintenance and Repairs] FLOAT (53)     NULL,
    [Tyres]                   FLOAT (53)     NULL,
    [Total Road cost]         FLOAT (53)     NULL,
    [Total Transport costs]   FLOAT (53)     NULL,
    [Road Accidents]          FLOAT (53)     NULL,
    [Road Congestion]         FLOAT (53)     NULL,
    [Road Emissions]          FLOAT (53)     NULL,
    [Road Landway]            FLOAT (53)     NULL,
    [Road Noise]              FLOAT (53)     NULL,
    [Road Policing]           FLOAT (53)     NULL,
    [Rail Accidents]          FLOAT (53)     NULL,
    [Rail Emissions]          FLOAT (53)     NULL,
    [Rail Landway]            FLOAT (53)     NULL,
    [Rail Noise]              FLOAT (53)     NULL,
    [Accidents]               FLOAT (53)     NULL,
    [Congestion]              FLOAT (53)     NULL,
    [Emissions]               FLOAT (53)     NULL,
    [Landway]                 FLOAT (53)     NULL,
    [Noise]                   FLOAT (53)     NULL,
    [Policing]                FLOAT (53)     NULL,
    [Total externality costs] FLOAT (53)     NULL,
    [Mode]                    NVARCHAR (MAX) NULL
);

