CREATE TABLE [model].[EBAT Incident] (
    [EBATIncidentKey]               INT              NOT NULL,
    [Accident Indicator]            VARCHAR (3)      NOT NULL,
    [Accident Location]             VARCHAR (50)     NOT NULL,
    [Case Number]                   VARCHAR (20)     NOT NULL,
    [EBAT Report Id]                UNIQUEIDENTIFIER NULL,
    [EBAT Status]                   VARCHAR (20)     NOT NULL,
    [Nature Of Injuries]            VARCHAR (20)     NOT NULL,
    [Not Successful Reason]         VARCHAR (50)     NOT NULL,
    [Number Of Vehicles]            INT              NOT NULL,
    [Protocol Number]               VARCHAR (10)     NOT NULL,
    [Reading Result]                NUMERIC (19, 2)  NULL,
    [Reading Result Category]       VARCHAR (20)     NOT NULL,
    [Record Number]                 VARCHAR (20)     NOT NULL,
    [Referred Indicator]            VARCHAR (3)      NOT NULL,
    [Referred Location]             VARCHAR (50)     NOT NULL,
    [Referred Type]                 VARCHAR (20)     NOT NULL,
    [Road Side Activity]            VARCHAR (50)     NOT NULL,
    [Subject Date Of Birth]         DATE             NULL,
    [Subject First Name]            VARCHAR (50)     NULL,
    [Subject Gender]                VARCHAR (20)     NOT NULL,
    [Subject Identification Number] VARCHAR (20)     NOT NULL,
    [Subject Identification Type]   VARCHAR (30)     NOT NULL,
    [Subject Initials]              VARCHAR (10)     NULL,
    [Subject Occupation Sector]     VARCHAR (50)     NOT NULL,
    [Subject Surname]               VARCHAR (50)     NULL,
    [Subject Telephone Number]      VARCHAR (15)     NOT NULL,
    [Vehicle Colour]                VARCHAR (20)     NOT NULL,
    [Vehicle Make]                  VARCHAR (20)     NOT NULL,
    [Vehicle Registration Number]   VARCHAR (20)     NOT NULL,
    [Vehicle Type]                  VARCHAR (20)     NOT NULL
);

