CREATE TABLE [model].[Impound Traffic Control Event] (
    [TrafficControlEventKey]               INT              NOT NULL,
    [Action Taken]                         VARCHAR (50)     NOT NULL,
    [Alcohol Level]                        VARCHAR (10)     NOT NULL,
    [Alcohol Screening]                    VARCHAR (30)     NOT NULL,
    [Arrival Time]                         DATETIME         NULL,
    [Blood Glucose Level]                  NUMERIC (11, 2)  NULL,
    [Blood Pressure Diastolic]             NUMERIC (11, 2)  NULL,
    [Blood Pressure Systolic]              NUMERIC (11, 2)  NULL,
    [Brake Taken Location]                 VARCHAR (50)     NULL,
    [Departure Point]                      VARCHAR (50)     NOT NULL,
    [Departure Time]                       DATETIME         NULL,
    [Destination]                          VARCHAR (50)     NOT NULL,
    [EMS Comments]                         VARCHAR (1000)   NULL,
    [EMS Testing Status]                   VARCHAR (20)     NOT NULL,
    [Event Completion Date Time]           DATETIME         NULL,
    [Event Open Date Time]                 DATETIME         NULL,
    [Event Source]                         VARCHAR (50)     NOT NULL,
    [Expected Duration Minutes]            NUMERIC (11, 2)  NULL,
    [Forced Close Reason]                  VARCHAR (50)     NOT NULL,
    [Forced Close Type]                    VARCHAR (50)     NOT NULL,
    [Has Alcohol And Drugs]                VARCHAR (3)      NOT NULL,
    [Has Disregarded Instructions]         VARCHAR (3)      NOT NULL,
    [Has Driving Violations]               VARCHAR (3)      NOT NULL,
    [Has Impound Violations]               VARCHAR (3)      NOT NULL,
    [Has Moving Violations]                VARCHAR (3)      NOT NULL,
    [Has No A G Violations]                VARCHAR (3)      NOT NULL,
    [Has Regulatory Signs]                 VARCHAR (3)      NOT NULL,
    [Has Road Markings]                    VARCHAR (3)      NOT NULL,
    [Has Speed Violations]                 VARCHAR (3)      NOT NULL,
    [Has Violation]                        VARCHAR (3)      NOT NULL,
    [Heart Rate]                           NUMERIC (11, 2)  NULL,
    [Impound Offence Date Time]            DATETIME         NULL,
    [Is Brake Taken]                       VARCHAR (3)      NOT NULL,
    [Is Enatis Feedback Reviewed]          VARCHAR (3)      NOT NULL,
    [Is Public Transport Survey Completed] VARCHAR (3)      NOT NULL,
    [Latitude]                             NUMERIC (19, 5)  NOT NULL,
    [Location]                             VARCHAR (50)     NOT NULL,
    [Longitude]                            NUMERIC (19, 5)  NOT NULL,
    [Number Of Passengers]                 INT              NULL,
    [Number Of People Wearing Seatbelts]   INT              NULL,
    [Police Station]                       VARCHAR (50)     NOT NULL,
    [Road Safety Comments]                 VARCHAR (1000)   NULL,
    [Road Safety Completed Date Time]      DATETIME         NULL,
    [Status Code]                          VARCHAR (30)     NOT NULL,
    [Traffic Control Event GUID]           UNIQUEIDENTIFIER NULL,
    [Travel Direction]                     VARCHAR (20)     NOT NULL,
    [Trip Type]                            VARCHAR (20)     NOT NULL
);

