CREATE TABLE [sampleitis].[activity_log] (
    [id]                           UNIQUEIDENTIFIER NULL,
    [type]                         NVARCHAR (MAX)   NULL,
    [updated_at]                   NVARCHAR (MAX)   NULL,
    [display]                      NVARCHAR (MAX)   NULL,
    [activity_id]                  UNIQUEIDENTIFIER NULL,
    [user_id]                      UNIQUEIDENTIFIER NULL,
    [archived_key]                 VARCHAR (MAX)    NULL,
    [archived_display]             VARCHAR (MAX)    NULL,
    [comment]                      VARCHAR (MAX)    NULL,
    [driver_id_number]             VARCHAR (MAX)    NULL,
    [driver_involved_key]          VARCHAR (MAX)    NULL,
    [driver_involved_display]      VARCHAR (MAX)    NULL,
    [location_latitude]            VARCHAR (MAX)    NULL,
    [location_longitude]           VARCHAR (MAX)    NULL,
    [location_altitude]            VARCHAR (MAX)    NULL,
    [location_horizontal_accuracy] VARCHAR (MAX)    NULL,
    [location_vertical_accuracy]   VARCHAR (MAX)    NULL,
    [location_timestamp]           VARCHAR (MAX)    NULL,
    [logged_at]                    VARCHAR (MAX)    NULL,
    [photo]                        VARCHAR (MAX)    NULL,
    [vehicle_reg_number]           VARCHAR (MAX)    NULL,
    [DeltaLogKey]                  INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                     INT              DEFAULT ((-1)) NOT NULL
);

