CREATE TABLE [sampleitis].[activity] (
    [id]                      UNIQUEIDENTIFIER NULL,
    [type]                    NVARCHAR (MAX)   NULL,
    [updated_at]              NVARCHAR (MAX)   NULL,
    [display]                 NVARCHAR (MAX)   NULL,
    [device_id]               UNIQUEIDENTIFIER NULL,
    [location_id]             UNIQUEIDENTIFIER NULL,
    [operational_area_id]     UNIQUEIDENTIFIER NULL,
    [shift_id]                UNIQUEIDENTIFIER NULL,
    [shift_statistic_id]      UNIQUEIDENTIFIER NULL,
    [task_description_id]     UNIQUEIDENTIFIER NULL,
    [traffic_centre_id]       UNIQUEIDENTIFIER NULL,
    [user_id]                 UNIQUEIDENTIFIER NULL,
    [activity_type_key]       VARCHAR (MAX)    NULL,
    [activity_type_display]   VARCHAR (MAX)    NULL,
    [adhoc_key]               VARCHAR (MAX)    NULL,
    [adhoc_display]           VARCHAR (MAX)    NULL,
    [comments]                VARCHAR (MAX)    NULL,
    [date]                    VARCHAR (MAX)    NULL,
    [description]             VARCHAR (MAX)    NULL,
    [end_time]                VARCHAR (MAX)    NULL,
    [gps_latitude]            VARCHAR (MAX)    NULL,
    [gps_longitude]           VARCHAR (MAX)    NULL,
    [gps_altitude]            VARCHAR (MAX)    NULL,
    [gps_horizontal_accuracy] VARCHAR (MAX)    NULL,
    [gps_vertical_accuracy]   VARCHAR (MAX)    NULL,
    [gps_timestamp]           VARCHAR (MAX)    NULL,
    [other_location]          VARCHAR (MAX)    NULL,
    [start]                   VARCHAR (MAX)    NULL,
    [start_time]              VARCHAR (MAX)    NULL,
    [DeltaLogKey]             INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                INT              DEFAULT ((-1)) NOT NULL
);

