CREATE TABLE [sampleitis].[month_statistic] (
    [id]                                  UNIQUEIDENTIFIER NULL,
    [type]                                NVARCHAR (MAX)   NULL,
    [updated_at]                          NVARCHAR (MAX)   NULL,
    [display]                             NVARCHAR (MAX)   NULL,
    [admin_id]                            UNIQUEIDENTIFIER NULL,
    [inspector_id]                        UNIQUEIDENTIFIER NULL,
    [superior_id]                         UNIQUEIDENTIFIER NULL,
    [traffic_centre_id]                   UNIQUEIDENTIFIER NULL,
    [appraisals]                          VARCHAR (MAX)    NULL,
    [complaints_from_public]              VARCHAR (MAX)    NULL,
    [completed_at]                        VARCHAR (MAX)    NULL,
    [cross_border_integrated_roadblocks]  VARCHAR (MAX)    NULL,
    [csf_cpf_meetings]                    VARCHAR (MAX)    NULL,
    [date]                                VARCHAR (MAX)    NULL,
    [drunken_driving_operations_actual]   VARCHAR (MAX)    NULL,
    [drunken_driving_operations_comments] VARCHAR (MAX)    NULL,
    [drunken_driving_operations_target]   VARCHAR (MAX)    NULL,
    [grievances]                          VARCHAR (MAX)    NULL,
    [kilometers_travelled]                VARCHAR (MAX)    NULL,
    [opened_at]                           VARCHAR (MAX)    NULL,
    [progressive_disciplinary_matters]    VARCHAR (MAX)    NULL,
    [report_type_key]                     VARCHAR (MAX)    NULL,
    [report_type_display]                 VARCHAR (MAX)    NULL,
    [signature]                           VARCHAR (MAX)    NULL,
    [speed_operations_actual]             VARCHAR (MAX)    NULL,
    [speed_operations_comments]           VARCHAR (MAX)    NULL,
    [speed_operations_target]             VARCHAR (MAX)    NULL,
    [status_key]                          VARCHAR (MAX)    NULL,
    [status_display]                      VARCHAR (MAX)    NULL,
    [traffic_updates_media]               VARCHAR (MAX)    NULL,
    [vehicles_stopped_checked_actual]     VARCHAR (MAX)    NULL,
    [vehicles_stopped_checked_comments]   VARCHAR (MAX)    NULL,
    [vehicles_stopped_checked_target]     VARCHAR (MAX)    NULL,
    [vehicles_weighed_actual]             VARCHAR (MAX)    NULL,
    [vehicles_weighed_comments]           VARCHAR (MAX)    NULL,
    [vehicles_weighed_target]             VARCHAR (MAX)    NULL,
    [workshops_attended]                  VARCHAR (MAX)    NULL,
    [DeltaLogKey]                         INT              DEFAULT ((-1)) NOT NULL,
    [AuditKey]                            INT              DEFAULT ((-1)) NOT NULL
);

