CREATE TABLE [cle].[Alerts] (
    [AlertRecordId]                INT                NOT NULL,
    [StorageDate]                  DATETIMEOFFSET (7) NOT NULL,
    [VRN]                          NVARCHAR (50)      NULL,
    [AlertDateTime]                DATETIMEOFFSET (7) NULL,
    [AlertId]                      NVARCHAR (50)      NULL,
    [SourceSystemId]               NVARCHAR (50)      NULL,
    [UserId]                       NVARCHAR (50)      NULL,
    [AlertStatus]                  INT                NULL,
    [AlertStatusDescription]       NVARCHAR (55)      NULL,
    [AlertType]                    NVARCHAR (50)      NULL,
    [AlertTypeId]                  INT                NULL,
    [AlertSubType]                 NVARCHAR (50)      NULL,
    [AlertSubTypeCode]             NVARCHAR (50)      NULL,
    [Latitude]                     FLOAT (53)         NULL,
    [Longitude]                    FLOAT (53)         NULL,
    [SightingId]                   NVARCHAR (100)     NULL,
    [AverageKmh]                   INT                NULL,
    [DeviceId]                     NVARCHAR (50)      NULL,
    [Lane]                         NVARCHAR (5)       NULL,
    [LaneDirectionCode]            NVARCHAR (5)       NULL,
    [LicenceNumber]                NVARCHAR (50)      NULL,
    [MainColour]                   NVARCHAR (50)      NULL,
    [MainColourCode]               NVARCHAR (5)       NULL,
    [Make]                         NVARCHAR (50)      NULL,
    [MakeCode]                     NVARCHAR (5)       NULL,
    [ModelName]                    NVARCHAR (50)      NULL,
    [ModelNameCode]                NVARCHAR (5)       NULL,
    [PrimarySightingDateTime]      DATETIMEOFFSET (7) NULL,
    [PrimarySightingId]            NVARCHAR (50)      NULL,
    [PrimaryInfraredImageFormat]   NVARCHAR (5)       NULL,
    [PrimaryOverviewImageFormat]   NVARCHAR (5)       NULL,
    [PrimarySiteName]              NVARCHAR (50)      NULL,
    [RoadSection]                  NVARCHAR (50)      NULL,
    [SecondarySightingDateTime]    DATETIMEOFFSET (7) NULL,
    [SecondarySightingId]          NVARCHAR (50)      NULL,
    [SecondaryInfraredImageFormat] NVARCHAR (5)       NULL,
    [SecondaryOverviewImageFormat] NVARCHAR (5)       NULL,
    [SecondarySiteName]            NVARCHAR (50)      NULL,
    [SpeedLimit]                   INT                NULL,
    [VehicleCategory]              NVARCHAR (150)     NULL,
    [VehicleCategoryCode]          NVARCHAR (5)       NULL,
    [VehicleDirectionCode]         NVARCHAR (50)      NULL,
    [VehicleSpeedClass]            NVARCHAR (50)      NULL,
    [VehicleSpeedClassCode]        NVARCHAR (5)       NULL,
    [VehicleUsage]                 NVARCHAR (50)      NULL,
    [VehicleUsageCode]             NVARCHAR (5)       NULL,
    [IsIgnoredForS341]             BIT                NULL,
    [DeltaLogKey]                  INT                NULL
);


GO
CREATE NONCLUSTERED INDEX [idxDeltaLogKey]
    ON [cle].[Alerts]([DeltaLogKey] ASC);

