CREATE TABLE [cle].[Sightings] (
    [SightingRecordId]           INT                NOT NULL,
    [StorageTimestamp]           DATETIMEOFFSET (7) NOT NULL,
    [ProviderId]                 NVARCHAR (50)      NOT NULL,
    [CameraId]                   NVARCHAR (50)      NOT NULL,
    [InstanceID]                 NVARCHAR (30)      NOT NULL,
    [Timestamp]                  DATETIMEOFFSET (7) NOT NULL,
    [TimestampError]             INT                NULL,
    [LaneID]                     INT                NOT NULL,
    [VehicleDirection]           NVARCHAR (10)      NOT NULL,
    [XYType]                     NVARCHAR (10)      NULL,
    [XCoord]                     FLOAT (53)         NULL,
    [YCoord]                     FLOAT (53)         NULL,
    [PlateNotRead]               BIT                NOT NULL,
    [VRN]                        NVARCHAR (10)      NULL,
    [VRNConfidence]              INT                NULL,
    [Country]                    NVARCHAR (5)       NULL,
    [Tag]                        INT                NULL,
    [TagConfidence]              INT                NULL,
    [Classification]             INT                NULL,
    [Make]                       NVARCHAR (50)      NULL,
    [Model]                      NVARCHAR (50)      NULL,
    [Colour]                     NVARCHAR (50)      NULL,
    [Velocity]                   INT                NULL,
    [VelocityError]              INT                NULL,
    [BOF_LaneDirection]          NVARCHAR (5)       NULL,
    [BOF_PrimaryVehicle]         BIT                NULL,
    [BOF_GPSQuality]             INT                NULL,
    [BOF_NumberOfSatellites]     INT                NULL,
    [BOF_GSMSignalStrength]      INT                NULL,
    [BOF_GPSSyncTime]            DATETIMEOFFSET (7) NULL,
    [BOF_SatelliteFixes]         INT                NULL,
    [BOF_EnrichData]             BIT                NULL,
    [DiagnosticTimestamp]        DATETIMEOFFSET (7) NULL,
    [DiagnosticType]             NVARCHAR (20)      NULL,
    [MeanTotalCurrent]           INT                NULL,
    [MeanSignalStrength]         INT                NULL,
    [MeanCpuTemperature]         INT                NULL,
    [HostName]                   NVARCHAR (50)      NULL,
    [LastSyncTime]               DATETIMEOFFSET (7) NULL,
    [MeanIlluminatorTemperature] INT                NULL,
    [MeanIlluminatorCurrent]     INT                NULL,
    [IlluminatorUsage]           INT                NULL,
    [MeanIlluminatorOutput]      INT                NULL,
    [LastResetTime]              DATETIMEOFFSET (7) NULL,
    [NumberOfHardwareErrors]     INT                NULL,
    [MeanCommsLag]               INT                NULL,
    [WorstCommsLag]              INT                NULL,
    [NoOfCommsResends]           INT                NULL,
    [NoOfCommsFailures]          INT                NULL,
    [NoOfCommsReconnects]        INT                NULL,
    [MeanSyncDifference]         INT                NULL,
    [WorstSyncDifference]        INT                NULL,
    [SupplyVoltage]              INT                NULL,
    [TamperAlarm]                NVARCHAR (30)      NULL,
    [MessageId]                  NVARCHAR (50)      NULL,
    [PartyKey]                   NVARCHAR (100)     NULL,
    [OverviewImageId]            NVARCHAR (120)     NULL,
    [OverviewImageType]          NVARCHAR (20)      NULL,
    [OverviewImageFormat]        NVARCHAR (5)       NULL,
    [InfraredImageId]            NVARCHAR (120)     NULL,
    [InfraredImageType]          NVARCHAR (20)      NULL,
    [InfraredImageFormat]        NVARCHAR (5)       NULL,
    [MatchedSightingPartyKey]    NVARCHAR (100)     NULL,
    [DeltaLogKey]                INT                NULL
);


GO
CREATE NONCLUSTERED INDEX [idxDeltaLogKey]
    ON [cle].[Sightings]([DeltaLogKey] ASC)
    INCLUDE([Timestamp], [VRN]);

