CREATE TABLE [cle].[VehicleEnquiryResponses] (
    [VehicleEnquiryResponseRecordId] INT                NOT NULL,
    [StorageTimestamp]               DATETIMEOFFSET (7) NOT NULL,
    [MessageId]                      NVARCHAR (50)      NOT NULL,
    [Timestamp]                      DATETIMEOFFSET (7) NULL,
    [Notes]                          NVARCHAR (MAX)     NULL,
    [AreaAuthority]                  NVARCHAR (50)      NULL,
    [AreaAuthorityCode]              NVARCHAR (10)      NULL,
    [AreaUserGroup]                  NVARCHAR (50)      NULL,
    [AreaUserGroupCode]              NVARCHAR (10)      NULL,
    [BusinessOrSurname]              NVARCHAR (100)     NULL,
    [DcceAddress]                    NVARCHAR (100)     NULL,
    [EconomicSector]                 NVARCHAR (50)      NULL,
    [EconomicSectorCode]             NVARCHAR (5)       NULL,
    [IdDocumentNumber]               NVARCHAR (50)      NULL,
    [IdDocumentType]                 NVARCHAR (50)      NULL,
    [IdDocumentTypeCode]             NVARCHAR (5)       NULL,
    [Initials]                       NVARCHAR (5)       NULL,
    [Nationality]                    NVARCHAR (50)      NULL,
    [NationalityCode]                NVARCHAR (5)       NULL,
    [NatureOfOwnership]              NVARCHAR (50)      NULL,
    [NatureOfOwnershipCode]          NVARCHAR (5)       NULL,
    [NatureOfPerson]                 NVARCHAR (50)      NULL,
    [NatureOfPersonCode]             NVARCHAR (5)       NULL,
    [OwnershipStartDate]             DATETIMEOFFSET (7) NULL,
    [OwnershipStatus]                NVARCHAR (50)      NULL,
    [OwnershipStatusCode]            NVARCHAR (5)       NULL,
    [OwnershipType]                  NVARCHAR (50)      NULL,
    [OwnershipTypeCode]              NVARCHAR (5)       NULL,
    [PersonNumber]                   NVARCHAR (50)      NULL,
    [PostalAddress]                  NVARCHAR (255)     NULL,
    [StreetAddress]                  NVARCHAR (255)     NULL,
    [VehicleUsage]                   NVARCHAR (50)      NULL,
    [VehicleUsageCode]               NVARCHAR (5)       NULL,
    [CapacitySitting]                INT                NULL,
    [CapacityStanding]               INT                NULL,
    [Category]                       NVARCHAR (50)      NULL,
    [CategoryCode]                   NVARCHAR (5)       NULL,
    [CountryOfExport]                NVARCHAR (50)      NULL,
    [CountryOfExportCode]            NVARCHAR (5)       NULL,
    [DataOwner]                      NVARCHAR (50)      NULL,
    [DataOwnerCode]                  NVARCHAR (5)       NULL,
    [Description]                    NVARCHAR (50)      NULL,
    [DescriptionCode]                NVARCHAR (5)       NULL,
    [DifferentialNumber]             NVARCHAR (50)      NULL,
    [Driven]                         NVARCHAR (50)      NULL,
    [DrivenCode]                     NVARCHAR (5)       NULL,
    [EngineDisplacement]             INT                NULL,
    [EngineNumber]                   NVARCHAR (50)      NULL,
    [FirstLicensingDate]             DATETIMEOFFSET (7) NULL,
    [FuelType]                       NVARCHAR (50)      NULL,
    [FuelTypeCode]                   NVARCHAR (5)       NULL,
    [GearboxNumber]                  NVARCHAR (50)      NULL,
    [GVM]                            INT                NULL,
    [LicenceChangeDate]              DATETIMEOFFSET (7) NULL,
    [LicenceExpiryDate]              DATETIMEOFFSET (7) NULL,
    [LicenceLiabilityDate]           DATETIMEOFFSET (7) NULL,
    [LicenceNumber]                  NVARCHAR (20)      NULL,
    [LicenceCertificateNumber]       NVARCHAR (50)      NULL,
    [LifeStatus]                     NVARCHAR (50)      NULL,
    [LifeStatusCode]                 NVARCHAR (5)       NULL,
    [MainColour]                     NVARCHAR (50)      NULL,
    [MainColourCode]                 NVARCHAR (5)       NULL,
    [Make]                           NVARCHAR (50)      NULL,
    [MakeCode]                       NVARCHAR (5)       NULL,
    [MicrodotAppliedDate]            DATETIMEOFFSET (7) NULL,
    [MicrodotPin]                    NVARCHAR (50)      NULL,
    [MicrodotUserGroup]              NVARCHAR (50)      NULL,
    [MicrodotUserGroupCode]          NVARCHAR (50)      NULL,
    [ModelName]                      NVARCHAR (50)      NULL,
    [ModelNameCode]                  NVARCHAR (5)       NULL,
    [ModelNumber]                    INT                NULL,
    [NetPower]                       INT                NULL,
    [PrePreviousLicenceNumber]       NVARCHAR (20)      NULL,
    [PreviousLicenceNumber]          NVARCHAR (20)      NULL,
    [RegAuthorityOfLicensing]        NVARCHAR (50)      NULL,
    [RegAuthorityOfLicensingCode]    NVARCHAR (5)       NULL,
    [RegAuthorityOfRegistration]     NVARCHAR (50)      NULL,
    [RegAuthorityOfRegistrationCode] NVARCHAR (50)      NULL,
    [RegistrationDate]               DATETIMEOFFSET (7) NULL,
    [RegistrationQualifier]          NVARCHAR (30)      NULL,
    [RegistrationQualifierCode]      NVARCHAR (5)       NULL,
    [RegistrationQualifierDate]      DATETIMEOFFSET (7) NULL,
    [RoadworthyStatus]               NVARCHAR (50)      NULL,
    [RoadworthyStatusCode]           NVARCHAR (5)       NULL,
    [RoadworthyTestDate]             DATETIMEOFFSET (7) NULL,
    [SapClearanceDate]               DATETIMEOFFSET (7) NULL,
    [SapClearanceReasonCodes]        NVARCHAR (50)      NULL,
    [SapClearanceReasons]            NVARCHAR (MAX)     NULL,
    [SapClearanceStatus]             NVARCHAR (50)      NULL,
    [SapClearanceStatusCode]         NVARCHAR (5)       NULL,
    [SapMark]                        NVARCHAR (MAX)     NULL,
    [SapMarkCode]                    NVARCHAR (5)       NULL,
    [SapMarkDate]                    DATETIMEOFFSET (7) NULL,
    [Tare]                           INT                NULL,
    [Transmission]                   NVARCHAR (30)      NULL,
    [TransmissionCode]               NVARCHAR (5)       NULL,
    [UnitNumber]                     NVARCHAR (50)      NULL,
    [VehicleRegisterNumber]          NVARCHAR (50)      NULL,
    [VehicleState]                   NVARCHAR (50)      NULL,
    [VehicleStateCode]               NVARCHAR (5)       NULL,
    [VehicleStateDate]               DATETIMEOFFSET (7) NULL,
    [VinOrChassis]                   NVARCHAR (50)      NULL,
    [Archived]                       BIT                NOT NULL,
    [SpeedClass]                     NVARCHAR (5)       NULL,
    [Deltalogkey]                    INT                NULL
);


GO
CREATE NONCLUSTERED INDEX [idxDeltaLogKey]
    ON [cle].[VehicleEnquiryResponses]([Deltalogkey] ASC);

